### PR TITLE
#1825 Made `+inf.minus` and `-inf.minus` work with multiple arguments

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Closes: #1825

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@Graur please take a look

**Review by Graur — APPROVED** [review]
@maxonfjvipon Looks good to me, thanks!
@yegor256 Please, have a look

**Comment by maxonfjvipon** [comment]
@yegor256 please have a look

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
