### PR TITLE
feat(#2352): Remove ChCompound

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
Remove `ChCompound` and `ChCompoundTest` since they aren't used.

Closes: #2352

---

### Detailed summary

- Deleted `ChCompound.java` and `ChCompoundTest.java` files.
- Replaced `ChCompound` import with `ChRemote` import.
- Updated the argument passed to `ChRemote` constructor in the `pullsFromProbes` method.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
@maxonfjvipon Could you take a look, please?

**Review by maxonfjvipon — APPROVED** [review]
@volodya-lombrozo LGTM! Thanks

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you merge that changes, please?

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
