### PR TITLE
1542 home version check

### LINKED ISSUE #1542: make sure all objects have +home and +version meta
Let's add a test to Makefile, which will make sure all `.eo` objects have `+home` meta, which has a URL as a tail. Also, let's check for the presence of `+version` meta with a SemVer in the tail.

### PR DESCRIPTION
**Pull request by levBagryansky**
resolves #1542 
`+home` meta check.

### CODE REVIEW

**Comment by levBagryansky** [comment]
@Graur please check.
I do not think troubles with windows checks are in this pr, check #1781

**Comment by Graur** [comment]
@levBagryansky Let me check it first

**Review by Graur — APPROVED** [review]
@levBagryansky Indeed, this error is not related to your changes. We will fix it in a separated pull request.
@yegor256 Please, have a look

**Comment by levBagryansky** [comment]
@yegor256 please take a look.

**Comment by yegor256** [comment]
@rultor merge

**Comment by Graur** [comment]
@yegor256 @levBagryansky I believe we should merge #1805 first

**Comment by levBagryansky** [comment]
@Graur There is quite unclear error in log:
```
[INFO]      [exec] /home/r/repo/eo-parser/src/main/resources/org/eolang/parser/synthetic-references.xsl looks good
[INFO]      [exec] /home/r/repo/eo-parser/src/main/resources/org/eolang/parser/vars-float-up.xsl looks good
[INFO]      [exec] /home/r/repo/eo-parser/src/main/resources/org/eolang/parser/warnings/correct-package-meta.xsl looks good
[INFO]      [exec] /home/r/repo/eo-parser/src/main/resources/org/eolang/parser/warnings/duplicate-metas.xsl looks good
[INFO]      [exec] /home/r/repo/eo-parser/src/main/resources/org/eolang/parser/warnings/incorrect-architect.xsl looks good
[INFO]      [exec] <?xml version="1.0" encoding="UTF-8"?>\n
[INFO]      [exec] <!--\n
[INFO]      [exec] The MIT License (MIT)\n
[INFO]      [exec] \n
[INFO]      [exec] Copyright (c) 2016-2023 Objectionary.com\n
[INFO]      [exec] \n
[INFO]      [exec] Permission is hereby granted, free of charge, to any person obtaining a copy\n
[INFO]      [exec] of this software and associated documentation files (the "Software"), to deal\n
[INFO]      [exec] in the Software without restriction, including without limitation the rights\n
[INFO]      [exec] to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n
[INFO]      [exec] copies of the Software, and to permit persons to whom the Software is\n
[INFO]      [exec] furnished to do so, subject to the following conditions:\n
[INFO]      [exec] \n
[INFO]      [exec] The above copyright notice and this permission notice shall be included\n
[INFO]      [exec] in all copies or substantial portions of the Software.\n
[INFO]      [exec] \n
[INFO]      [exec] THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n
[INFO]      [exec] IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n
[INFO]      [exec] FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE\n
[INFO]      [exec] AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n
[INFO]      [exec] LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n
[INFO]      [exec] OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\n
[INFO]      [exec] SOFTWARE.\n
[INFO]      [exec] -->\n
[INFO]      [exec] <xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" id="incorrect-home" version="2.0">\n
[INFO]      [exec]   <xsl:output encoding="UTF-8" method="xml"/>\n
[INFO]      [exec]   <xsl:template match="/program/errors">\n
[INFO]      [exec]     <xsl:copy>\n
[INFO]      [exec]       <xsl:apply-templates select="node()|@*"/>\n
[INFO]      [exec]       <xsl:for-each select="/program/metas/meta">\n
[INFO]      [exec]         <xsl:variable name="meta-head" select="head"/>\n
[INFO]      [exec]         <xsl:variable name="meta-tail" select="tail"/>\n
[INFO]      [exec]         <xsl:if test="$meta-head='home' and not(matches($meta-tail, '^(?:http(s)?://)?[\w.-]+(?:\.[\w\.-]+)+[\w\-\._~:/?#\[\]@!\$&amp;&apos;'\(\)\*\+,;=.]+$'))">\n        <xsl:if test="$meta-head='home' and not(matches($meta-tail, '^(?:http(s)?://)?[\w.-]+(?:\.[\w\.-]+)+[\w\-\._~:/?#\[\]@!\$&amp;amp;''\(\)\*\+,;=.]+$'))&quot;&gt;\n
[INFO]      [exec]           &lt;xsl:element name=&quot;error&quot;&gt;\n
[INFO]      [exec]             &lt;xsl:attribute name=&quot;check&quot;&gt;\n
[INFO]      [exec]               <xsl:text>incorrect-home</xsl:text>\n
[INFO]      [exec]             </xsl:attribute>\n
[INFO]      [exec]             <xsl:attribute name="line">\n
[INFO]      [exec]               <xsl:value-of select="@line"/>\n
[INFO]      [exec]             </xsl:attribute>\n
[INFO]      [exec]             <xsl:attribute name="severity">\n
[INFO]      [exec]               <xsl:text>warning</xsl:text>\n
[INFO]      [exec]             </xsl:attribute>\n
[INFO]      [exec]             <xsl:text>Wrong format of home url "</xsl:text>\n
[INFO]      [exec]             <xsl:value-of select="$meta-tail"/>\n
[INFO]      [exec]             &lt;xsl:text&gt;&quot;&lt;/xsl:text&gt;\n
[INFO]      [exec]           &lt;/xsl:element&gt;\n
[INFO]      [exec]         &lt;/xsl:if&gt;\n
[INFO]      [exec]       &lt;/xsl:for-each>\n
[INFO]      [exec]     </xsl:copy>\n
[INFO]      [exec]   </xsl:template>\n
[INFO]      [exec]   <xsl:template match="node()|@*">\n
[INFO]      [exec]     <xsl:copy>\n
[INFO]      [exec]       <xsl:apply-templates select="node()|@*"/>\n
[INFO]      [exec]     </xsl:copy>\n
[INFO]      [exec]   </xsl:template>\n
[INFO]      [exec] </xsl:stylesheet>\n
[INFO]      [exec] Invalid XML formatting in /home/r/repo/eo-parser/src/main/resources/org/eolang/parser/warnings/incorrect-home.xsl
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for eo 1.0-SNAPSHOT:
```

What  does `Invalid XML formatting` mean?

**Comment by Graur** [comment]
@levBagryansky You can check your xml file by [xcop](https://github.com/yegor256/xcop)

**Comment by levBagryansky** [comment]
@yegor256 please take a look

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
