### PR TITLE
#1418 make Placed attrs distinguishable

### PR DESCRIPTION
**Pull request by mximp**
#1418 make Placed attrs distinguishable

### CODE REVIEW

**Review by volodya-lombrozo — APPROVED** [review]
The only question - what is "PLD"?

**Comment by yegor256** [comment]
@volodya-lombrozo it's for "PLaceD", I believe

**Comment by yegor256** [comment]
@rultor merge

**Comment by mximp** [comment]
> The only question - what is "PLD"?

@volodya-lombrozo It's short for "placed"

**Pull request merged**
