### PR TITLE
feat(#2211): `memory` behaves as bytes

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Closes: #2211

Desc: every time `memory` gets an object, it dataizes that object, converts to bytes and start behaves like this bytes

---

## PR-Codex overview
This PR focuses on updating the `EOmemory` object in the codebase. 

### Detailed summary
- `EOmemory` now behaves as bytes.
- `EOmemory` can be taken as an integer and updated.
- The written value can be read immediately after writing.
- The `as-string` attribute is added to `EOmemory`.

> The following files were skipped due to too many changes: `eo-runtime/src/test/java/EOorg/EOeolang/EOmemoryTest.java`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@Graur please review this one

**Review by Graur — APPROVED** [review]
@maxonfjvipon Looks good ot me, thanks!
@yegor256 Please, have a look

**Comment by maxonfjvipon** [comment]
@yegor256 please have a look

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
