### PR TITLE
feat(#3251): `console` object + some inputs/outputs objects

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Ref: #3251

What's done:
- Introduced `console` object which can `read` from and `write` to standard operating system console
- Objects `stdout` and `stdin` are implemented in EO and uses the object `console`
- Introduced `bytes-as-input` object
- Introduced `malloc-as-output` object
- Introduced `uname` object which represents operating system name
- Introduced `line-separator` object which returns `"\n"` of unix OS and `"\r\n"` for windows OS
- Fixed some documentation
- Some objects are pretty formatted

---

## PR-Codex overview
This PR focuses on adding new objects and improving existing ones in the EO language runtime. 

### Detailed summary
- Added `while` object for loop functionality
- Updated `stdout` object in `io` package
- Added `range` object constructor
- Updated dependencies in `SnippetTestCase.java`
- Improved `malloc` object functionality

> The following files were skipped due to too many changes: `eo-runtime/src/main/eo/org/eolang/txt/regex.eo`, `eo-runtime/src/test/eo/org/eolang/sys/uname-test.eo`, `eo-runtime/src/test/eo/org/eolang/io/console-tests.eo`, `eo-runtime/src/main/java/EOorg/EOeolang/EOio/EOstdout.java`, `eo-runtime/src/test/eo/org/eolang/io/bytes-as-input-test.eo`, `eo-runtime/src/main/eo/org/eolang/sys/line-separator.eo`, `eo-runtime/src/main/eo/org/eolang/sys/uname.eo`, `eo-runtime/src/test/eo/org/eolang/io/malloc-as-output-test.eo`, `eo-runtime/src/main/eo/org/eolang/io/stdin.eo`, `eo-runtime/src/main/eo/org/eolang/txt/text.eo`, `eo-runtime/src/test/java/EOorg/EOeolang/EOnumberTest.java`, `eo-runtime/src/main/java/EOorg/EOeolang/EOio/Input.java`, `eo-runtime/src/main/eo/org/eolang/io/malloc-as-output.eo`, `eo-runtime/src/main/eo/org/eolang/io/bytes-as-input.eo`, `eo-runtime/src/main/eo/org/eolang/io/console.eo`, `eo-runtime/src/test/java/EOorg/EOeolang/EOio/EOstdinTest.java`, `eo-runtime/src/test/java/EOorg/EOeolang/EOio/EOconsoleTest.java`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Review by yegor256 — APPROVED** [review]
@rultor merge

**Comment by maxonfjvipon** [comment]
@rultor status

**Comment by 0crat** [comment]
@yegor256 Thanks for the review! You've earned +55 points for this: +25 as a basis; +40 for the 1586 hits-of-code that you reviewed; -10 for too few (1) comments.  Your running balance is [+157](https://www.eolang.org/zerocracy/objectionary-vitals.html).

**Pull request merged**
