### PR TITLE
reports-check.yml

### PR DESCRIPTION
**Pull request by h1alexbel**
@maxonfjvipon, @yegor256 what do you think?

This action will validate the quality of incoming bug reports (GitHub issues here) and post the possible improvements to the author of that report. Example of work: 

image

More information you can find in our [README](https://github.com/tracehubpm/reports-check-action)

---

## PR-Codex overview
This PR adds a GitHub Actions workflow `reports-check` to monitor and check issues using the `reports-check-action` for improved issue management.

### Detailed summary
- Added a new GitHub Actions workflow `reports-check.yml`
- Workflow triggers on opened issues
- Permissions set to write for issues and read for contents
- Job runs on Ubuntu 22.04
- Utilizes `actions/checkout` and `tracehubpm/reports-check-action`
- Passes GitHub and OpenAI tokens for authentication

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@h1alexbel good one, I like it. But I have one question: we have so many tickets created by `pdd` bot, I'm sure you know it. The explanation of problem is hidden in source code there. What will this reports checker say about such tickets?

**Comment by yegor256** [comment]
@maxonfjvipon let's find out

**Comment by h1alexbel** [comment]
@maxonfjvipon @yegor256 for now this action does not support puzzles, our plan is to add this support: https://github.com/tracehubpm/reports-check-action/issues/49

**Comment by h1alexbel** [comment]
@maxonfjvipon @yegor256 now we do support puzzle analysis, check out the latest doc https://github.com/tracehubpm/reports-check-action?tab=readme-ov-file#puzzle-pdd-analysis

**Pull request merged**
