### PR TITLE
fix(#2739): phi-to-xmir fails on error

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Closes: #2739 

---

## PR-Codex overview
This PR focuses on improving error handling in the `PhiSyntax` class and adding a new test case in `PhiSyntaxTest`. 

### Detailed summary
- Added a new constructor in `PhiSyntax` to be used for tests.
- Modified the `PhiSyntax` class to accumulate parsing errors during compilation.
- Updated the `UnphiMojo` class to check for parsing errors and throw an exception if any errors are found.
- Added a new test case in `PhiSyntaxTest` to verify that errors are correctly added to the XML output.

> The following files were skipped due to too many changes: `eo-parser/src/main/java/org/eolang/parser/ParsingErrors.java`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@yegor256 please have a look

**Review by yegor256 — APPROVED** [review]
LGTM

**Comment by maxonfjvipon** [comment]
@yegor256 please merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by maxonfjvipon** [comment]
@yegor256 please try to merge one more time, if failed because of #2727

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
