### PR TITLE
fix(#3004): fibonacci test is enabled

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Closes: #3004 

---

## PR-Codex overview
This PR focuses on enabling the test `calculates-fibonacci-number-with-recursion` in `int-tests.eo`.

### Detailed summary
- Enabled the test `calculates-fibonacci-number-with-recursion`.
- Modified the comparison operator in the test.
- Updated the expected result value in the test.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
@rultor merge

**Comment by maxonfjvipon** [comment]
@yegor256 Rultor fails:
image

Let's try again?

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
