### PR TITLE
#1130 Make Place to copy missing dependencies

### PR DESCRIPTION
**Pull request by mximp**
Fix for #1130

### CODE REVIEW

**Comment by mximp** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
@mximp I have a strong feeling that we are violating the SRP principle here. This mojo is now doing two things: placing once, and replacing when it's gone. How about we create a new `ReplaceMojo`, which will do the second part of the job -- it not found, place again. We keep `PlaceMojo` untouched. Then, we run both `PlaceMojo` and then `ReplaceMojo` from `AssembleMojo`. WDYT?

**Comment by mximp** [comment]
> @mximp I have a strong feeling that we are violating the SRP principle here. This mojo is now doing two things: placing once, and replacing when it's gone. How about we create a new `ReplaceMojo`, which will do the second part of the job -- it not found, place again. We keep `PlaceMojo` untouched. Then, we run both `PlaceMojo` and then `ReplaceMojo` from `AssembleMojo`. WDYT?

@yegor256 `re-placing` in this case just means that we extending scope of the files we copy. It's absolutely the same set of steps performed. So conceptually we don't add any new responsibility/functionality. 
And technically if we are to create `ReplaceMojo` we would have to copy-paste most of `PlaceMojo`.
So I believe creation of new object in this case is slight overkill. Or can you suggest what this new object would do?

Just to make sure we are on the same page: by **replace** I mean to place again and not to substitute something.

Do you agree?

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
