### PR TITLE
fix(#2993): OPENAI_API_KEY

### LINKED ISSUE #2993: Provide `secrets.OPENAI_TOKEN` in order to make `reports-check.yml` analyze submitted bug reports/puzzle
in [reports-check.yml](https://github.com/objectionary/eo/blob/master/.github/workflows/reports-check.yml) we assigning `OPENAI_TOKEN` to `openai_token` input. For now, action stays quiet probably due to `OPENAI_TOKEN` is not defined in the [secrets of the repo](https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions). Lets define it and track correct execution of this action.

https://github.com/objectionary/eo/blob/40393e883f51607ed552ba743f9d41b27cdaf3af/.github/workflows/reports-check.yml#L17

### PR DESCRIPTION
**Pull request by h1alexbel**
@maxonfjvipon take a look, please
closes #2993

---

## PR-Codex overview
This PR updates the OpenAI token in the reports-check GitHub workflow.

### Detailed summary
- Updated the OpenAI token in `.github/workflows/reports-check.yml` from `${{ secrets.OPENAI_TOKEN }}` to `${{ secrets.OPENAI_API_KEY }}`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by h1alexbel** [comment]
@maxonfjvipon @yegor256 we also enhanced [reports-check-action](https://github.com/tracehubpm/reports-check-action) with [puzzle analysis](https://github.com/tracehubpm/reports-check-action?tab=readme-ov-file#puzzle-pdd-analysis) and [configurable regular expressions](https://github.com/tracehubpm/reports-check-action?tab=readme-ov-file#issues-to-ignore) for issues to ignore

**Comment by maxonfjvipon** [comment]
@h1alexbel please restart CI by pushing some one more commit

**Comment by h1alexbel** [comment]
@maxonfjvipon all checks passed

**Review by maxonfjvipon — APPROVED** [review]
@h1alexbel LGTM! Thanks
@yegor256 please check

**Pull request merged**
