### PR TITLE
feat(#3283): replaced `float` and `int` with `number`

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Closes: #3283

---

## PR-Codex overview
This PR updates the codebase to replace `int` with `number` for improved type consistency and precision.

### Detailed summary
- Replaced `int` with `number` for type consistency
- Updated method names for clarity
- Improved error handling and test coverage
- Enhanced code readability and maintainability

> The following files were skipped due to too many changes: `eo-runtime/src/main/eo/org/eolang/txt/sscanf.eo`, `eo-maven-plugin/src/main/resources/org/eolang/maven/pre/to-java.xsl`, `eo-parser/src/test/resources/org/eolang/parser/packs/syntax/post-method.yaml`, `eo-runtime/src/test/eo/org/eolang/dataized-tests.eo`, `eo-maven-plugin/src/test/resources/org/eolang/maven/sodgs/data.yaml`, `eo-parser/src/test/resources/org/eolang/parser/packs/syntax/bound-reversed-application.yaml`, `eo-runtime/src/test/java/org/eolang/PhCopyTest.java`, `eo-parser/src/test/resources/org/eolang/parser/packs/parsed-data.yaml`, `eo-runtime/src/test/java/org/eolang/PhiTest.java`, `eo-runtime/src/test/java/org/eolang/DataizedTest.java`, `eo-runtime/src/main/java/EOorg/EOeolang/EOio/EOstdout.java`, `eo-runtime/src/test/java/org/eolang/BytesOfTest.java`, `eo-maven-plugin/src/test/resources/org/eolang/maven/packs/test-object-to-java.yaml`, `eo-maven-plugin/src/test/resources/org/eolang/maven/sodgs/dots.yaml`, `eo-runtime/src/main/java/EOorg/EOeolang/EObytes$EOeq.java`, `eo-maven-plugin/src/test/resources/org/eolang/maven/sodgs/abstracts.yaml`, `eo-parser/src/test/java/org/eolang/parser/EoSyntaxTest.java`, `eo-runtime/src/main/java/EOorg/EOeolang/EObytes$EOnot.java`, `eo-runtime/src/main/java/org/eolang/BytesRaw.java`, `eo-runtime/src/main/java/EOorg/EOeolang/EObytes$EOsize.java`, `eo-maven-plugin/src/test/resources/org/eolang/maven/sodgs/arrays.yaml`, `eo-parser/src/test/resources/org/eolang/parser/packs/optimize/redundant-levels-with-siblings.yaml`, `eo-runtime/src/test/java/EOorg/EOeolang/EOtryTest.java`, `eo-parser/src/test/resources/org/eolang/parser/packs/optimize/redundant-levels.yaml`, `.codacy.yml`, `eo-runtime/src/main/java/EOorg/EOeolang/EObytes$EOor.java`, `eo-runtime/src/main/java/EOorg/EOeolang/EObytes$EOand.java`, `eo-runtime/src/main/java/EOorg/EOeolang/EObytes$EOxor.java`, `eo-maven-plugin/src/test/resources/org/eolang/maven/phi/yaml/fibonaci.yaml`, `eo-maven-plugin/src/test/resources/org/eolang/maven/binarize/twice-rust.eo`, `eo-runtime/src/main/java/EOorg/EOeolang/EOcage$EOencaged$EOencage.java`, `eo-runtime/src/main/java/org/eolang/Data.java`, `eo-runtime/src/main/rust/eo/src/eo_enum.rs`, `eo-runtime/src/test/java/org/eolang/PhPackageTest.java`, `eo-runtime/src/main/java/EOorg/EOeolang/EObytes$EOright.java`, `eo-runtime/src/main/java/EOorg/EOeolang/EOstring$EOlength.java`, `/eo-runtime/src/main/java/EOorg/EOeolang/EOcage$EOencaged$EO\317\206.java"`, `eo-runtime/src/test/java/EOorg/EOeolang/EOmallocTest.java`, `eo-runtime/src/test/java/org/eolang/UniverseDefaultTest.java`, `eo-runtime/src/main/java/EOorg/EOeolang/EOmalloc$EOof$EOallocated$EOwrite.java`, `eo-runtime/src/test/java/EOorg/EOeolang/EOio/EOstdoutTest.java`, `eo-runtime/src/test/eo/org/eolang/seq-tests.eo`, `eo-runtime/src/test/eo/org/eolang/int-tests.eo`, `eo-runtime/src/main/java/EOorg/EOeolang/EOtxt/EOregex$EOcompiled.java`, `eo-runtime/src/main/eo/org/eolang/structs/list.eo`, `eo-parser/src/test/resources/org/eolang/parser/packs/add-locators.yaml`, `eo-runtime/src/main/eo/org/eolang/structs/hash-code-of.eo`, `eo-runtime/src/test/java/org/eolang/SnippetTestCase.java`, `eo-runtime/src/main/java/EOorg/EOeolang/EObytes$EOconcat.java`, `eo-parser/src/main/java/org/eolang/parser/XeEoListener.java`, `eo-runtime/src/main/eo/org/eolang/bytes.eo`, `eo-runtime/src/main/java/EOorg/EOeolang/EOmalloc$EOof$EOallocated$EOread.java`, `eo-maven-plugin/src/test/java/org/eolang/maven/BinarizeParseTest.java`, `eo-runtime/src/test/java/EOorg/EOeolang/EOintTest.java`, `eo-runtime/src/test/java/org/eolang/PhWithTest.java`, `eo-runtime/src/main/java/EOorg/EOeolang/EOstring$EOslice.java`, `eo-runtime/src/test/eo/org/eolang/runtime-tests.eo`, `eo-runtime/src/test/eo/org/eolang/while-tests.eo`, `eo-runtime/src/main/java/EOorg/EOeolang/EObytes$EOslice.java`, `eo-runtime/src/main/java/EOorg/EOeolang/EOint$EOgt.java`, `eo-runtime/src/main/java/EOorg/EOeolang/EOint$EOtimes.java`, `eo-runtime/src/test/eo/org/eolang/cage-tests.eo`, `eo-runtime/src/main/java/EOorg/EOeolang/EOfloat$EOtimes.java`, `eo-maven-plugin/src/test/resources/org/eolang/maven/packs/data-as-bytes.yaml`, `eo-runtime/src/main/java/EOorg/EOeolang/EOfloat$EOdiv.java`, `eo-maven-plugin/src/test/resources/org/eolang/maven/phi/yaml/iterates-over-counter.yaml`, `eo-runtime/src/main/java/EOorg/EOeolang/EOtxt/EOsscanf.java`, `eo-runtime/src/test/eo/org/eolang/txt/text-tests.eo`, `eo-parser/src/test/resources/org/eolang/parser/packs/syntax/tuples.yaml`, `eo-runtime/src/main/java/EOorg/EOeolang/EOfloat$EOplus.java`, `eo-runtime/src/test/eo/org/eolang/structs/hash-code-of-tests.eo`, `eo-parser/src/main/java/org/eolang/parser/StUnhex.java`, `eo-parser/src/test/resources/org/eolang/parser/packs/explicit-data.yaml`, `eo-runtime/src/main/java/EOorg/EOeolang/EOtxt/EOsprintf.java`, `eo-parser/src/test/java/org/eolang/parser/StUnhexTest.java`, `eo-runtime/src/main/eo/org/eolang/txt/regex.eo`, `eo-runtime/src/main/eo/org/eolang/positive-infinity.eo`, `eo-runtime/src/main/eo/org/eolang/negative-infinity.eo`, `eo-runtime/src/main/eo/org/eolang/float.eo`, `eo-parser/src/test/resources/org/eolang/parser/packs/optimize/redundant-levels-with-arrays.yaml`, `eo-runtime/src/main/java/org/eolang/Dataized.java`, `eo-parser/src/main/resources/org/eolang/parser/explicit-data.xsl`, `eo-runtime/src/main/java/EOorg/EOeolang/EOtxt/EOregex$EOpattern$EOmatch$EOmatched_from_index.java`, `eo-parser/src/test/resources/org/eolang/parser/packs/all-data-types.yaml`, `eo-runtime/src/test/java/EOorg/EOeolang/EOcageTest.java`, `eo-runtime/src/test/java/org/eolang/PhDefaultTest.java`, `eo-runtime/src/test/eo/org/eolang/bytes-tests.eo`, `eo-runtime/src/main/eo/org/eolang/txt/text.eo`, `eo-runtime/src/test/java/EOorg/EOeolang/EOio/EOstdinTest.java`, `eo-runtime/src/test/eo/org/eolang/rust-tests.eo`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
@rultor merge

**Comment by maxonfjvipon** [comment]
@yegor256 please try to merge one more time

**Comment by maxonfjvipon** [comment]
@yegor256 please try to merge one more time

**Comment by yegor256** [comment]
@maxonfjvipon something is wrong with one test?

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@maxonfjvipon there is definitely something wrong with one test

**Comment by maxonfjvipon** [comment]
@yegor256 let's try again, now we at least should see log on failed snippet test

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by maxonfjvipon** [comment]
@rultor status

**Comment by yegor256** [comment]
@maxonfjvipon let's make it simple this time

**Comment by 0crat** [comment]
@maxonfjvipon Thanks for the contribution! You've earned +5 points for this: +20 as a basis; +5 for 3226 hits-of-code; -7 for too many hits-of-code (3226 >= 100); -15 for way too many hits-of-code (3226 >= 400); -15 for the lack of code review; -20 for 21 comments of reviewers; +37 to give you at least something. Please, [keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) them coming. Your running balance is [+118](https://www.eolang.org/zerocracy/objectionary-vitals.html).

**Pull request merged**
