### PR TITLE
feat(#1723): Snippet Test. Make them work.

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
1. I have to copy [bytes-as-array.eo](https://github.com/objectionary/eo/compare/master...volodya-lombrozo:1723_snippet_test?expand=1#diff-483d113fb5f238707beec9b38a602412804717b90c759f05a0e2c71bb66d789b) and [list.eo](https://github.com/objectionary/eo/compare/master...volodya-lombrozo:1723_snippet_test?expand=1#diff-e83f984639d39c9717118e3a525847ef92f12e534e7bbeb537b8a2abf0aa6f7c) eo objects since they are required for testing. You can read about the problem in that issue https://github.com/objectionary/eo/issues/1724
2. I had to remove any usage of `txt` package in `eo` programs and checks, since `txt` package out of `eo-runtime` (the same problem as `collections`).

**Important:** It's not the final PR related to the issue.

#1723

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
@Graur Could you have a look, please?

**Comment by Graur** [comment]
@volodya-lombrozo Can you clarify what will be the next step? I don't see any puzzles here

**Comment by volodya-lombrozo** [comment]
@Graur I've added several puzzles. Could you take a look, again, please?

**Review by Graur — APPROVED** [review]
@volodya-lombrozo I get the idea now, thanks!

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you merge that PR, please?

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
