### PR TITLE
Making sonar works 'on pull_request' by using SonarSource/sonarcloud-github-action

### PR DESCRIPTION
**Pull request by c71n93**
Related to #2251

---

## PR-Codex overview
This PR updates the SonarCloud workflow to include licensing information and specific paths to ignore during analysis.

### Detailed summary
- Added MIT License header
- Specified paths to ignore during analysis
- Updated workflow to run on specific branches and events
- Added conditions for workflow execution based on repository and event type

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by yegor256** [comment]
@c71n93 we have `SONAR_TOKEN` secret set for the entire organization

**Comment by c71n93** [comment]
@yegor256 According to https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions: "With the exception of `GITHUB_TOKEN`, secrets are not passed to the runner when a workflow is triggered from a forked repository."

So unfortunately we can't use secrets in workflows on PR from forks and should ignore sonarcloud worflow in this cases.

**Comment by yegor256** [comment]
@c71n93 so, what now? We merge this one?

**Comment by c71n93** [comment]
@yegor256 we can close this one. It looks like it is impossible to run sonar CI on PR from forks. Also we [can't use](https://community.sonarsource.com/t/github-action-keeps-failing-on-sonarcloud-scan-cause-of-maven-project/68692) this [sonarcloud github action](https://github.com/SonarSource/sonarcloud-github-action) for maven project.

**Pull request closed without merging**
