### PR TITLE
fix(#1574) Update `tojos` dependency

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
I've updated `tojos` dependency version. In the new version (`0.17.0`) we solved all concurrency problems related to `MonoTojo`.
Closes: #1607 
Closes: #1574

### CODE REVIEW

**Comment by yegor256** [comment]
@rultor merge

**Comment by volodya-lombrozo** [comment]
Blocked by https://github.com/objectionary/eo/issues/1614

**Comment by volodya-lombrozo** [comment]
@yegor256 Can you merge it again, please?

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor release, tag is `0.28.15`

**Pull request merged**
