### PR TITLE
(#632) - Add Bytes

### PR DESCRIPTION
**Pull request by andreoss**
Per #632

- Add a new `Data` type `Bytes`
- Move to-be implementations of `EOBytes` methods to `Bytes`
- Leave `left` & `right` unimplemented for further discussion

### CODE REVIEW

**Comment by yegor256** [comment]
@andreoss nice class, but I don't see how it's used by any of our existing classes. Did you forget to add this?

**Comment by andreoss** [comment]
@yegor256 The implemementation is incomplete, we are missing `>>` and `<<` operators. 
There is a PDD for that, after it's done we will be able to replace code currently implementing this logic with `Bytes`

**Comment by yegor256** [comment]
@andreoss do we need these classes to be `public`?

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
