### PR TITLE
remove math from eo repo

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Should merge this PR after [this one](https://github.com/objectionary/home/pull/39).
After merging this PR we'll be able to version eo up in eo-math and continue work in eo-math repo

### CODE REVIEW

**Comment by yegor256** [comment]
@maxonfjvipon it seems you didn't delete everything

**Comment by maxonfjvipon** [comment]
@yegor256 It seems to me, I deleted everything (or I really didn't?). Can it be some kind of conflict? Because errors are in classes that exist now in two repos: eo-runtime and eo-math (EOnumber, EOangle, EOrandom)
image

**Comment by maxonfjvipon** [comment]
@yegor256 [release `0.1.4`](https://github.com/objectionary/home/pull/40) is ready to merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@maxonfjvipon looks good now, thanks!

**Pull request merged**
