### PR TITLE
feat(#2412): disable GPT code review check

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Closes: #2412

---

## PR-Codex overview
This PR focuses on disabling a step in the GitHub Actions workflow. 

### Detailed summary
- Disabled the `npm install code-review-gpt` step.
- Disabled the `npx code-review-gpt review --ci=github` step.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@yegor256 please merge this one since this check does not work anyway

**Comment by yegor256** [comment]
@maxonfjvipon maybe let's disable it instead of deleting? Maybe later it will start working, we will be able to try again

**Comment by maxonfjvipon** [comment]
@yegor256 please have a look one more time

**Comment by yegor256** [comment]
@rultor merge

**Comment by maxonfjvipon** [comment]
@yegor256 please try to merge one more tome

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
