### PR TITLE
#1174 Test for offline hash parameter in PullMojo

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
I've added the test for `PullMojo` and `offlineHash`. 
After implementation I'll remove the `@Disabled` annotation.

Original issue: #1174. It's not a final PR.

### CODE REVIEW

**Comment by yegor256** [comment]
@volodya-lombrozo set it to "draft" if you don't want it to be reviewed and merged

**Comment by volodya-lombrozo** [comment]
> @volodya-lombrozo set it to "draft" if you don't want it to be reviewed and merged

Actually I want to be reviewed and merged. @yegor256 Can you merge, please, if you don't have any objections?

**Comment by volodya-lombrozo** [comment]
@mximp Can you take a look, please?

**Comment by yegor256** [comment]
@volodya-lombrozo it's not a good idea to add a disabled test to master branch without any puzzle (or any comment attached to it). We can easily forget about it and it will be hard to remember later what it was about.

**Comment by volodya-lombrozo** [comment]
@yegor256  I've added one more unit test and dummy implementation.  Also I've added puzzle for future `ChPattern` implementation.

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
