### PR TITLE
Move `ScopedTojos` class out of `SafeMojo`

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
Since we have a separate package for `tojos`, I believe it would be nice to move `ScopedTojos` out of `SafeMojo` in order to simplify `SafeMojo`.

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
@Graur Could you have a look, please?

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you merge that changes, please?

**Comment by volodya-lombrozo** [comment]
@yegor256 Reminder

**Comment by volodya-lombrozo** [comment]
@yegor256 Reminder

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
