### PR TITLE
fix(#3057): right design of `cage`

### PR DESCRIPTION
**Pull request by maxonfjvipon**
What's done:
1. Design of `cage` is changed. Now it's similar to `malloc` and `memory`
2. `Heaps` and `Cages` are not thread local because they should be shared by all threads

Closes: #3057

---

## PR-Codex overview
This PR focuses on refactoring the `Heaps` class to use a single static instance. 

### Detailed summary
- Changed `ThreadLocal` to a static instance in `Heaps` class.
- Updated references to `Heaps.INSTANCE` in multiple files.
- Added new classes `EOcage$EOφ`, `EOcage$EOencaged$EOφ`, and `EOcage$EOencaged$EOencage`.
- Updated exclusion paths in `.codacy.yml`.
- Updated test cases in `CagesTest.java`.

> The following files were skipped due to too many changes: `eo-runtime/src/test/java/EOorg/EOeolang/CagesTest.java`, `eo-runtime/src/test/java/EOorg/EOeolang/EOcageTest.java`, `eo-runtime/src/test/eo/org/eolang/cage-tests.eo`, `eo-runtime/src/main/java/EOorg/EOeolang/Cages.java`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by yegor256** [comment]
@maxonfjvipon it seems to me, we don't need `free` here, since there is nothing actually to "free" -- we don't acquire any resources.

**Comment by maxonfjvipon** [comment]
@yegor256 but object are stored somewhere. Now it's a hash map. It may be something else, but it's still a storage. And I think we need to be able to clean it

**Comment by maxonfjvipon** [comment]
@yegor256 please check, I removed `free` from `cage`

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
