### PR TITLE
(#1185) - Add `Bytes.toPhi`, remove extra `Data.ToPhi`

### PR DESCRIPTION
**Pull request by andreoss**
Per #1185

### CODE REVIEW

**Comment by yegor256** [comment]
@rultor merge

**Comment by andreoss** [comment]
@yegor256 `RamTest` is still flaky, I disabled it in this PR. 
Will be fixed in #1069

**Comment by andreoss** [comment]
@yegor256 It's ready to be merged

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
