### PR TITLE
set failOnWarning to true

### PR DESCRIPTION
**Pull request by Graur**
Closes: #1587

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
@Graur if you will set the value to true, the build will fail

**Comment by Graur** [comment]
@volodya-lombrozo Looks like this build didn't fail

**Comment by volodya-lombrozo** [comment]
@volodya-lombrozo Let's try :)

**Comment by Graur** [comment]
@yegor256 Looks like we can try to merge this pull request

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@Graur try `mvn clean deploy -Psonatype`

**Comment by volodya-lombrozo** [comment]
@Graur You can also clean local cache `rm -rf ~/.m2/repository/org/eolang`

**Comment by Graur** [comment]
@volodya-lombrozo @yegor256 I changed this flag in all related projects (like `eo-strings`, `eo-collections`, etc). I believe we can merge this change and close #1587 ticket now

**Comment by volodya-lombrozo** [comment]
@Graur Looks good to me, thanks.

**Comment by Graur** [comment]
@yegor256 Please, have a look

**Comment by yegor256** [comment]
@rultor merge

**Comment by Graur** [comment]
@yegor256 Please, let's try again

**Comment by yegor256** [comment]
@rultor merge

**Comment by volodya-lombrozo** [comment]
@Graur @yegor256 I have fix for that, but GitHub is [lying down](https://www.githubstatus.com) now.  When it will be fix, I hope we will be able to fix Rultor

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you merge it again, please?

**Comment by Graur** [comment]
@yegor256 Can we try to merge one more time, please?

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
