### PR TITLE
Hotfix for failed cyclic dependency

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
Remove cyclic dependency and downgrade `maven-compiler-plugin` version.
Hotfix for: https://github.com/objectionary/eo/pull/1592#issuecomment-1359202227

### CODE REVIEW

**Comment by yegor256** [comment]
@rultor merge

**Comment by volodya-lombrozo** [comment]
@yegor256 the problem with compilation for windows has to be solved [here](https://github.com/objectionary/eo/pull/1592)

**Comment by yegor256** [comment]
@rultor stop

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
