### PR TITLE
#1111 remove data puzzle

### PR DESCRIPTION
**Pull request by OlesiaSub**
#1111 
@yegor256 please check

### CODE REVIEW

**Comment by yegor256** [comment]
@andreoss please, take a look

**Comment by OlesiaSub** [comment]
@andreoss please check

**Comment by OlesiaSub** [comment]
@yegor256 this pr still hasn't been checked

**Comment by OlesiaSub** [comment]
@yegor256 ping :')

**Review by andreoss — APPROVED** [review]
@OlesiaSub @yegor256 I apologize for the delay

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
