### PR TITLE
added info about separated test run in eo-runtime

### PR DESCRIPTION
**Pull request by Graur**
Closes: #954

### CODE REVIEW

**Comment by Graur** [comment]
@maxonfjvipon @yegor256 Please take a look. And please let me know if this description is unclear.

**Comment by maxonfjvipon** [comment]
@Graur pretty much clear as for me

**Comment by yegor256** [comment]
@Graur good for me

**Comment by Graur** [comment]
@yegor256 Please merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
