### PR TITLE
2973 enable rust tests

### LINKED ISSUE #2973: rust-tests.eo:29-31: Enable rust tests. They were fully...
The puzzle `2931-ad3f15a5` from #2931 has to be resolved: 

https://github.com/objectionary/eo/blob/446d62f268ac3224a2927fccfba20a7f444576ce/eo-runtime/src/test/eo/org/eolang/rust-tests.eo#L29-L31

The puzzle was created by rultor on 18-Mar-24. 

Estimate: 60 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

### PR DESCRIPTION
**Pull request by levBagryansky**
Closes #2973

---

## PR-Codex overview
This PR enables Rust tests by adding test cases for different scenarios like returning positive/negative integers and doubles, working with byte arrays, and error handling.

### Detailed summary
- Added test cases for returning positive/negative integers and doubles in Rust
- Included tests for working with byte arrays and strings
- Added error handling scenarios in Rust tests

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by levBagryansky** [comment]
@maxonfjvipon please take a look

**Review by maxonfjvipon — APPROVED** [review]
@levBagryansky LGTM! Many thanks

**Comment by levBagryansky** [comment]
@yegor256 please take a look

**Comment by yegor256** [comment]
@rultor merge

**Comment by levBagryansky** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
@rultor merge

**Comment by levBagryansky** [comment]
@yegor256 please check

**Pull request merged**
