### PR TITLE
fix objectionary field in AssembleMojo

### PR DESCRIPTION
**Pull request by Graur**
#726

### CODE REVIEW

**Comment by Graur** [comment]
@yegor256 Could you please give an idea how to design the test which will check validation of github link with the given hash in AssembleMojo or PullMojo?

**Comment by yegor256** [comment]
@Graur maybe you can make a "fake" `Objectionary`, which will remember which URLs where requested through it and then compare them with the expected ones. Maybe even some Mockito framework would be helpful to make a mock of `Objectionary`.

**Comment by yegor256** [comment]
@Graur ready to merge or you still want to add the test?

**Comment by Graur** [comment]
@yegor256 I want to add the test

**Comment by Graur** [comment]
@yegor256 I change my mind. Right now I can't write such test. I need to think a little how to refactor the related code

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
