### PR TITLE
fix(#2943): added many tests for `phi` and `unphi` + allow vmethod after formation in EO grammar

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Ref: #2943

---

## PR-Codex overview
This PR updates test cases, listener methods, and grammar rules related to EO language parsing.

### Detailed summary
- Added test cases for bool objects in Maven plugin
- Modified methods in `XeEoListener.java`
- Updated grammar rules in `Eo.g4` for formation naming and vmethod definition

> The following files were skipped due to too many changes: `eo-maven-plugin/src/test/resources/org/eolang/maven/unphi/bool-tests.yaml`, `eo-parser/src/test/resources/org/eolang/parser/packs/syntax/bool-tests-straight.yaml`, `eo-maven-plugin/src/test/resources/org/eolang/maven/phi/bool-tests.yaml`, `eo-maven-plugin/src/test/resources/org/eolang/maven/print/xmir/bool-tests.xmir`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@yegor256 please have a look

**Comment by yegor256** [comment]
@rultor merge

**Comment by maxonfjvipon** [comment]
@yegor256 something went wrong: `tlmgr: Local TeX Live (2023) is older than remote repository (2024).`

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@maxonfjvipon my mistake, will work now (hopefully)

**Comment by maxonfjvipon** [comment]
@yegor256 again: `-bash: line 1: tlmgr: command not found`

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
