### PR TITLE
#998 cached tojos

### PR DESCRIPTION
**Pull request by OlesiaSub**
#998 
I also had to modify AssembleMojo, as it used `placed` and `placedFormat` properties

### CODE REVIEW

**Comment by OlesiaSub** [comment]
@yegor256 @mximp done, please check
but there are test failures connected to #1069

**Review by mximp — APPROVED** [review]

**Comment by mximp** [comment]
@OlesiaSub how is that related? Where do you see `Execution(CONCURRENT)` is used?

**Comment by OlesiaSub** [comment]
@mximp I just saw the tests output is almost the same as the example in that issue. So, apparently, it's not my mistake but there is a bug in master. I might be wrong though, but I think my code does not affect those tests.

**Comment by mximp** [comment]
@yegor256 please merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by mximp** [comment]
@OlesiaSub Please comment out failing RamTests to make the build successful.

**Comment by OlesiaSub** [comment]
@mximp done

**Comment by mximp** [comment]
@yegor256 please merge

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
