### PR TITLE
feat(#3743): Add Error Location for Custom Errors

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
In this PR I added location and helpful information to custom parsing errors.

Was:
```
Object binding can't be negative
```

Become:
```
[4:6] error: 'Object binding can't be negative'
    42:-1
      ^^^
```

Closes: #3743.

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
@maxonfjvipon Could you review these changes, please?

**Review by maxonfjvipon — APPROVED** [review]

**Comment by volodya-lombrozo** [comment]
@yegor256 Can you take a look, please?

**Comment by 0crat** [comment]
@volodya-lombrozo Thanks for the contribution! You've earned +6 points for this: +4 as a basis; +6 for the 128 hits-of-code that you wrote; -4 for very few (2) comments. Please, [keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) them coming. Your running balance is [-4](https://www.eolang.org/zerocracy/objectionary-vitals.html).

**Comment by 0crat** [comment]
@maxonfjvipon Thanks for the review! You've earned +4 points for this: +4 as a basis; -10 for very few (2) comments; +10 to give you at least something.  Your running balance is [+24](https://www.eolang.org/zerocracy/objectionary-vitals.html).

**Pull request merged**
