### PR TITLE
2157 Vertices

### PR DESCRIPTION
**Pull request by levBagryansky**
Closes: #2157

---

## PR-Codex overview
This PR improves the performance of the EO language by replacing ThreadLocal with a ConcurrentHashMap to allow parallelism. 

### Detailed summary
- Replaced ThreadLocal with ConcurrentHashMap to allow parallelism.
- Updated PhDefault and Data classes to use the new ConcurrentHashMap.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by levBagryansky** [comment]
@volodya-lombrozo please take a look

**Review by volodya-lombrozo — CHANGES_REQUESTED** [review]
@levBagryansky Left several comments, please, take a look.

**Comment by volodya-lombrozo** [comment]
@yegor256 reminder

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
