### PR TITLE
#931 dataization level fix

### LINKED ISSUE #931: Make dataization logging concise
Currently `Dataized.take()` uses `φTerm()` for logging Φ's:
```
 if (Dataized.LOGGER.isLoggable(Level.FINE)) {
            Dataized.LOGGER.log(
                Level.FINE,
                String.format(
                    "%s\uD835\uDD3B( <%s>%s ) ➜ %s",
                    String.join("", Collections.nCopies(before, "·")),
                    this.phi.location(),
                    this.phi.φTerm().replaceAll("[\n\t]", ""),
                    new Data.Value<>(data).φTerm()
                )
            );
        }
```
It makes impossible to enable dataization logging.
Let's change this to using `Φ.toString()` which is much more compact.

Also `Dataized.LEVEL` which is logged should be limited to 5 by default. 
It also must be possible to configure this value via configuration property:
```
-Ddataized.log.until=3
```

### PR DESCRIPTION
**Pull request by mximp**
#931

### CODE REVIEW

**Comment by mximp** [comment]
@yegor256 please merge

**Comment by mximp** [comment]
@yegor256 
This fixes the issue covered by existing test: `org.eolang.DataizedTest.logsCorrectly`:
```
Error:  Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.002 s <<< FAILURE! - in org.eolang.DataizedTest
Error:  org.eolang.DataizedTest.logsCorrectly  Time elapsed: 0.001 s  <<< ERROR!
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
```
This failure appears in quite a few builds in current master, e.g.:
https://github.com/objectionary/eo/runs/7665532066?check_suite_focus=true#step:5:2657
https://github.com/objectionary/eo/runs/7720492739?check_suite_focus=true#step:5:3021

Also there is a ticket for the problem: #985

**Comment by mximp** [comment]
@yegor256 the test is added. Please check and merge.

**Comment by mximp** [comment]
@yegor256 can we try to merge it? The build failure seems sporadical.

**Comment by yegor256** [comment]
@mximp let's use `assertThrows` instead

**Comment by mximp** [comment]
@yegor256 Good idea - implemented.
Pls check and merge.

**Comment by yegor256** [comment]
@rultor merge

**Comment by mximp** [comment]
The following error from merge log:
```
[INFO] --- qulice-maven-plugin:0.21.1:check (jcabi-qulice-check) @ eo-runtime ---
[INFO] Calling org.apache.maven.plugins:maven-enforcer-plugin:3.0.0:enforce...
[INFO] This is not an SVN project
[WARNING] Used undeclared dependencies found:
        org.junit.jupiter:junit-jupiter-api:jar:5.6.2:test
[INFO] You can suppress this message by <exclude>dependencies:...</exclude> in pom.xml, where <...> is what the dependency name starts with (not a regular expression!)
[INFO] Read our quality policy: http://www.qulice.com/quality.html
```

**Comment by mximp** [comment]
@yegor256 is this something on Rultor's side? Local check doesn't show any qulice errors. Besides qulice is disabled for `eo-runtime`.

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@mximp thanks!

**Pull request merged**
