### PR TITLE
feat(#3251): `tee-input` + `input-length` objects introduced

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Ref: #3251

---

## PR-Codex overview
This PR adds licensing information and architectural details to multiple EO files. It also introduces new objects like `dead-input` and `dead-output`.

### Detailed summary
- Added licensing information to various files
- Introduced `dead-input` and `dead-output` objects
- Included architectural details and package information

> The following files were skipped due to too many changes: `eo-runtime/src/test/eo/org/eolang/io/tee-input-tests.eo`, `eo-runtime/src/main/eo/org/eolang/io/tee-input.eo`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Review by yegor256 — CHANGES_REQUESTED** [review]
@maxonfjvipon why not `tee` and `length-of`?

**Comment by maxonfjvipon** [comment]
@yegor256 EO now have concept of inputs and outputs. So we have `bytes-as-input`, `dead-input`, and... `tee-input`. The only way to understand that they inputs - by their name. The `length-of` is quite wide broad wide broad name meanwhile it can work only with inputs. Thats why it's `input-length`.

**Review by yegor256 — APPROVED** [review]

**Comment by yegor256** [comment]
@rultor merge

**Comment by maxonfjvipon** [comment]
@yegor256 the process was killed for some reason

**Comment by yegor256** [comment]
@rultor merge

**Comment by maxonfjvipon** [comment]
@yegor256 the same strory(

**Comment by yegor256** [comment]
@maxonfjvipon again, the machine is too small for our build, I believe :(

**Comment by 0crat** [comment]
@yegor256 Thank you for your code review! Your contribution has earned you 23 points: 25 points as a base, plus 8 points for reviewing 409 hits-of-code. However, we deducted 10 points due to the low number of comments (only 1). Remember, thorough feedback is crucial for our team's growth. Your current balance stands at [+163](https://www.eolang.org/zerocracy/objectionary-vitals.html). Keep up the good work, and don't hesitate to provide more detailed comments in future reviews!

**Comment by 0crat** [comment]
@maxonfjvipon Great job on your contribution! 🎉 You've earned +18 points (+25 base, -7 for exceeding 200 hits-of-code). We appreciate your effort and encourage you to [keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) the quality contributions coming. Your current balance stands at [+216](https://www.eolang.org/zerocracy/objectionary-vitals.html). Keep up the excellent work!

**Pull request merged**
