### PR TITLE
2648 refactor bin mojo

### LINKED ISSUE #2648: BinarizeMojo.java:52-54: Make it more generic. Perhaps by...
The puzzle `2118-1bbacef7` from #2118 has to be resolved: 

https://github.com/objectionary/eo/blob/f384b1c98c9dc66e18d160cdb4216012a6047bc2/eo-maven-plugin/src/main/java/org/eolang/maven/BinarizeMojo.java#L52-L54

The puzzle was created by @rultor on 29-Nov-23. 

Estimate: 90 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

### PR DESCRIPTION
**Pull request by levBagryansky**
Closes #2648 

## PR-Codex overview
This PR focuses on refactoring and optimizing the `BinarizeParseMojo` class in the `eo-maven-plugin`. 

### Detailed summary
- Removed unused imports and parameters
- Extracted logic into a separate `BinarizeParse` class
- Renamed `BinarizeParseMojoTest` to `BinarizeParseTest`
- Updated references to `BinarizeParseMojo` to `BinarizeParse`
- Added `Buildable` interface for FFI nodes that can be built

> The following files were skipped due to too many changes: `eo-maven-plugin/src/main/java/org/eolang/maven/BinarizeMojo.java`, `eo-maven-plugin/src/main/java/org/eolang/maven/rust/RustNode.java`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by levBagryansky** [comment]
@maxonfjvipon please take a look

**Review by maxonfjvipon — APPROVED** [review]
@levBagryansky LGTM! Thanks

**Comment by maxonfjvipon** [comment]
@levBagryansky please add issue link to the description of the PR

**Comment by levBagryansky** [comment]
@yegor256 please take a look

**Pull request merged**
