### PR TITLE
feat(#3603): added syntax sugar for phi applications

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Closes: #3603
Closes: #3574

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Review by yegor256 — APPROVED** [review]
@maxonfjvipon LGTM, thanks!

**Comment by 0crat** [comment]
@maxonfjvipon Thanks for your contribution! Here's a breakdown of your earned points: +4 base, -8 for 577 hits-of-code (≥200), -4 for only 1 comment, and +12 adjustment. Total: +4 points. While the code volume was high, we encourage more [concise contributions](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) and active code reviews in the future. Your balance is now [+32](https://www.eolang.org/zerocracy/objectionary-vitals.html). Keep up the good work! 💻

**Comment by 0crat** [comment]
@yegor256 Hey there! 👋 Great job on the review! You've snagged +4 points for this one. Here's the breakdown: +4 base points, +5 for tackling those 577 [hits-of-code](https://www.yegor256.com/2014/11/14/hits-of-code.html) (impressive!), but we had to deduct 10 because there was only 1 comment. Don't worry, we made sure you got at least 4 points! Your current balance sits at [-108](https://www.eolang.org/zerocracy/objectionary-vitals.html). Keep up the great work, and remember, more comments can boost your points next time! 💪

**Pull request merged**
