### PR TITLE
2292 dataize

### LINKED ISSUE #2292: eo_env.rs:78-80: Implement "dataize" method. It must call...
The puzzle `2237-4d097292` from #2237 has to be resolved: 

https://github.com/objectionary/eo/blob/494408a320a76b5bbfa1318815365b03020bdfca/eo-runtime/src/main/rust/eo_env/src/eo_env.rs#L78-L80

The puzzle was created by @rultor on 21-Jul-23. 

Estimate: 60 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

### PR DESCRIPTION
**Pull request by levBagryansky**
Closes #2292, #2400

---

### Focus of this PR:
This PR focuses on adding a new feature to the `EOEnv` struct in the Rust code. It introduces the `dataize` method, which calls a Java dataizing method and returns a byte array as a result of dataization.

### Detailed summary:
- Added `dataize` method to the `EOEnv` struct in Rust code.
- The `dataize` method calls the Java `dataize` method and retrieves a byte array.
- The retrieved byte array is returned as a result of dataization.
- Updated the `foo` function in Rust code to use the `dataize` method.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by levBagryansky** [comment]
@Graur could you please review these changes?

**Comment by levBagryansky** [comment]
@Graur please review

**Comment by levBagryansky** [comment]
@yegor256 please take a look

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
