### PR TITLE
maven compiler plugin update version ignored by renovate bot

### PR DESCRIPTION
**Pull request by Graur**
#1585

What is done:

- changed maven compiler plugin version
- added ignoring rule for this dependency to renovate bot

### CODE REVIEW

**Comment by Graur** [comment]
@yegor256 @volodya-lombrozo please ,take a look

**Review by volodya-lombrozo — APPROVED** [review]
@Graur Looks good to me. The only question - what is the reason of the fail? Is it some bug in  the  new version?

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by volodya-lombrozo** [comment]
@yegor256 Can you try to merge again, please?

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
