### PR TITLE
feat(#3251): Added `regex` object to `eo-runtime`

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Ref: #3251

---

## PR-Codex overview
This PR updates logging levels, refactors regex patterns, and adds licensing info to Java files.

### Detailed summary
- Updated logging level from `info` to `debug`
- Refactored regex patterns to handle more free attributes
- Added MIT licensing info to Java files

> The following files were skipped due to too many changes: `eo-runtime/src/main/eo/org/eolang/txt/regex.eo`, `eo-runtime/src/test/eo/org/eolang/txt/regex-tests.eo`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Review by yegor256 — APPROVED** [review]
LGTM

**Comment by 0crat** [comment]
@maxonfjvipon Thanks for the contribution! You've earned +5 points for this: +20 as a basis; +5 for 468 hits-of-code; -7 for too many hits-of-code (468 >= 100); -15 for way too many hits-of-code (468 >= 400); -5 for 1 comments of reviewers; +7 to give you at least something. Please, [keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) them coming. Your running balance is [+113](https://www.eolang.org/zerocracy/objectionary.html).

**Comment by 0crat** [comment]
@yegor256 Thanks for the review! You've earned +70 points for this: +25 as a basis; +40 for 468 hits-of-code; +5 for 1 comments.  Your running balance is [+127](https://www.eolang.org/zerocracy/objectionary.html).

**Pull request merged**
