### PR TITLE
feat(#2148): Test Refactoring in eo-maven-plugin

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
1. Remove `SkipTest` (move all test cases into corresponding test classes)
2. Move `DummyCentral` under `FakeMaven` class.

Related to #2148 

---

## PR-Codex overview
This PR removes three Java test files and adds a new test method to two other test files. It also introduces a new class, `DummyCentral`, used to emulate the Maven Central repository. 

### Detailed summary
- Removed `SkipTest.java`, `DummyCentral.java`, and `PlaceMojoTest.java` from `eo-maven-plugin/src/test/java/org/eolang/maven/`
- Added new test method `skipsCopyMojo` to `CopyMojoTest.java`
- Added new test method `skipsPullMojo` to `PullMojoTest.java`
- Introduced new class `DummyCentral` to emulate the Maven Central repository.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
@Graur Could you have a look, please?

**Review by Graur — APPROVED** [review]
@volodya-lombrozo Good one
@yegor256 Please have a look

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you merge that changes, please?

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
