### PR TITLE
feat(#1990): Rename XMIR_2 to OPTIMIZED

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
Rename `XMIR_2` to `OPTIMIZED`.

Closes: #1990

---

## PR-Codex overview
This PR changes the naming of a file in the eo-maven-plugin and updates the corresponding references to it. 

### Detailed summary
- Renames `xmir2` to `optimized` in `ForeignTojo` and related classes
- Updates all references to `xmir2` to `optimized` in `OptimizeMojo`, `ProbeMojo`, `DiscoverMojo`, `BinarizeParseMojo`, `SodgMojo`, `TranspileMojo`, `TranspiledTojos`, and `ForeignTojos`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
@mximp Could you have a look, please?

**Review by mximp — APPROVED** [review]

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you merge that changes, please?

**Comment by volodya-lombrozo** [comment]
@yegor256 Reminder

**Comment by volodya-lombrozo** [comment]
@yegor256 reminder

**Pull request merged**
