### PR TITLE
#1570 fix ampersand (home locator)

### LINKED ISSUE #1570: `.&` expression is not handled properly
```
[] > app
  [] > @
    [] > @
      &.&.a > @
  1 > a 
```
Leads to a execution error:
`Caused by: org.eolang.ExUnset: Can't get(), attribute "&" is absent among other ...`

Expected: `&.&.a` correctly refers to `app.a`.

### PR DESCRIPTION
**Pull request by mximp**
closes #1570

### CODE REVIEW

**Comment by mximp** [comment]
@yegor256 please check and merge

**Comment by mximp** [comment]
> @yegor256 please check and merge

please hold on, missed commits

**Comment by mximp** [comment]
@yegor256 please review

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
