### PR TITLE
fix(#1426): transpile with cache

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Ref: #1426 

---

## PR-Codex overview
This PR primarily focuses on restructuring the `eo-maven-plugin` to reorganize the package structure from `org.eolang.maven.fp` to `org.eolang.maven.footprint`, alongside various deletions of unused files and tests.

### Detailed summary
- Deleted multiple files from `eo-maven-plugin/src/main/java/org/eolang/maven/fp` and `eo-maven-plugin/src/test/java/org/eolang/maven/fp`.
- Renamed package from `org.eolang.maven.fp` to `org.eolang.maven.footprint` in several classes.
- Updated imports to reflect the new package structure.
- Modified the `Footprint` interface to extend `BiFunc<Path, Path, Path>`.
- Changed method signatures in various classes to accommodate the new structure.
- Removed references to previously deleted classes in tests and other files.
- Replaced `new FtDefault(temp)` with `temp` in several test cases.
- Updated logging messages to use formatted strings for better readability.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Review by yegor256 — APPROVED** [review]
LGTM

**Comment by 0crat** [comment]
@maxonfjvipon Hey there, great job on your contribution! 👍 You've earned +4 points, which is our base reward. We had to make some adjustments though: -8 for exceeding 200 hits-of-code and -16 for going over 800 (you hit 2235!). Also, -4 because we only saw 1 comment. To keep you motivated, we added +28 to ensure you get something. Remember, [quality over quantity](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) is key! Keep the contributions coming, but try to keep them more focused next time. Your current balance is [+12](https://www.eolang.org/zerocracy/objectionary-vitals.html). Let's aim for more reviews and comments on your next submission!

**Comment by 0crat** [comment]
@yegor256 Great job on the review! 🎉 You've earned +10 points: +4 base, +16 for reviewing 2235 hits-of-code, with a -10 adjustment for limited comments. Keep up the good work and consider adding more insights next time. Your current balance is [-90](https://www.eolang.org/zerocracy/objectionary-vitals.html). Keep pushing forward!

**Pull request merged**
