### PR TITLE
#1206 LatexMojo added to translate .xmir files to phi-calc formulas in form of .tex files

### PR DESCRIPTION
**Pull request by potatmen**

### CODE REVIEW

**Comment by potatmen** [comment]
@Graur here I used the new branch called `1206` + `Home.exists()`. About `Home.rel()` I will duplicate the comment. 
I think no because in here I need to find the position of pattern from the string and then find filename by taking the filename after this pattern, therefore, I think Home.rel() will not be suitable in this case

**Review by Graur — APPROVED** [review]
@yegor256 Can you take a look, please?

**Comment by potatmen** [comment]
@yegor256 reminder

**Comment by potatmen** [comment]
@yegor256 Please merge

**Comment by yegor256** [comment]
@potatmen the implementation of this mojo is very much different from what we have in other mojos. Why? Maybe it's better to study how similar functionality is implemented there? We use `foreign` catalog over there, for example. Also, the tests are designed differently. Why?

**Comment by potatmen** [comment]
@yegor256 because I didn't try to copy the structure of existing Mojos and for now `LatexMojo` hasn't the full functionality as it's required in issue. As I understand I need to make structure of this Mojo more similar to existing, for example `GmiMojo` because it's also a standalone Mojo.

**Comment by yegor256** [comment]
@potatmen it seems that something similar has already been implemented, so I'm closing this one

**Pull request closed without merging**
