### PR TITLE
fix(#2873): changed rho with sigma

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Ref: #2873

---

## PR-Codex overview
This PR updates object references in YAML files and XSL stylesheets, changing `ρ` to `σ` for consistency and clarity.

### Detailed summary
- Updated object references in YAML files and XSL stylesheets from `ρ` to `σ`
- Improved consistency and clarity in the codebase

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@rultor status

**Comment by maxonfjvipon** [comment]
@yegor256 please try to merge one more time

**Comment by yegor256** [comment]
@rultor merge

**Comment by maxonfjvipon** [comment]
@rultor status

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
