### PR TITLE
add "and" and "or" operations for integers

### PR DESCRIPTION
**Pull request by dours**

### CODE REVIEW

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@dours thanks!

**Comment by dours** [comment]
@yegor256 could you release a new minor version please

**Comment by yegor256** [comment]
@rultor release, tag is `0.23.2`

**Comment by yegor256** [comment]
@dours you have it

**Comment by dours** [comment]
@yegor256 thank you!

**Pull request merged**
