### PR TITLE
feat(#2829): lambda as function

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Closes: #2829

What's done:
- `Atom` interface that contain `lambda` function is introduced
- All atoms in `eo-runtime` implements `Atom`
- `AtLambda` is removed

---

## PR-Codex overview
This PR focuses on making several classes final and adding interface implementation. 

### Detailed summary
- Made `Input`, `EOintTest`, `RamTest`, `EOint$EOgt`, `EObytes$EOand`, `EObytes$EOor`, `EObytes$EOxor`, `EObytes$EOnot`, `EObytes$EOas_int`, `EObytes$EOas_float`, `EObytes$EOsize`, `EOstring$EOlength`, `EOas_phi`, `EOstdin$EOφ` and `Ram` classes final.
- Added interface implementation to `EObytes$EOas_int`, `EObytes$EOas_float`, `EObytes$EOor`, `EObytes$EOand`, `EObytes$EOxor`, `EObytes$EOnot`, `EOstring$EOlength`, `EOas_phi` and `EOstdin$EOφ` classes.

> The following files were skipped due to too many changes: `eo-runtime/src/main/java/EOorg/EOeolang/EObytes$EOxor.java`, `eo-runtime/src/main/java/EOorg/EOeolang/EOint$EOtimes.java`, `eo-runtime/src/main/java/EOorg/EOeolang/EOfloat$EOgt.java`, `eo-runtime/src/main/java/EOorg/EOeolang/EOfloat$EOdiv.java`, `eo-runtime/src/main/java/EOorg/EOeolang/EOstring$EOas_bytes.java`, `eo-runtime/src/main/java/EOorg/EOeolang/EOint$EOplus.java`, `eo-runtime/src/main/java/EOorg/EOeolang/EOfloat$EOtimes.java`, `eo-runtime/src/main/java/EOorg/EOeolang/EOfloat$EOplus.java`, `eo-runtime/src/main/java/EOorg/EOeolang/EObytes$EOright.java`, `eo-runtime/src/main/java/EOorg/EOeolang/EObytes$EOas_string.java`, `eo-runtime/src/main/java/EOorg/EOeolang/EObytes$EOeq.java`, `eo-runtime/src/main/java/EOorg/EOeolang/EObool$EOif.java`, `eo-runtime/src/main/java/EOorg/EOeolang/EOerror.java`, `eo-runtime/src/main/java/EOorg/EOeolang/EOint$EOdiv.java`, `eo-runtime/src/main/java/EOorg/EOeolang/EOio/EOstdout.java`, `eo-runtime/src/test/java/org/eolang/AtLambdaTest.java`, `eo-runtime/src/main/java/EOorg/EOeolang/EOram$EOslice.java`, `/eo-runtime/src/main/java/EOorg/EOeolang/EOram$EOram_slice$EO\317\206.java"`, `eo-runtime/src/main/java/EOorg/EOeolang/EObool$EOwhile.java`, `eo-runtime/src/main/java/EOorg/EOeolang/EOio/EOstdin$EOnext_line.java`, `eo-runtime/src/main/java/EOorg/EOeolang/EObytes$EOslice.java`, `eo-runtime/src/main/java/EOorg/EOeolang/EOram$EOwrite.java`, `eo-runtime/src/main/java/EOorg/EOeolang/EObytes$EOconcat.java`, `eo-runtime/src/main/java/EOorg/EOeolang/EOram$EOram_slice$EOwrite.java`, `eo-runtime/src/main/java/EOorg/EOeolang/EOcage.java`, `eo-runtime/src/main/java/EOorg/EOeolang/EOtry.java`, `eo-runtime/src/main/java/EOorg/EOeolang/EOmemory.java`, `eo-runtime/src/main/java/EOorg/EOeolang/EOseq.java`, `eo-runtime/src/main/java/org/eolang/Atom.java`, `eo-runtime/src/main/java/org/eolang/PhDefault.java`, `eo-runtime/src/main/java/org/eolang/AtLambda.java`, `eo-runtime/src/main/java/EOorg/EOeolang/EOstring$EOslice.java`, `eo-runtime/src/main/java/org/eolang/AtComposite.java`, `eo-runtime/src/main/java/EOorg/EOeolang/EOrust.java`, `.codacy.yml`, `eo-runtime/src/main/java/EOorg/EOeolang/EOgoto.java`, `eo-runtime/src/main/java/EOorg/EOeolang/EOheap$EOpointer$EOblock.java`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@yegor256 please have a look

**Comment by maxonfjvipon** [comment]
@yegor256 please have a look

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@maxonfjvipon thanks!

**Pull request merged**
