### PR TITLE
fix(#3213): delta in formation to application on phi + termination to error

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Ref: #3213 
Ref: #3212

---

## PR-Codex overview
This PR focuses on improving the EO Maven plugin and parser by refining object properties and adding license information.

### Detailed summary
- Updated object properties in parser for `LambdaBinding` and `Termination`
- Added license information to YAML test files
- Implemented byte wrapping transformation in `UnphiMojo`
- Created XSL file for byte wrapping transformation

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
@rultor merge

**Comment by maxonfjvipon** [comment]
@yegor256 let's make a new release with tag `0.38.3`

**Comment by yegor256** [comment]
@rultor release, tag is `0.38.3`

**Pull request merged**
