### PR TITLE
refactor(#1633): Remove duplication between `FtDefault` and `FtCached`

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
Remove duplication between `FtDefault` and `FtCached`.

Closes: #1633

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
@mximp Can you take a look, please?

**Review by mximp — APPROVED** [review]

**Comment by volodya-lombrozo** [comment]
@yegor256 Can you merge that PR, please?

**Comment by yegor256** [comment]
@rultor merge

**Comment by volodya-lombrozo** [comment]
@yegor256 can we merge it again, please?

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
