### PR TITLE
feat(#3247): added `+rt node` meta

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Closes: #3247 

---

## PR-Codex overview
The focus of this PR is to update the runtime environment for EO language from JVM to Node.js. 

### Detailed summary
- Updated runtime environment to Node.js
- Updated version numbers for compatibility

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
@rultor merge

**Review by yegor256 — APPROVED** [review]
lgtm

**Comment by 0crat** [comment]
@maxonfjvipon Thanks for the contribution! You've earned +20 points for this. Please, [keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) them coming. Your running balance is [+20](https://objectionary.github.io/eo/zerocracy.html).

**Comment by 0crat** [comment]
@yegor256 Thanks for the review! You've earned +25 points for this.

**Pull request merged**
