### PR TITLE
feat(#3251): multiplatform console read

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Ref: #3251

---

## PR-Codex overview
The focus of this PR is to enhance the Wincon and CStdLib interfaces in the EOsys package, update the Win32 object in sys package, and introduce a new ReadFileFuncCall for Win32. 

### Detailed summary
- Updated Wincon interface with constants
- Added new constants to CStdLib interface
- Enhanced Win32 object in sys package
- Introduced ReadFileFuncCall for Win32
- Refactored console object in io package

> The following files were skipped due to too many changes: `eo-runtime/src/main/eo/org/eolang/io/console.eo`, `eo-runtime/src/test/java/EOorg/EOeolang/EOio/InputOutputTest.java`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
@rultor merge

**Review by yegor256 — APPROVED** [review]
LGTM

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Comment by maxonfjvipon** [comment]
@yegor256 the process was killed(

**Comment by 0crat** [comment]
@yegor256 Hey there, code review superstar! 🌟 You've just racked up a sweet **35 points** for your latest review. Here's the breakdown: **15** points for being an awesome reviewer, plus a whopping **30** for tackling those 1,750 hits-of-code (that's some serious dedication!). We had to dock **10** points because there were only 3 comments (remember, we're aiming for at least 6 next time), but don't let that discourage you. Your total balance is now sitting pretty at [+213](https://www.eolang.org/zerocracy/objectionary-vitals.html) – keep up the great work!

**Comment by 0crat** [comment]
@maxonfjvipon Hey there! 👋 Great job on your contribution! You've earned +5 points, which is the minimum reward we give. Here's the breakdown: +20 base points, -7 for exceeding 200 hits-of-code, -15 for surpassing 800 hits-of-code (wow, 1750!), and -5 for having only 4 comments. We love to see big contributions, but remember that [quality matters too](https://www.yegor256.com/2018/03/06/speed-vs-quality.html). Next time, try to keep it under 800 hits-of-code and encourage more review comments. Your balance is now [+239](https://www.eolang.org/zerocracy/objectionary-vitals.html). Keep up the good work and happy coding! 🚀

**Pull request merged**
