### PR TITLE
(#1007) - Use Concurrent map

### LINKED ISSUE #1007: Ram is not thread safe
Ram is a singleton, if it's being used from two threads, CME will happen.
https://github.com/objectionary/eo/blob/master/eo-runtime/src/main/java/EOorg/EOeolang/Ram.java
https://github.com/objectionary/eo/blob/master/eo-runtime/src/main/eo/org/eolang/ram.eo

### PR DESCRIPTION
**Pull request by andreoss**
Closes #1007

### CODE REVIEW

**Comment by yegor256** [comment]
@andreoss would be nice to reproduce this error first, in a test. Maybe this way: https://www.yegor256.com/2018/03/27/how-to-test-thread-safety.html Otherwise, how do we know 1) the problem was there, and 2) this PR fixes it?

**Comment by andreoss** [comment]
@yegor256 
The problem was reproducible with `junit.jupiter.execution.parallel.enabled = true
`.

I added annotation to run run all there tests simultaneously.

**Comment by yegor256** [comment]
@andreoss I don't see the annotation. where is it?

**Comment by andreoss** [comment]
@yegor256 forgot to push, it's there now

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@andreoss thanks!

**Pull request merged**
