### PR TITLE
feat(#3251): introduced `random` object via syscalls from `eo-math`

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Ref: #3251

---

## PR-Codex overview
The focus of this PR is to add the `gettimeofday` syscall functionality to the EOsys.Posix module. 

### Detailed summary
- Added `gettimeofday` syscall to `CStdLib` interface.
- Implemented `GettimeofdaySyscall` in `EOsys.Posix`.
- Updated documentation in `random.eo` and `GettimeofdaySyscall.java`.

> The following files were skipped due to too many changes: `eo-runtime/src/main/eo/org/eolang/math/random.eo`, `eo-runtime/src/main/java/EOorg/EOeolang/EOsys/Win32/Kernel32.java`, `eo-runtime/src/main/java/EOorg/EOeolang/EOsys/Win32/GetSystemTimeFuncCall.java`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Review by yegor256 — APPROVED** [review]
@maxonfjvipon LGTM

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
@maxonfjvipon Thank you for your contribution! We appreciate your effort. You've earned +4 points for this submission: +4 as a base reward, -8 for exceeding the recommended hits-of-code (478 ≥ 200), and -4 for the low number of review comments (3). While we encourage substantial contributions, please keep in mind our [guidelines](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) for code size and review engagement. Your current balance stands at [+45](https://www.eolang.org/zerocracy/objectionary-vitals.html). We look forward to your future contributions and increased collaboration in code reviews.

**Comment by 0crat** [comment]
@yegor256 Thank you for your code review! Your effort is appreciated, but there's room for improvement. Based on our policy, you've earned +4 points as a base reward. However, we had to deduct 10 points due to the low number of comments (only 4). To ensure a minimum reward, we've adjusted your total to +4 points. Keep in mind that more detailed feedback can significantly boost your score in future reviews. Your current balance stands at [+119](https://www.eolang.org/zerocracy/objectionary-vitals.html). Let's aim for more comprehensive reviews next time! 💪

**Pull request merged**
