### PR TITLE
fix(#2544): fixed delimited name

### PR DESCRIPTION
**Pull request by Yanich96**
Closes: #2544

---

## PR-Codex overview
This PR focuses on replacing the usage of `String.join` with a new `DelimitedName` class in the codebase. 

### Detailed summary
- Replaces `String.join` with `new DelimitedName` in multiple files
- Updates method calls and assignments to use `DelimitedName` class
- Removes the static constant `DELIMITER` from `OnReplaced` class
- Updates unit tests to use `DelimitedName` for string conversions
- Updates `Place` class to use `DelimitedName` for file name generation
- Updates `DiscoverMojo` class to use `DelimitedName` for XML parsing

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@yegor256 please approve the workflow

**Comment by Yanich96** [comment]
I have done this task, please approve @maxonfjvipon

**Review by maxonfjvipon — APPROVED** [review]
@Yanich96 well done! 
@yegor256 could you please have a look

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
