### PR TITLE
feat(#3108): got rid of `if` atom, introduced `true` and `false` objects

### PR DESCRIPTION
**Pull request by maxonfjvipon**
What's done:
1. Literas `TRUE` and `FALSE` are removed from the grammar
2. New objects `true` and `false` are introduced.
3. `if` atom was implemented in java and moved to `true` and `false` objects
4. Tests were fixed and refactored
5. `TRUE` and `FALSE` usages were replaced with `true` and `false` in whole project
6. `and` and `or` objects were duplicated in `true` and `false` so their result would be `true` or `false` but not `bytes`

Closes: #3108 

---

## PR-Codex overview
This PR focuses on updating boolean values from uppercase to lowercase in multiple files. 

### Detailed summary
- Updated boolean values from uppercase to lowercase in various files
- Removed unnecessary files and imports

> The following files were skipped due to too many changes: `eo-maven-plugin/src/test/resources/org/eolang/maven/sodgs/data.yaml`, `eo-maven-plugin/src/test/resources/org/eolang/maven/print/samples/compares-bool-to-bytes.yaml`, `eo-runtime/src/test/eo/org/eolang/string-tests.eo`, `eo-runtime/src/test/eo/org/eolang/try-tests.eo`, `eo-runtime/src/test/eo/org/eolang/malloc-tests.eo`, `eo-runtime/src/test/java/org/eolang/PhPackageTest.java`, `eo-maven-plugin/src/test/resources/org/eolang/maven/sodgs/dots.yaml`, `eo-runtime/src/test/eo/org/eolang/nan-tests.eo`, `eo-parser/src/test/java/org/eolang/parser/EoSyntaxTest.java`, `eo-parser/src/test/resources/org/eolang/parser/packs/catches/catches-many-free-attrs.yaml`, `eo-parser/src/test/resources/org/eolang/parser/packs/parsed-data.yaml`, `eo-parser/src/test/resources/org/eolang/parser/packs/all-data-types.yaml`, `eo-runtime/src/test/eo/org/eolang/seq-tests.eo`, `eo-runtime/src/main/eo/org/eolang/if.eo`, `eo-runtime/src/test/eo/org/eolang/if-tests.eo`, `eo-parser/src/test/resources/org/eolang/parser/samples/same-name-inners.yaml`, `eo-runtime/src/test/eo/org/eolang/switch-tests.eo`, `eo-runtime/src/test/eo/org/eolang/runtime-tests.eo`, `eo-parser/src/test/java/org/eolang/parser/StEoLoggedTest.java`, `eo-runtime/src/main/eo/org/eolang/switch.eo`, `eo-runtime/src/test/eo/org/eolang/bool-tests.eo`, `eo-runtime/src/main/eo/org/eolang/positive-infinity.eo`, `eo-runtime/src/test/eo/org/eolang/memory-tests.eo`, `eo-parser/src/test/resources/org/eolang/parser/packs/explicit-data.yaml`, `eo-maven-plugin/src/test/resources/org/eolang/maven/packs/pre/data-as-bytes.yaml`, `eo-runtime/src/main/eo/org/eolang/negative-infinity.eo`, `eo-runtime/src/test/eo/org/eolang/while-tests.eo`, `eo-runtime/src/main/java/org/eolang/Data.java`, `eo-runtime/src/test/eo/org/eolang/negative-infinity-tests.eo`, `eo-runtime/src/test/eo/org/eolang/int-tests.eo`, `eo-runtime/src/test/eo/org/eolang/positive-infinity-tests.eo`, `eo-runtime/src/test/eo/org/eolang/float-tests.eo`, `eo-maven-plugin/src/test/resources/org/eolang/maven/phi/yaml/bool-tests.yaml`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Comment by maxonfjvipon** [comment]
@yegor256 object `bool` looks like something redundant here. Maybe we should get rid of it too? We'll just have 2 objects `true` and `false` with all bool methods inside
WDYT?

**Comment by yegor256** [comment]
@maxonfjvipon yes, I agree, we can get rid of `bool` (but in another PR)

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
