### PR TITLE
test(#1616) for `AtConst`

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
1) Add tests for `AtConst`
2) Increase `jacoco` limits

Closes: #1616

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
@Graur Can you take a look, please?

**Review by Graur — APPROVED** [review]
@volodya-lombrozo Looks good to me
@yegor256 Check, please

**Comment by Graur** [comment]
@volodya-lombrozo Looks like we need to add a new line at the end of the test file

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
