### PR TITLE
fix(#2866): fixed `ξ` without dispatch + enabled phi pack

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Closes: #2866 
Closes: #2864

---

## PR-Codex overview
This PR focuses on improving the code diff in the eo-parser and eo-maven-plugin modules. 

### Detailed summary
- In `Phi.g4`:
  - Dispatch rule is modified to allow `(attr+ disp)` to be optional.
- In `pom.xml`:
  - The stack size is increased from 128M to 256M.
- In `XePhiListener.java`:
  - The condition `if (!this.attributes.empty())` is removed.
- In `as-phi.yaml`:
  - The skip flag is removed.
  - A comment is modified in the `phi` section.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@yegor256 please have a look

**Comment by maxonfjvipon** [comment]
@yegor256 please have a look

**Comment by maxonfjvipon** [comment]
@yegor256 please have a look

**Comment by yegor256** [comment]
@maxonfjvipon something is wrong here. We can't have an attribute `\tau_i`. Only `\alpha_i`, `\varphi`, etc. `\tau` is a letter that stands for attribute name, when we don't know the name of it, in formulas.

**Comment by maxonfjvipon** [comment]
@yegor256 so, when we meet `\tau` in phi expression, how it should be converted to XMIR?

**Comment by maxonfjvipon** [comment]
@yegor256 or it won't exist in result phi expression?

**Comment by yegor256** [comment]
@maxonfjvipon there will be no `\tau` in a phi expression. It's illegal syntax.

**Comment by maxonfjvipon** [comment]
@yegor256 please have a look

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@maxonfjvipon do you have any idea why this happens? Maybe we should increase memory for Java/Maven somehow?

**Comment by maxonfjvipon** [comment]
@yegor256 I increased stack size, let's try to merge again

**Comment by maxonfjvipon** [comment]
@yegor256 I increased stack size, let's try to merge again

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@maxonfjvipon thanks!

**Pull request merged**
