### PR TITLE
#2257: BinarizeDir can be configured via pom.xml

### LINKED ISSUE #2257: BinarizeParseMojo.java:61-63: Specify directory for names...
The puzzle `2238-ba23d431` from #2238 has to be resolved: 

https://github.com/objectionary/eo/blob/16bcbb3ef550c8dff1e0c7228f9c11d0f9fd80bc/eo-maven-plugin/src/main/java/org/eolang/maven/BinarizeParseMojo.java#L61-L63

The puzzle was created by rultor on 14-Jul-23. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

### PR DESCRIPTION
**Pull request by levBagryansky**
Closes #2257

---

## PR-Codex overview
This PR focuses on improving the handling of the `Names` file in the `eo-maven-plugin`. 

### Detailed summary
- The `Names` constructor now takes a `target` parameter and assigns it to the `dest` field.
- The `namesDir` parameter is added to the `BinarizeMojo` and `BinarizeParseMojo` classes.
- The `namesDir` parameter is used to create a `Names` object in the `BinarizeParseMojo` class.
- The `NamesTest` class now uses the `names` directory for creating `Names` objects.
- The `BinarizeParseMojo` class uses the `namesDir` parameter to create a `Names` object.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by levBagryansky** [comment]
@Graur could you please review?

**Comment by levBagryansky** [comment]
@Graur please review

**Review by Graur — APPROVED** [review]
@levBagryansky Nice, thanks!

**Comment by levBagryansky** [comment]
@yegor256 please check

**Comment by levBagryansky** [comment]
@yegor256 please check

**Comment by levBagryansky** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
