### PR TITLE
fix(#3400): fixed `try` object

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Closes: #3400
Closes: #3396

---

## PR-Codex overview
This PR focuses on refactoring the `EOtry` class by removing redundant code and simplifying the structure of exception handling. It also updates test cases to ensure they work with new values and modifies data retrieval methods for better clarity.

### Detailed summary
- Deleted `EOdataized.java` and updated references in tests.
- Changed `message.as-bytes.size` usage in tests.
- Updated socket connection parameters in `EOsocketTest` from `1234` to `8080` and `LOCALHOST` to `"127.0.0.0"`.
- Simplified the `EOtry` class by removing the `PhTry`, `TryExecute`, and `TryReturn` classes.
- Improved exception handling in the `lambda` method of `EOtry`.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Review by yegor256 — APPROVED** [review]
@maxonfjvipon LGTM

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
@yegor256 Great job on the review! 🌟 You've earned +4 points: +4 base, -10 for limited comments (only 4), but +10 to ensure you receive something. Your current balance stands at [-35](https://www.eolang.org/zerocracy/objectionary-vitals.html). Keep up the good work and aim for more detailed feedback next time!

**Comment by 0crat** [comment]
@maxonfjvipon Great contribution! 🎉 You've earned +4 points: +4 base, -8 for high hits-of-code (284 ≥ 200), -4 for limited comments (4), +12 bonus. Your balance is now [+44](https://www.eolang.org/zerocracy/objectionary-vitals.html). Keep the momentum going and [focus on quality](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) in your next submission!

**Pull request merged**
