### PR TITLE
Create an object for testing application, that accepts arguments in the form of `tuple`

### LINKED ISSUE #2723: MainTest.java:43-48: Enable the tests. Tests {@link...
The puzzle `2718-833aa636` from #2718 has to be resolved: 

https://github.com/objectionary/eo/blob/aaf5969452699c72bfcd9c33fc1299e3df77f845/eo-runtime/src/test/java/org/eolang/MainTest.java#L43-L48

The puzzle was created by rultor on 22-Dec-23. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

### PR DESCRIPTION
**Pull request by c71n93**
Closes #2723

---

## PR-Codex overview
This PR focuses on enabling two tests in the `MainTest` class that were previously disabled. The changes include replacing the `org.eolang.io.stdout` object with a new object `org.eolang.io.tupled-stdout` that accepts a tuple as the first argument. 

### Detailed summary
- Enabled the `deliversCleanOutput()` test by replacing `org.eolang.io.stdout` with `org.eolang.io.tupled-stdout`.
- Enabled the `executesJvmFullRun()` test by replacing `org.eolang.io.stdout` with `org.eolang.io.tupled-stdout`.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by c71n93** [comment]
@maxonfjvipon could you check this one, please?

**Comment by c71n93** [comment]
@maxonfjvipon Check, please. I just moved `tupled-stdout.eo` from `main` to `test`. Is it okay? WDYT?

**Comment by maxonfjvipon** [comment]
@c71n93 I think it's okay for the test purposes
@yegor256 WDYT?

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
