### PR TITLE
feat(#2175): Add more tests for abstracts-float-up and fix the bug

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
Add more tests for `abstracts-float-up.xsl` and fix the bug with redundant arguments.

Closes: #2175 

---

## PR-Codex overview
This PR optimizes the EO parser by fixing a problem with redundant objects. It introduces changes to the `abstracts-float-up.xsl` and `remove-levels.xsl` transformations, and includes improvements to the corresponding test cases.

### Detailed summary
- Fix problem with redundant objects
- Update `abstracts-float-up.xsl` and `remove-levels.xsl` transformations
- Improve test cases for `redundant-levels-with-siblings.yaml`, `redundant-levels-with-arguments-and-siblings.yaml`, and `redundant-levels-with-arguments-and-abstract-parents.yaml`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
@Graur Could you have a look, please?

**Review by Graur — APPROVED** [review]
@volodya-lombrozo Looks good to me
@yegor256 Please have a look

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you merge that changes, please?

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
