### PR TITLE
test(#1619) add test for `PhLogged`

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
Add test for `PhLogged`

Closes: #1619

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
@Graur Can you take a look, please?

**Review by Graur — APPROVED** [review]
@volodya-lombrozo Good one!

**Comment by volodya-lombrozo** [comment]
@yegor256 Can you merge that changes, please?

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
