### PR TITLE
#920 add architect meta

### PR DESCRIPTION
**Pull request by OlesiaSub**

### CODE REVIEW

**Comment by OlesiaSub** [comment]
#920 
@yegor256 please check

**Comment by yegor256** [comment]
@OlesiaSub do we have a test for this new feature? We keep them in `eo-parser/src/test/resources/.../packs`

**Comment by OlesiaSub** [comment]
@yegor256 we do have a new catches-incorrect-architect test, but I put it in ...packs/catches

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@OlesiaSub install [xcop](https://rubygems.org/gems/xcop) locally and run the build again. You will see that some of your XML/XSL files are not correctly formatted.

**Comment by OlesiaSub** [comment]
@yegor256 done

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@OlesiaSub thanks!

**Pull request merged**
