### PR TITLE
Add cosmetic fixes

### LINKED ISSUE #3663: `failOnWarning` must be turned ON in eo-runtime
Currently, `failOnWarning` is set to `false` in `eo-runtime/pom.xml`. Let's put it to `true` and fix all warnings in `.eo` files: most of them are cosmetic.

### PR DESCRIPTION
**Pull request by uchitsa**
#3663 some fixes

### CODE REVIEW

**Comment by uchitsa** [comment]
@yegor256  hello, please take a look

**Comment by yegor256** [comment]
@uchitsa thanks for your contribution, but the build is not green so far

**Comment by uchitsa** [comment]
@yegor256 updated, all checks are green

**Comment by yegor256** [comment]
@uchitsa thanks!

**Pull request merged**
