### PR TITLE
feat(#1928): Remove PlacedTojosCache

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
Remove unused PlacedTojosCache.

Closes: #1928

---

## PR-Codex overview
This PR removes the `PlacedTojosCache` class and replaces all its usages with the `placedTojos` field in `PlaceMojo`. It also adds a new method to `PlacedTojos` to find a `PlacedTojo` by path.

### Detailed summary
- Removed `PlacedTojosCache` class
- Replaced all usages of `PlacedTojosCache` with `placedTojos` field in `PlaceMojo`
- Added `find` method to `PlacedTojos` to find a `PlacedTojo` by path

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
Blocked by https://github.com/yegor256/tojos/pull/65#issuecomment-1602689265

**Comment by volodya-lombrozo** [comment]
@Graur Could you have a look, please?

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you merge that changes, please?

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
