### PR TITLE
#1666 adding location info

### LINKED ISSUE #1666: Make `PhLocated` and `AtLocated` to accept location source information
Let's extend `PhLocated` and `AtLocated` to hold source information along with line and position.
Potentially the source is contained within `loc` attribute in XMIR:
```
<o base=".with" line="87" loc="Φ.org.eolang.collections.multimap$find-in-list$t2$a2.φ.α0" pos="11"> 
``` 
It also should be printed within location information:
```
<Φ.org.eolang.collections.multimap$find-in-list$t2$a2.φ.α0:82:10>
```

### PR DESCRIPTION
**Pull request by mximp**
closes #1666

### CODE REVIEW

**Comment by mximp** [comment]
@yegor256 please check

**Comment by mximp** [comment]
@yegor256 reminder

**Comment by yegor256** [comment]
@mximp probably you forgot to modify `to-java.xsl`? I don't see how you pass this `@loc` attribute to `PhLocated`

**Comment by mximp** [comment]
> @mximp probably you forgot to modify `to-java.xsl`? I don't see how you pass this `@loc` attribute to `PhLocated`

@yegor256 It's requested in different task: #1667. We cannot modify both runtime and the plugin in this case - the build fails.

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
