### PR TITLE
refactor(#2484): remove redundant parentheses check

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Closes: #2484 

Since #2474 is done `RedundantParentheses` class is no more needed

---

## PR-Codex overview
This PR focuses on removing redundant parentheses in the code. 

### Detailed summary
- Deleted `RedundantParentheses.java` and `RedundantParenthesesTest.java`.
- Added new EO code snippets in various YAML files.
- Updated `redundant-parentheses.yaml` with multiple test cases.
- Added a new comment line and an empty list in `redundant-parentheses.yaml`.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@Graur please review this one

**Review by Graur — APPROVED** [review]
@maxonfjvipon Looks good, thanks!

**Comment by maxonfjvipon** [comment]
@yegor256 please have a look

**Comment by maxonfjvipon** [comment]
@yegor256 please have a look

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
