### PR TITLE
feat(#3251): introduced `i64` object

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Ref: #3251

What's done:
1. the object `i64` is introduced
2. `number.is-nan`, `number.is-finite`, `number.is-integer` objects are added
3. implementations of `nan`, `positive-infinity` and `negative-infinity` are changed
4. `Data.ToPhi` can return `nan`, `positive-infinity` or `negative-infinity` objects
5. implementations of `hash-code-of` and `text` objects are fixed
6. some tests are fixed

---

## PR-Codex overview
The focus of this PR is to add new tests, improve error handling, and optimize type conversions in EO programming language modules.

### Detailed summary
- Added new tests for various functionalities
- Improved error handling for type conversions
- Optimized type conversions in EO modules

> The following files were skipped due to too many changes: `eo-runtime/src/main/java/org/eolang/Data.java`, `eo-runtime/src/main/eo/org/eolang/positive-infinity.eo`, `eo-runtime/src/main/java/EOorg/EOeolang/EOi64$EOas_number.java`, `eo-runtime/src/main/java/EOorg/EOeolang/EOnumber$EOas_i64.java`, `eo-runtime/src/main/java/EOorg/EOeolang/EOi64$EOgt.java`, `eo-runtime/src/main/java/EOorg/EOeolang/EOi64$EOdiv.java`, `eo-runtime/src/main/java/EOorg/EOeolang/EOi64$EOtimes.java`, `eo-runtime/src/main/java/EOorg/EOeolang/EOi64$EOplus.java`, `eo-runtime/src/main/eo/org/eolang/i64.eo`, `eo-runtime/src/main/eo/org/eolang/number.eo`, `eo-runtime/src/test/eo/org/eolang/i64-tests.eo`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Comment by maxonfjvipon** [comment]
@yegor256 I need your advice: what should `i64` object decorate - `bytes` or `number`. If it decorates `number` then all bytes operations would skip `i64.as-bytes` representation which is different from `number.as-bytes` representation.

**Comment by maxonfjvipon** [comment]
@yegor256 WDYT?

**Comment by maxonfjvipon** [comment]
@yegor256 WDYT?

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Review by yegor256 — APPROVED** [review]
@maxonfjvipon LGTM, thanks!

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
@maxonfjvipon Great contribution! Your efforts have earned you +4 points: +4 base, -8 for exceeding 200 hits-of-code (1135), -16 for surpassing 800 hits-of-code, -4 for only 5 review comments, and +28 adjustment to ensure fair compensation. While the code volume was high, remember that [quality often trumps quantity](https://www.yegor256.com/2018/03/06/speed-vs-quality.html). Your current balance stands at [+72](https://www.eolang.org/zerocracy/objectionary-vitals.html). Keep up the good work, and consider more compact, well-reviewed contributions in the future!

**Comment by 0crat** [comment]
@yegor256 Great job on the review! 🎉 Your efforts have earned you +5 points: +4 base points, +16 (capped from +11.35) for reviewing 1135 hits-of-code, -10 for having only 5 comments, and -5 for self-review. Remember, more comments can boost your score next time! Your current balance stands at [+114](https://www.eolang.org/zerocracy/objectionary-vitals.html). Keep up the excellent work!

**Pull request merged**
