### PR TITLE
fix(#2541): removed `master` commit hash pair

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Closes: #2541

---

## PR-Codex overview
This PR focuses on adding a new field to the SafeMojo class and making changes to the CommitHashesMap class. 

### Detailed summary
- Added a new field "hash" to the SafeMojo class.
- Updated the CommitHashesMap class to remove the "master" hash from the table and update tests accordingly.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@Graur please review this one

**Review by Graur — APPROVED** [review]
@maxonfjvipon Good one!

**Comment by maxonfjvipon** [comment]
@yegor256 please have a look

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
