### PR TITLE
Dataize returns u8 array

### PR DESCRIPTION
**Pull request by levBagryansky**
Closes: #2445 
`eo_env.dataize` should return `Vec<u8>` in order to avoid unsafe operations in the insert.

---

## PR-Codex overview
This PR focuses on changing the `dataize` function in `eo_env.rs` to return a `Vec<u8>` instead of `Vec<i8>`. It also updates the usage of `dataize` in `rust-tests.eo` to handle the new return type. 

### Detailed summary
- Changed `dataize` function in `eo_env.rs` to return `Vec<u8>` instead of `Vec<i8>`
- Updated usage of `dataize` in `rust-tests.eo` to handle new return type

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by levBagryansky** [comment]
@Graur could you please take a look

**Comment by Graur** [comment]
@levBagryansky Were is the related issue?

**Comment by levBagryansky** [comment]
@Graur it here: #2445

**Review by Graur — APPROVED** [review]
@levBagryansky Thanks!
@yegor256 Please take a look

**Comment by levBagryansky** [comment]
@yegor256 please take a look

**Comment by yegor256** [comment]
@rultor merge

**Comment by levBagryansky** [comment]
@yegor256 please check, there were conficts with other branches related to rust inserts

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
