### PR TITLE
feat(#2392): Add tests for ForeignTojos.find method

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
Add tests for `ForeignTojos#find()` method.

Closes: #2392

---

## PR-Codex overview
This PR focuses on adding unit tests for the `ForeignTojos.find` method in the `eo-maven-plugin`. The changes include:
- Adding a unit test for the `find` method
- Implementing the `equals` and `hashCode` methods in `ForeignTojo` class

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
@Graur Could you take a look, please?

**Review by Graur — APPROVED** [review]
@volodya-lombrozo Good one, thanks!
@yegor256 Please, have a look

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you merge that changes?

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
