### PR TITLE
feat(#2119): rename synthetic-reference.xsl -> scopes.xsl

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
Rename `synthetic-reference.xsl` transformation to `scopes.xsl` transformation and alias attribute to scope attribute.

Closes: #2119

---

## PR-Codex overview
This PR focuses on replacing the concept of "aliases" with "scopes" in the codebase. 

### Detailed summary
- Replaced references to "aliases" with "scopes" in various files
- Renamed `alias()` method to `scope()` and `closeAlias()` method to `closeScope()` in `Objects` class
- Updated XSLT stylesheet names from `synthetic-references.xsl` to `scopes.xsl`
- Updated relevant test resources and configurations

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
@Graur Could you have a look, please?

**Comment by Graur** [comment]
@volodya-lombrozo Looks like some checks failed

**Comment by volodya-lombrozo** [comment]
@Graur Could you have a look one more time, please?

**Review by Graur — APPROVED** [review]
@volodya-lombrozo Looks good to me

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you merge that changes, please?

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
