### PR TITLE
fix(#2528): flag for not rewriting classes on `test-compile` step

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Ref: #2528

What's done:
- Added flag `rewriteBinaries` that allows to rewrite `.class` files in `target/classes` folder
- Added integration test to check if `test-compile` does not rewrite binaries in `target/classes` folder
- `Home` object is split into two objects: `HmBase` and `HmOptional`

---

## PR-Codex overview
This PR focuses on updating the EO Maven plugin. 

### Detailed summary
- Added `invoker.goals` property in `invoker.properties` file.
- Added logo and description in `README.md` file.
- Renamed `Home` class to `HmBase` in multiple test files.
- Added new parameter `rewriteBinaries` in `SafeMojo` class.
- Renamed `Home` class to `HmBase` in multiple main files.
- Renamed `Home` class to `HmBase` in multiple test files.
- Renamed `Home` class to `HmBase` in multiple util files.
- Renamed `Home` class to `HmBase` in multiple footprint files.
- Renamed `Home` class to `HmBase` in multiple rust files.
- Renamed `Home` class to `HmBase` in multiple name files.
- Renamed `Home` class to `HmBase` in multiple copy files.
- Renamed `Home` class to `HmBase` in multiple optimization files.
- Renamed `Home` class to `HmBase` in multiple transpile files.

> The following files were skipped due to too many changes: `eo-maven-plugin/src/main/java/org/eolang/maven/TranspileMojo.java`, `eo-maven-plugin/src/test/java/org/eolang/maven/TranspileMojoTest.java`, `eo-maven-plugin/src/main/java/org/eolang/maven/hash/CommitHashesMap.java`, `eo-maven-plugin/src/test/java/org/eolang/maven/objectionary/OyHomeTest.java`, `eo-maven-plugin/src/test/java/org/eolang/maven/JavaFilesTest.java`, `eo-maven-plugin/src/test/java/org/eolang/maven/DepDirsTest.java`, `eo-maven-plugin/src/test/java/org/eolang/maven/UnspileMojoTest.java`, `eo-maven-plugin/src/test/java/org/eolang/maven/PullMojoTest.java`, `eo-maven-plugin/src/test/java/org/eolang/maven/UnplaceMojoTest.java`, `eo-maven-plugin/src/test/java/org/eolang/maven/OptimizeMojoTest.java`, `eo-maven-plugin/src/test/java/org/eolang/maven/RegisterMojoTest.java`, `eo-maven-plugin/src/test/java/org/eolang/maven/PlaceMojoTest.java`, `eo-maven-plugin/src/it/rewritten_sources/src/main/eo/org/eolang/math/e.eo`, `eo-maven-plugin/src/it/rewritten_sources/src/main/eo/org/eolang/math/pi.eo`, `eo-maven-plugin/src/test/java/org/eolang/maven/FakeMaven.java`, `eo-maven-plugin/src/it/rewritten_sources/src/test/eo/org/eolang/math/e-tests.eo`, `eo-maven-plugin/src/it/rewritten_sources/src/test/eo/org/eolang/math/pi-tests.eo`, `eo-maven-plugin/src/test/java/org/eolang/maven/CopyMojoTest.java`, `eo-maven-plugin/src/main/java/org/eolang/maven/PlaceMojo.java`, `eo-maven-plugin/src/it/rewritten_sources/src/main/eo/org/eolang/math/integral.eo`, `eo-maven-plugin/src/it/rewritten_sources/src/main/eo/org/eolang/math/series.eo`, `eo-maven-plugin/src/it/rewritten_sources/verify.groovy`, `eo-maven-plugin/src/it/rewritten_sources/src/test/eo/org/eolang/math/integral-tests.eo`, `eo-maven-plugin/src/main/java/org/eolang/maven/SodgMojo.java`, `eo-maven-plugin/src/it/rewritten_sources/src/test/eo/org/eolang/math/random-tests.eo`, `eo-maven-plugin/src/it/rewritten_sources/src/test/eo/org/eolang/math/series-tests.eo`, `eo-maven-plugin/src/it/rewritten_sources/src/main/eo/org/eolang/math/random.eo`, `eo-maven-plugin/src/main/java/org/eolang/maven/util/HmOptional.java`, `eo-maven-plugin/src/test/java/org/eolang/maven/util/HomeTest.java`, `eo-maven-plugin/src/it/rewritten_sources/pom.xml`, `eo-maven-plugin/src/main/java/org/eolang/maven/util/HmBase.java`, `eo-maven-plugin/src/main/java/org/eolang/maven/util/Home.java`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@Graur please review this one

**Review by Graur — CHANGES_REQUESTED** [review]

**Comment by maxonfjvipon** [comment]
@Graur please have a look one more time

**Review by Graur — APPROVED** [review]
@maxonfjvipon I'm not sure about the `HmBase` class name. But in general I have no questions. You have done a great job!

**Comment by maxonfjvipon** [comment]
@Graur what about `HomeBase`?

**Comment by maxonfjvipon** [comment]
@yegor256 please try to merge one more time

**Comment by yegor256** [comment]
@rultor merge

**Comment by maxonfjvipon** [comment]
@yegor256 please try to merge one more time

**Comment by maxonfjvipon** [comment]
@yegor256 please try to merge one more time

**Comment by yegor256** [comment]
@rultor merge

**Comment by maxonfjvipon** [comment]
@yegor256 I remove `eo-runtime` dependency, please try to merge one more time

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
