### PR TITLE
feat(#2044): print meaningful cti messages

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
Print meaningful messages instead of hex values for cti.

Closes: #2044

---

## PR-Codex overview
This PR focuses on improving the error messages in the EO language parser. 

### Detailed summary
- Updated error messages in cti-adds-warning.yaml and cti-adds-error.yaml pack tests.
- Added a new function to convert hex strings to readable UTF-8 strings in cti-adds-errors.xsl.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
@Graur Could you take a look, please?

**Review by Graur — APPROVED** [review]
@volodya-lombrozo Good one!
@yegor256 Please have a look

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you merge that changes, please?

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
