### PR TITLE
#1264 Vertices thread safety

### PR DESCRIPTION
**Pull request by mximp**
fix for #1264

### CODE REVIEW

**Comment by mximp** [comment]
@yegor256 please check

**Comment by mximp** [comment]
@yegor256 please check

**Comment by mximp** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
@mximp try to use this class from Cactoos: https://www.javadoc.io/doc/org.cactoos/cactoos/latest/org/cactoos/experimental/Threads.html It does exactly what you do, but the code will be much more compact

**Comment by mximp** [comment]
@yegor256 yeah, that's shorter now. Please check

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
