### PR TITLE
bug(#3760): Synchronized `StrictXmir`

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Ref: #3760

### CODE REVIEW

**Review by yegor256 — APPROVED** [review]
ok

**Comment by yegor256** [comment]
@rultor release, tag is `0.49.4`

**Comment by 0crat** [comment]
@maxonfjvipon Thanks for the contribution! You've earned +4 points for this: +4 as a basis; -16 for absolutely no comments posted by reviewers; +16 to give you at least something. Please, [keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) them coming.

**Comment by 0crat** [comment]
@yegor256 Thanks for the review! You've earned +4 points for this: +4 as a basis; -10 for very few (3) comments; +10 to give you at least something.  Your running balance is [-8](https://www.eolang.org/zerocracy/objectionary-vitals.html).

**Pull request merged**
