### PR TITLE
#841 bytes as array implementation

### PR DESCRIPTION
**Pull request by mximp**
#841

### CODE REVIEW

**Comment by mximp** [comment]
@yegor256 please check and merge

**Comment by yegor256** [comment]
@mximp looks good, but it should belong to `org.eolang.collections` package

**Comment by mximp** [comment]
> @mximp looks good, but it should belong to `org.eolang.collections` package

I was thinking about it... 

Done, @yegor256 please merge

**Comment by mximp** [comment]
@yegor256 Implemented in EO. Please check and merge.

**Comment by mximp** [comment]
@yegor256 done, please check

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
