### PR TITLE
fix(#3213): convert normalized atoms with Lambda to applications

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Ref: #3213 

---

## PR-Codex overview
This PR updates XML/XSL files and YAML test files in the `eo-maven-plugin` and `eo-parser` modules. 

### Detailed summary
- Updated XSL files for XML transformations
- Modified YAML test files for object properties
- Improved listener method in `XePhiListener.java`

> The following files were skipped due to too many changes: `eo-maven-plugin/src/test/resources/org/eolang/maven/unphi/bindings.yaml`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
