### PR TITLE
feat(#3251): added `text` and `sscanf` objects to `eo-runtime`

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Ref: #3251 

---

## PR-Codex overview
This PR focuses on enhancing the `sprintf` and `sscanf` objects in the `EOtxt` package. It includes improvements to format string parsing and conversions.

### Detailed summary
- Enhanced `sprintf` object with character conversion map
- Improved format parsing and conversions in `sprintf` and `sscanf`
- Updated `sscanf` object with formatted input reading functionality

> The following files were skipped due to too many changes: `eo-runtime/src/main/java/EOorg/EOeolang/EOtxt/EOsscanf.java`, `eo-runtime/src/test/eo/org/eolang/txt/text-tests.eo`, `eo-runtime/src/main/eo/org/eolang/txt/text.eo`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Review by yegor256 — APPROVED** [review]
LGTM

**Comment by yegor256** [comment]
@maxonfjvipon thanks!

**Comment by 0crat** [comment]
@maxonfjvipon Thanks for the contribution! You've earned +5 points for this: +20 as a basis; +5 for 1521 hits-of-code; -7 for too many hits-of-code (1521 >= 100); -15 for way too many hits-of-code (1521 >= 400); -5 for 1 comments; +7 to give you at least something. Please, [keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) them coming. Your running balance is +108.

**Comment by 0crat** [comment]
@yegor256 Thanks for the review! You've earned +25 points for this: +25 as a basis; +5 for 1521 hits-of-code; -5 for 2 comments.  Your running balance is +162.

**Pull request merged**
