### PR TITLE
fixed paper by getting rid of char

### PR DESCRIPTION
**Pull request by Graur**
#643

### CODE REVIEW

**Comment by yegor256** [comment]
@Graur still a draft?

**Comment by Graur** [comment]
@yegor256 Yes, I've got some problem with local check of this paper: `make` didn't work for me

**Comment by Graur** [comment]
@yegor256 please, check. I build this paper somehow, but the whole Makefile still didn't work for me

**Comment by yegor256** [comment]
@Graur thanks!

**Pull request merged**
