### PR TITLE
1877 other design

### LINKED ISSUE #1877: BinarizeMojo.java:61-64: Extract rust code from rust...
The puzzle `1864-29f06796` from #1864 has to be resolved: 

https://github.com/objectionary/eo/blob/5a28e8fd14f67b98623cca8c0acf3461c96bdef6/eo-maven-plugin/src/main/java/org/eolang/maven/BinarizeMojo.java#L61-L64

The puzzle was created by rultor on 06-Mar-23. 

Estimate: 90 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

### PR DESCRIPTION
**Pull request by levBagryansky**
Closes #1877
Redisigned #1945 
Created RustProject class in order to generate rust project and then compie shared library via cargo build command.
Constructor creates the raw cargo project. add method adds new modules to the project. To compile one library from several files rust project structure must look like:
```
.
├── Cargo.lock
├── Cargo.toml
├── src/
│   ├── lib.rs
│   ├── module1.rs
│   ├── module2.rs
...
```
Modules must follow snake_case.
I also fixed the "rust" code to a compiled form.

### CODE REVIEW

**Comment by levBagryansky** [comment]
@Graur please review

**Review by Graur — APPROVED** [review]
@levBagryansky Looks good to me

**Comment by levBagryansky** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
