### PR TITLE
docs(#2537): added docs about running specific integration test

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Closes: #2537 

---

## PR-Codex overview
This PR focuses on updating the README.md file in the eo-maven-plugin. The notable changes include adding instructions on how to run integration tests and how to disable integration tests temporarily. 

### Detailed summary
- Added instructions on how to run integration tests only
- Added command to execute a specific integration test
- Added option to skip unit tests while running integration tests
- Updated instructions on how to disable integration tests

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@Graur please review

**Review by Graur — APPROVED** [review]
@maxonfjvipon Thanks!

**Comment by maxonfjvipon** [comment]
@yegor256 please have a look

**Comment by maxonfjvipon** [comment]
@yegor256 please have a look

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
