### PR TITLE
#2546: Improved error describing

### LINKED ISSUE #2546: sparse decoration warning is unclear
Now sparse decoration warning looks like```
```
[INFO] Shift #0 via 'globals-to-abstracts' made no changes
[INFO] Shift #0 via 'globals-to-abstracts' made no changes
[INFO] Shift #0 via 'globals-to-abstracts' made no changes
Error:  net.sf.saxon.style.XSLText@62f2a4fe: Warnings identified: Sparse decoration is prohibited; 
Error:  #fatalError(): Processing terminated by xsl:message at line 32 in fail-on-warnings.xsl; SystemID: file:///org/eolang/parser/fail-on-warnings.xsl; Line#: 32; Column#: 17
[INFO] Shift #0 via 'globals-to-abstracts' made no changes
[INFO] Shift #0 via 'globals-to-abstracts' made no changes
```
So it does not provide information in which .eo file the mistake happened. Let's expand it

### PR DESCRIPTION
**Pull request by levBagryansky**
Closes #2546 
Improved description of errors. Now it looks like
```
18:21:21 [INFO] org.eolang.maven.ParseMojo: Parsed 1 .eo sources to XMIRs
18:21:23 [ERROR] com.jcabi.xml.XSLDocument: net.sf.saxon.style.XSLMessage@23e78dd0: Warnings identified: 
  /tmp/junit9253374041433086166/foo/x/main.eo, 3: Sparse decoration is prohibited;
  /tmp/junit9253374041433086166/foo/x/main.eo, 4: Sparse decoration is prohibited;
  /tmp/junit9253374041433086166/foo/x/main.eo, : Missing home;
  /tmp/junit9253374041433086166/foo/x/main.eo, : Missing version meta;
18:21:23 [ERROR] com.jcabi.xml.ConsoleErrorListener: #fatalError(): Processing terminated by xsl:message at line 31 in fail-on-warnings.xsl; SystemID: file:///org/eolang/parser/fail-on-warnings.xsl; Line#: 31; Column#: 34
``` 
I did not add  tests since it is just error message.

---

## PR-Codex overview
This PR focuses on adding a test that checks the message of exceptions in case of warnings, errors, and critical issues in xmir. The test includes the filename and line information. 

### Detailed summary
- Added a test in `VerifyMojoTest` class that checks the message of exceptions in xmir.
- Modified `fail-on-errors.xsl`, `fail-on-warnings.xsl`, and `fail-on-critical.xsl` files to include filename and line information in the error messages.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by levBagryansky** [comment]
@volodya-lombrozo please take a look

**Review by volodya-lombrozo — COMMENTED** [review]
@levBagryansky Is it possible to test the logging somehow?

**Comment by volodya-lombrozo** [comment]
@levBagryansky exception messages are logic too and I believe they worth to be tested. But if it is not straightforward, I would suggest leave the puzzle.

**Comment by levBagryansky** [comment]
@volodya-lombrozo Let's leave a puzzle in order to add test to `VerifyMojo` then.

**Comment by volodya-lombrozo** [comment]
@levBagryansky agree

**Comment by levBagryansky** [comment]
@yegor256 please take a look

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
