### PR TITLE
#2710: Verify groovy in eo-maven-plugin

### LINKED ISSUE #2710: maven plugin parameter names inconsistency
In `PrintMojo` we have `eo.printSourcesDir`, while in `UnphiMojo` we have `unphiInputDir`. Obviously, it's not consistent. Let's introduce a test, which will look into `eo-maven-plugin/target/classes/META-INF/maven/plugin.xml` and check that all property names are formatted the same way (let's use a simple regexp).

Probably, such a test should be placed into `src/test/groovy` directory (we already have a few tests over there).

### PR DESCRIPTION
**Pull request by levBagryansky**
Closes #2710
If there are wrong case it fails with
```
[INFO] 
[INFO] --- groovy-maven-plugin:2.1.1:execute (project-validate) @ eo-maven-plugin ---
Verify that parameters passed to java are named consistent
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  18.317 s
[INFO] Finished at: 2024-01-24T22:36:17+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.gmaven:groovy-maven-plugin:2.1.1:execute (project-validate) on project eo-maven-plugin: Execution project-validate of goal org.codehaus.gmaven:groovy-maven-plugin:2.1.1:execute failed: org.apache.maven.plugin.MojoExecutionException: Following parameters don't match pattern \$\{eo\.[a-z]+([A-Z][a-z]+)*}:
[ERROR]  ${phiInputDir}, ${phiOutputDir}

```

---

### Focus of the PR
This PR focuses on updating the Maven plugin configuration by changing the property names and adding new dependencies.

### Detailed summary
- Updated the property names in the `CopySourcesMojo`, `SafeMojo`, `PhiMojo`, and `UnphiMojo` classes.
- Added a new version for the `groovy-maven-plugin` in the `pom.xml`.
- Added a new execution and configuration for the `groovy-maven-plugin` in the `pom.xml`.
- Added a new dependency for `groovy-xml` in the `pom.xml`.
- Added new validation scripts in the `verify.groovy` file.
- Added a new test script for checking parameter names in the `check-parameters-names.groovy` file.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by levBagryansky** [comment]
@maxonfjvipon could you please review these changes

**Comment by levBagryansky** [comment]
@maxonfjvipon please check

**Review by maxonfjvipon — APPROVED** [review]
@levBagryansky LGTM! Thanks

**Comment by levBagryansky** [comment]
@yegor256 please check

**Comment by levBagryansky** [comment]
@yegor256 let's try again

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
