### PR TITLE
feat(#3251): introduced `real` number from `eo-math`

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Ref: #3251

---

## PR-Codex overview
This PR adds new mathematical functions to the `EOreal` class and updates the license information in multiple files.

### Detailed summary
- Added `EOreal$EOpow`, `EOreal$EOasin`, `EOreal$EOacos`, `EOreal$EOln`, and `EOreal$EOsqrt` classes to `EOmath`
- Updated license information in multiple files
- Added alias and architect information in `real.eo`

> The following files were skipped due to too many changes: `eo-runtime/src/main/eo/org/eolang/math/real.eo`, `eo-runtime/src/test/eo/org/eolang/math/real-tests.eo`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Review by yegor256 — CHANGES_REQUESTED** [review]
@maxonfjvipon you forgot to rename the .eo file

**Comment by maxonfjvipon** [comment]
@yegor256 please check one more time

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
@maxonfjvipon Great job on your contribution! 🌟 You've earned +4 points, with adjustments for code volume and review. While there's room for improvement in code size and comments, we appreciate your effort. Your balance is now [+35](https://www.eolang.org/zerocracy/objectionary-vitals.html). Keep the contributions coming and remember to [focus on quality](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) as you code. We're excited to see your next submission!

**Pull request merged**
