### PR TITLE
#2810: More smart printing

### LINKED ISSUE #2810: Logging in `PrintMojo` is not using jcabi-log smart printing
I'm getting this:

```
[INFO] --- eo:0.34.4:print (default-cli) @ benchmark ---
[INFO] Printed: /Volumes/sec/code/o/benchmark/after/generated-sources/opeo-compile/org/eolang/benchmark/F.xmir => /Volumes/sec/code/o/benchmark/after/generated-sources/opeo-compile.eo/org/eolang/benchmark/F.eo
[INFO] Printed: /Volumes/sec/code/o/benchmark/after/generated-sources/opeo-compile/org/eolang/benchmark/App.xmir => /Volumes/sec/code/o/benchmark/after/generated-sources/opeo-compile.eo/org/eolang/benchmark/App.eo
[INFO] Printed: /Volumes/sec/code/o/benchmark/after/generated-sources/opeo-compile/org/eolang/benchmark/A.xmir => /Volumes/sec/code/o/benchmark/after/generated-sources/opeo-compile.eo/org/eolang/benchmark/A.eo
[INFO] Printed: /Volumes/sec/code/o/benchmark/after/generated-sources/opeo-compile/org/eolang/benchmark/B.xmir => /Volumes/sec/code/o/benchmark/after/generated-sources/opeo-compile.eo/org/eolang/benchmark/B.eo
[INFO] Printed: /Volumes/sec/code/o/benchmark/after/generated-sources/opeo-compile/org/eolang/benchmark/BA.xmir => /Volumes/sec/code/o/benchmark/after/generated-sources/opeo-compile.eo/org/eolang/benchmark/BA.eo
[INFO] Printed: /Volumes/sec/code/o/benchmark/after/generated-sources/opeo-compile/org/eolang/benchmark/Main.xmir => /Volumes/sec/code/o/benchmark/after/generated-sources/opeo-compile.eo/org/eolang/benchmark/Main.eo
[INFO] Printed 6 XMIR sources into EO
```

As you see, the paths of files are absolute, which is too verbose. Let's use smart logging from jcabi-log, which prints relative file names automatically, as it's done here: https://github.com/objectionary/jeo-maven-plugin/blob/master/src/main/java/org/eolang/jeo/improvement/ImprovementXmirFootprint.java#L88-L94

Would be great to get rid of the `Rel` class entirely (we use it in many places, but jcabi-log is a more powerful technique).

### PR DESCRIPTION
**Pull request by levBagryansky**
Closes #2810 
Print paths of file relatively current directory if the path is inside the directory (does not start with `"../"`).
For example in tests it looks like `Printed: /tmp/junit11017855222522217884/xmir/foo/x/main.xmir (1Kb) => /tmp/junit11017855222522217884/eo/foo/x/main.eo (197b)` since path starts with `"../"` 

---

## PR-Codex overview
This PR focuses on improving the logging message in the `PrintMojo` class. 

### Detailed summary
- Replaced the logging message format with a more descriptive one.
- Added the file size information to the logging message.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@levBagryansky it would good to write a simple test for it

**Comment by levBagryansky** [comment]
@maxonfjvipon I asked about testing of  in the issue #2810

**Comment by levBagryansky** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
