### PR TITLE
feat(#3001): new cage implementation

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Closes: #3001

---

## PR-Codex overview
This PR enhances memory allocation and object storage in EOlang. It introduces new functionalities, refactors existing code, and improves error handling.

### Detailed summary
- Added `cage.new` object for object storage.
- Updated memory allocation and error handling in `EOmemory$EOalloc.java`.
- Refactored `PhWrite` object for writing to memory.
- Improved object behavior in `cage.eo`.
- Enhanced test cases in `bytes-tests.eo` and `runtime-tests.eo`.
- Updated exclusion path in `codacy.yml`.
- Modified `PhDefault.java` for better object representation.
- Updated `EOmemory.java` and `EOcage$EOnew.java`.

> The following files were skipped due to too many changes: `eo-runtime/src/main/java/EOorg/EOeolang/EOcage$EOnew.java`, `eo-runtime/src/test/eo/org/eolang/cage-tests.eo`, `eo-runtime/src/main/java/org/eolang/PhTracedEnclosure.java`, `eo-runtime/src/test/java/EOorg/EOeolang/EOcageTest.java`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
@maxonfjvipon maybe, while you are at it, it's better to change the design to this one:

```
[] > cage 
  [o] > new
    [o] > encage
    [] > it # this new "method"
```

Then, we can use it like this:

```
[] > foo
  [x] > encage
    print x > @

cage.new foo > c
c.it.encage "Hello, world!"
```

This snippet won't work in your current implementation, due to a conflict between `foo.encage` and your `encage`.

**Comment by maxonfjvipon** [comment]
@yegor256 what is `it` for? Seems like something redundant

**Comment by yegor256** [comment]
@maxonfjvipon how do we get the object out of a cage?

**Comment by maxonfjvipon** [comment]
@yegor256 
```
seq
  *
    cage.new x > c
    c # x is got here
```

**Comment by yegor256** [comment]
@maxonfjvipon let's rename `object` to `it` and that's it

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
