### PR TITLE
test(#1673): Add tests for `DcsEachWithoutTransitive` class

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
Add tests for `DcsEachWithoutTransitive` class.

Closes: #1673

### CODE REVIEW

**Review by Graur — APPROVED** [review]

**Comment by volodya-lombrozo** [comment]
@yegor256 Reminder

**Comment by yegor256** [comment]
@rultor merge

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you merge that changes, please?

**Comment by yegor256** [comment]
@rultor merge

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you try to merge it again, please?

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
