### PR TITLE
feat(#3251): introduced `e`, `pi`, `numbers` and `integral` objects from `eo-math`

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Ref: #3251

---

## PR-Codex overview
This PR updates the EOmath package in the EO runtime, adding trigonometric functions and constants.

### Detailed summary
- Added `EOangle$EOsin` and `EOangle$EOcos` classes for sine and cosine functions
- Added `pi.eo` file with the PI constant
- Added `e.eo` file with the Euler's number constant

> The following files were skipped due to too many changes: `eo-runtime/src/main/eo/org/eolang/math/numbers.eo`, `eo-runtime/src/main/eo/org/eolang/math/integral.eo`, `eo-runtime/src/test/eo/org/eolang/math/numbers-tests.eo`, `eo-runtime/src/main/eo/org/eolang/math/angle.eo`, `eo-runtime/src/test/eo/org/eolang/math/integral-tests.eo`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Review by yegor256 — APPROVED** [review]
@maxonfjvipon perfect!

**Comment by 0crat** [comment]
@maxonfjvipon Thanks for your contribution! Your reward is +4 points: +4 base, +16 for 670 hits-of-code (max), -8 for exceeding 200 hits, -16 for exceeding 800 hits, -4 for only 3 comments. We appreciate your substantial code addition, but remember to [balance](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) quantity with quality and encourage more review interactions. Your running balance is [+49](https://www.eolang.org/zerocracy/objectionary-vitals.html). Keep up the good work!

**Comment by 0crat** [comment]
@yegor256 Thanks for the review! You've earned +4 points for this: +4 as a basis; +6 for the 670 hits-of-code that you reviewed; -10 for very few (4) comments; +3 to give you at least something.  Your running balance is [+107](https://www.eolang.org/zerocracy/objectionary-vitals.html).

**Pull request merged**
