### PR TITLE
feat(#1784): remove `@Parameter` annotation from `ResolveMojo`

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
Remove `@Parameter` annotation from `ResolveMojo`.

Closes: #1784

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
@mximp, have a look, please.

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you merge, please?

**Comment by yegor256** [comment]
@volodya-lombrozo no tests? How did you reproduce the problem? How are you sure that it's fixed?

**Comment by volodya-lombrozo** [comment]
@yegor256 Done. Could you check, again, please? If you will return the next annotation back, integration test will fail. 
```java
@Parameter(property = "eo.transitiveDependencies", required = true, defaultValue = "true")
```

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
