### PR TITLE
#652 - fix array.eq and add more tests

### PR DESCRIPTION
**Pull request by Graur**
@yegor256 redo `array.eq` by `goto` and `reduci` objects. Please, have a look

### CODE REVIEW

**Comment by yegor256** [comment]
@Graur we discourage our users to use of "gray" objects. It would be a bad example for them if we use "goto" in our library. Is it possible to do this without goto?

**Comment by Graur** [comment]
@yegor256 Sure, I can remove it. Just tried to find an alternative of `return` from the cycle, to not to compare arrays completely when an element is not equal to another.

**Comment by Graur** [comment]
@yegor256 done. Please, have a look

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
