### PR TITLE
fix(#2802): single quotes instead of trippled

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Ref: #2802 

---

## PR-Codex overview
This PR focuses on making changes to several YAML files and XSL templates. 

### Detailed summary
- Updated string values in YAML files.
- Removed unnecessary lines in YAML files.
- Updated string values in XSL templates.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@yegor256 please have a look

**Comment by maxonfjvipon** [comment]
@yegor256 please have a look

**Comment by maxonfjvipon** [comment]
@yegor256 please have a look

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
