### PR TITLE
feat(#3251): move `eo-files` to `eo-runtime`

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Ref: #3251 

What's done:
- Introduced `file` object
- Introduced `dir` object
- Introduced `tmpdir` object
- Introduced `getenv` object
- Object `uname` is renamed to `os`
- Fixed `unescapedJavaString` function so it works correctly

---

## PR-Codex overview
This PR updates the project to use `.typos.toml` config file, renames classes, improves file structure, and refactors environment-related objects.

### Detailed summary
- Updated workflow to use `.typos.toml` config file
- Renamed classes for consistency
- Improved file structure in `EOorg.EOeolang.EOfs` package
- Refactored environment-related objects for clarity

> The following files were skipped due to too many changes: `eo-runtime/src/main/java/EOorg/EOeolang/EOfs/EOfile$EOsize.java`, `eo-runtime/src/main/java/EOorg/EOeolang/EOfs/EOfile$EOexists.java`, `eo-runtime/src/main/java/EOorg/EOeolang/EOfs/EOfile$EOis_directory.java`, `eo-runtime/src/main/java/EOorg/EOeolang/EOfs/EOdir$EOmade$EOmkdir.java`, `eo-runtime/src/main/java/EOorg/EOeolang/EOfs/EOfile$EOtouched$EOtouch.java`, `eo-runtime/src/main/java/EOorg/EOeolang/EOfs/EOfile$EOdeleted$EOdelete.java`, `eo-runtime/src/main/java/EOorg/EOeolang/EOsys/EOgetenv.java`, `.codacy.yml`, `eo-runtime/src/main/java/EOorg/EOeolang/EOfs/EOfile$EOresolved$EOresolve.java`, `eo-runtime/src/main/java/EOorg/EOeolang/EOfs/EOfile$EOmoved$EOmove.java`, `eo-runtime/src/main/java/EOorg/EOeolang/EOfs/EOdir$EOtmpfile$EOtouch.java`, `eo-runtime/src/test/java/EOorg/EOeolang/EOfs/EOfileTest.java`, `eo-runtime/src/main/java/EOorg/EOeolang/EOfs/EOfile$EOopen$EOprocess_file.java`, `eo-runtime/src/main/java/EOorg/EOeolang/EOfs/EOfile$EOopen$EOfile_stream$EOread$EOread_bytes.java`, `eo-runtime/src/main/java/EOorg/EOeolang/EOfs/EOfile$EOopen$EOfile_stream$EOwrite$EOwritten_bytes.java`, `eo-runtime/src/main/eo/org/eolang/fs/tmpdir.eo`, `eo-runtime/src/test/eo/org/eolang/fs/dir-test.eo`, `eo-runtime/src/main/java/EOorg/EOeolang/EOfs/EOdir$EOwalk.java`, `eo-runtime/src/main/eo/org/eolang/fs/dir.eo`, `eo-runtime/src/main/java/EOorg/EOeolang/EOfs/Files.java`, `eo-runtime/src/test/java/EOorg/EOeolang/EOfs/FilesTest.java`, `eo-runtime/src/test/eo/org/eolang/fs/file-tests.eo`, `eo-runtime/src/main/eo/org/eolang/fs/file.eo`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@maxonfjvipon very good job, thanks!

**Comment by 0crat** [comment]
@maxonfjvipon 🎉 Awesome job on your contribution! You've snagged 5 points this time. We love your enthusiasm, but remember: less code can be more effective. Next time, try to trim it down a bit and don't forget to get a code review. Keep those comments coming too! Your [speed vs quality](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) balance is crucial. Your total score is now a cool [200 points](https://www.eolang.org/zerocracy/objectionary-vitals.html). Keep up the great work! 💪

**Pull request merged**
