### PR TITLE
Close JsonReader correctly

### LINKED ISSUE #1961: DcsDepgraph.java:195-197: Close `JsonReader` object in...
The puzzle `1897-5e29a33b` from #1897 has to be resolved: 

https://github.com/objectionary/eo/blob/8e82e617d5de10dc7816327d416acff19269cda0/eo-maven-plugin/src/main/java/org/eolang/maven/dependencies/DcsDepgraph.java#L195-L197

The puzzle was created by Max Petrov on 31-Mar-23. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

### PR DESCRIPTION
**Pull request by mximp**
Closes #1961.

### CODE REVIEW

**Comment by mximp** [comment]
@volodya-lombrozo please review

**Review by volodya-lombrozo — APPROVED** [review]

**Comment by mximp** [comment]
@yegor256 can you please re-trigger tests

**Comment by yegor256** [comment]
@rultor merge

**Comment by mximp** [comment]
@yegor256 this is flaky issue - please try again.

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
