### PR TITLE
fix(#3357): moved snippet test to integration testing

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Ref: #3357

---

## PR-Codex overview
This PR updates test files and configurations, changes aliases in a list, and refactors test classes. 

### Detailed summary
- Excludes a test file and updates test classes
- Changes aliases in a list
- Updates configurations in test files

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by yegor256** [comment]
@rultor merge

**Comment by maxonfjvipon** [comment]
@yegor256 let's try again, should work

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@maxonfjvipon hurray! thanks!

**Comment by 0crat** [comment]
@maxonfjvipon Hey there! 👋 Great job on your contribution! You've earned +4 points for this one. Here's the breakdown: +4 base points, +7 for your 142 [hits-of-code](https://www.yegor256.com/2014/11/14/hits-of-code.html) (nice work!), but -16 for missing the code review (oops!). We bumped it up by 9 to keep you motivated. Remember, code reviews are crucial - they can boost your points and improve code quality. [Keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) the contributions coming! Your current balance is [+68](https://www.eolang.org/zerocracy/objectionary-vitals.html). Let's aim for more points next time! 💪

**Pull request merged**
