### PR TITLE
Prohibit trailing spaces

### LINKED ISSUE #1881: forbid trailing spaces in comments
Try to add `eo-parser/src/test/resources/org/eolang/parser/typos/trailing-spaces.yaml` file and see what happens (make sure you have a space at the end of the line):

```
line: 1
eo: |
  # This is a comment with a space at the end of the line 
  [] > x
```

Such spaces must be prohibited by the syntax in `Program.g4`.

### PR DESCRIPTION
**Pull request by mximp**
Closes #1881

### CODE REVIEW

**Comment by mximp** [comment]
@yegor256 please review and merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@volodya-lombrozo check the stacktrace above, pls

**Comment by yegor256** [comment]
@rultor merge

**Comment by mximp** [comment]
@volodya-lombrozo do you know what is the issue here?

**Comment by yegor256** [comment]
@rultor merge

**Comment by mximp** [comment]
@yegor256 can you please try again

**Pull request merged**
