### PR TITLE
feat(#3251): added `sprintf` and `list` to `eo-runtime`

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Ref: #3251

---

## PR-Codex overview
This PR updates package names, adds new objects, and includes licensing info. 

### Detailed summary
- Renamed `EOorg.EOeolang.EOio` to `EOorg.EOeolang.EOtxt`
- Added `@XmirObject` annotations
- Updated exclusion paths in `codacy.yml`
- Modified `toPhi` method in `Data.java`
- Updated licensing info in package-info files

> The following files were skipped due to too many changes: `eo-runtime/src/test/java/EOorg/EOeolang/EOtxt/EOsprintfTest.java`, `eo-runtime/src/main/java/EOorg/EOeolang/EOtxt/EOsprintf.java`, `eo-runtime/src/main/eo/org/eolang/structs/list.eo`, `eo-runtime/src/test/eo/org/eolang/structs/list-tests.eo`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Review by yegor256 — APPROVED** [review]
LGTM

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
@yegor256 Thanks for the review! You've earned +72 points for this (+25 as a basis, +40 for 1301 hits-of-code, +7 for 7 comments).  Your running balance is [+25](https://www.eolang.org/zerocracy/objectionary.html).

**Comment by 0crat** [comment]
@maxonfjvipon Thanks for the contribution! You've earned +53 points for this (+20 as a basis, +40 for 1301 hits-of-code, -7 for 7 comments). Please, [keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) them coming. Your running balance is [+60](https://www.eolang.org/zerocracy/objectionary.html).

**Pull request merged**
