### PR TITLE
2315 return string

### LINKED ISSUE #2315: EOrust.java:253-255: Implement handling of String...
The puzzle `2283-ddadafec` from #2283 has to be resolved: 

https://github.com/objectionary/eo/blob/44fe52e47b5db6b2a3accb5ae59bc8b92b058b23/eo-runtime/src/main/java/EOorg/EOeolang/EOrust.java#L253-L255

The puzzle was created by @rultor on 25-Jul-23. 

Estimate: 45 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

### PR DESCRIPTION
**Pull request by levBagryansky**
Closes #2315 

---

### Focus of this PR:
This PR focuses on adding support for string values in the EO enum in the Rust code.

### Detailed summary:
- Added support for string values in the EO enum in the Rust code.
- Modified the `EO::EOString` variant to store the content as a byte vector.
- Updated the `EO::EOString` variant to convert the content string into bytes and store it in the byte vector.
- Modified the `EO::EOString` variant to create a new byte vector with the length of the content string plus one, and copy the content bytes into it.
- Updated the `EO::EOString` variant to set the first byte of the byte vector to `3`.
- Modified the `EO::EOString` variant to return the byte vector as the result.
- Added a new test case in the Rust tests to check if the `EOString` variant returns the expected content string.
- Updated the Java code to handle the new `EO::EOString` variant by converting the content bytes back to a string using UTF-8 encoding.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by levBagryansky** [comment]
@Graur please check

**Comment by levBagryansky** [comment]
@Graur please have a look

**Review by Graur — APPROVED** [review]
@levBagryansky Good one

**Comment by levBagryansky** [comment]
@yegor256 could you please merge these changes?

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
