### PR TITLE
feat(#2206): Remove AccessDenied catch from TranspileMojo

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
Try to remove AccessDenied exception catch from TranspileMojo. I close the puzzle because it seems that we don't have the problem anymore and all PR checks don't reveal the problem with AccessDenied exception.

Closes: #2206

---

## PR-Codex overview
This PR focuses on fixing an issue with file deletion in the TranspileMojo class. The AccessDeniedException catch block is removed and a warning is logged instead.

### Detailed summary
- Removed the catch block for AccessDeniedException in the cleanUpClasses method of TranspileMojo class.
- Logging a warning instead of handling the exception.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
I'm trying to reproduce the bug with AccessDenied in that PR.

**Comment by volodya-lombrozo** [comment]
@Graur Could you take a look, please?

**Review by Graur — COMMENTED** [review]
@volodya-lombrozo Is it worthwhile to write a test to verify the occurrence of this error?

**Comment by volodya-lombrozo** [comment]
@Graur Actually, we added catch (AccessDeniedException ex) to ensure all the tests pass (we swallowed the exception because the tests were failing). Now, all the tests are passing, so we already have all the necessary tests in place which show that everything is 'Ok'

**Review by Graur — APPROVED** [review]

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you merge that changes, please?

**Comment by volodya-lombrozo** [comment]
@yegor256 Reminder

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
