### PR TITLE
Jdk18

### LINKED ISSUE #992: Build error with -Werror
OpenJDK 18 on macOS/aarch64 generates build fatal warnings "non-transient instance field of a serializable class declared with a non-serializable type" due to some classes do not implement `Serializable` interface.

Classes/interfaces that must implement `Serializable`:
 * interface `org.eolang.Phi`
 * all generated classes extending `org.eolang.PhDefault`, also these classes must provide `serialVersionUID`.

### PR DESCRIPTION
**Pull request by kerelape**
Closes #992

### CODE REVIEW

**Comment by yegor256** [comment]
@rultor merge

**Comment by Graur** [comment]
@yegor256 @kerelape @MikhailLipanin this is the same error as in #1136

**Comment by mximp** [comment]
@kerelape is there anything to fix here?

**Comment by kerelape** [comment]
@Graur @mximp can you run the checks again so I see the logs, please?

**Comment by Graur** [comment]
@kerelape You can push a new commit to your branch

**Comment by mximp** [comment]
replaced by https://github.com/objectionary/eo/pull/1707

**Pull request closed without merging**
