### PR TITLE
fix(#3483): delta application

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Closes: #3483 
Closes: #3517 
Closes: #3494

### CODE REVIEW

**Comment by yegor256** [comment]
@maxonfjvipon thanks!

**Comment by yegor256** [comment]
@rultor release, tag is `0.43.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.43.0`

**Comment by 0crat** [comment]
@maxonfjvipon Thanks for your contribution! Here's the breakdown of your +4 points: +4 base, -8 for exceeding 200 hits-of-code (1305), -16 for surpassing 800 hits-of-code, -16 for no code review, -16 for lack of reviewer comments, and +56 adjustment to meet the minimum reward. While the size of your contribution was substantial, remember that our policy values [quality over quantity](https://www.yegor256.com/2018/03/06/speed-vs-quality.html). For future submissions, aim for smaller, focused changes and encourage code reviews to maximize your points. Your current balance is [+20](https://www.eolang.org/zerocracy/objectionary-vitals.html). Keep up the good work!

**Pull request merged**
