### PR TITLE
fix(#3169): decapitalize auto named objects on converting to phi

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Closes: #3169

---

## PR-Codex overview
This PR adds licensing information and updates XML files in the project. 

### Detailed summary
- Added MIT License to YAML and XSL files
- Updated XML files with licensing info
- Modified XSL files for XML transformation
- Updated Java file imports and variables

> The following files were skipped due to too many changes: `eo-maven-plugin/src/test/resources/org/eolang/maven/packs/decapitalize-auto-named.yaml`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
@maxonfjvipon why can't we just auto-generate names like `attribute-at-XXX` where `XXX` is the number of the line. Later, we can introduce a check that would prohibit programmers from giving similar names to their attributes, _if_ there are conflicts.

**Comment by maxonfjvipon** [comment]
@yegor256 we already have check that checks if there are more than one objects with the same name, so imagine:
```
[] > obj
  x > y
    [] >>
  5 > attribute-at-3
```
Programmer writes the code and expects it works because why not? But it fails on compilation because of the name conflict. Usability? I don't think so.
I believe it's quite strong rule to prohibit names started with capital letter and use such names on auto-generation. Because there's no any possible way to get a conflict in such case.
So my suggestion is to stick with current implementation. What's your decision?

**Comment by maxonfjvipon** [comment]
@yegor256 WDYT?

**Comment by maxonfjvipon** [comment]
@yegor256 maybe you're right

**Comment by yegor256** [comment]
@maxonfjvipon later we can make our game-generator more powerful, so that it avoids conflicts. But making names that don't follow the grammar of the language -- this definitely is a wrong idea.

**Pull request closed without merging**
