### PR TITLE
feat(#2287): Increase outdated time for already optimized xmir

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
Increase outdated time for already optimized xmir in `OptimizeMojoTest.optimizeIfExpired`.

Closes: #2287

---

### Detailed summary
- In `ForeignTojo.java`, the comment was updated to clarify that the check is for optimization not being already done.
- In `OptimizeMojo.java`, the `shouldPass` method was simplified by removing unnecessary variable assignment.
- In `OptimizeMojoTest.java`, the calculation of the `old` variable was updated to use `System.currentTimeMillis()` instead of calculating it based on the current time.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
@levBagryansky Could you take a look, please?

**Review by levBagryansky — APPROVED** [review]
@volodya-lombrozo Looks good to me, nice test.

**Comment by levBagryansky** [comment]
@yegor256 please take a look.

**Comment by volodya-lombrozo** [comment]
@yegor256 Reminder

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
