### PR TITLE
feat(#2046): Fix the bug that prevents the removal of generated files

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
Disable the removal of generated `java` files. The puzzle was added to investigate why we need to clean generated `java` files during the transpilation phase.
For more info see `TranspileMojo` class.

Closes: #2046

---

## PR-Codex overview
This PR adds a todo to enable removing transpiled files in the eo-maven-plugin. 

### Detailed summary
- Added a todo to enable removing transpiled files in the eo-maven-plugin.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
@mximp Could you have a look, please?

**Comment by mximp** [comment]
@volodya-lombrozo FYI the generated files present for tests in `generated-tests-sources`. So it's still unclear why it's missing for `generated-sources`

**Comment by volodya-lombrozo** [comment]
@mximp I don't clearly understand what you mean. I've just checked the directories `generated-test-sources` and `generated-sources`  and both of them contain `java` classes.

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you merge that changes, please?

**Comment by mximp** [comment]
> @mximp I don't clearly understand what you mean. I've just checked the directories `generated-test-sources` and `generated-sources` and both of them contain `java` classes.

That was my comment to root cause of the issue and your fix. If we remove Java sources for transpiled objects why java sources still presents in `generated-test-sources`?

**Comment by volodya-lombrozo** [comment]
@mximp Yea, the feature itself is quite questionable.

**Comment by mximp** [comment]
@yegor256 can you please merge this. It's holding release.

**Comment by volodya-lombrozo** [comment]
@yegor256 reminder

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
