### PR TITLE
feat(#2120): Enable synthetic refs transformation

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
Enable `synthetic-references.xsl` transformation. Since `synthetic-references.xsl` creates new objects, we have to determine new references for that objects by using the `add-refs.xsl` transformation,  which was also added after the `synthetic-references.xsl` transformation.

Also I disabled `correctly-handles-same-name-attrs` test which is rather weird and filed with `StackOverflowException`. 

Closes: #2120

---

## PR-Codex overview
This PR focuses on optimizing and refactoring code. 

### Detailed summary
- Changed file path in `OptimizeMojoTest.java`
- Updated XPath expression in `float-abstracts.yaml`
- Updated XSLT expression in `broken-refs.xsl`
- Added comments and todo in `AssembleMojoTest.java`
- Updated XSLT expressions in `synthetic-references.xsl`
- Updated EO code in `runtime-tests.eo`
- Added comments and todo in `ParsingTrain.java`
- Updated file order in `ParsingTrain.java`
- Updated XSLT expressions in `add-refs.xsl`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
@Graur Could you have a look, please?

**Comment by volodya-lombrozo** [comment]
@Graur It seems that I've fixed all mistakes. Could you take a look, please?

**Review by Graur — APPROVED** [review]
@volodya-lombrozo Looks good to me
@yegor256 Could you please have a look?

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you take a look, please?

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
