### PR TITLE
introduced eo-test module

### PR DESCRIPTION
**Pull request by MikhailLipanin**
`CheckXSL` transfered to `eo`/`eo-test` module

#1008

### CODE REVIEW

**Comment by yegor256** [comment]
@rultor merge

**Comment by MikhailLipanin** [comment]
@yegor256 Some classes from `eo-parser`: `Syntax`, `ParsingTrain`, are used in `eo-maven-plugin` and in `CheckPack` class, that will be moved to `eo-test` module.
So it will be a cycle in dependencies:
`eo-maven-plugin` --> `eo-parser`
___________________--> `eo-runtime`
___________________--> `eo-test` (used by `CheckPack`)
|
`eo-parser`-->`eo-test` (used by `CheckPack`)
|
`eo-test`-->`eo-parser` (used by `ParsingTrain`, `Syntax`)

So, maybe we can move `ParsingTrain` and `Syntax` classes to this new `eo-test` module, and we can rename 
this module to `eo-util` for example.

Or it can be done in other way?

**Comment by yegor256** [comment]
@MikhailLipanin let's make `train` an argument of `CheckPack`

**Comment by MikhailLipanin** [comment]
@yegor256 but what about `Syntax.java` ?

**Comment by yegor256** [comment]
@MikhailLipanin I think it's not necessary anymore, since we added jucs and xax modules

**Pull request closed without merging**
