### PR TITLE
Update qulice to 0.22.2

### LINKED ISSUE #2937: upgrade qulice to 0.22.2
Let's upgrade it to 0.22.2: there are many fixes to be made, but they are not hard to make.

### PR DESCRIPTION
**Pull request by c71n93**
Closes #2937

---

## PR-Codex overview
This PR updates method names, adds assertion messages, improves exception handling, and enhances dependencies in various Maven plugin test files.

### Detailed summary
- Renamed `key()` method to `getKey()`
- Added assertion messages in multiple test files
- Improved exception handling with `@SuppressWarnings("PMD.CognitiveComplexity")`
- Enhanced dependencies by updating versions

> The following files were skipped due to too many changes: `eo-maven-plugin/src/test/java/org/eolang/maven/CleanMojoTest.java`, `eo-maven-plugin/src/test/java/org/eolang/maven/hash/ChRemoteTest.java`, `eo-maven-plugin/src/test/java/org/eolang/maven/hash/ChTextTest.java`, `eo-maven-plugin/src/main/java/org/eolang/maven/hash/ChPattern.java`, `eo-maven-plugin/src/test/java/org/eolang/maven/objectionary/OyRemoteTest.java`, `eo-maven-plugin/src/test/java/org/eolang/maven/util/FileHashTest.java`, `eo-maven-plugin/src/test/java/org/eolang/maven/MarkMojoTest.java`, `eo-maven-plugin/src/main/java/org/eolang/maven/Moja.java`, `eo-maven-plugin/src/test/java/org/eolang/maven/tojos/ForeignTojosTest.java`, `eo-parser/src/test/java/org/eolang/parser/ObjectsTest.java`, `eo-maven-plugin/src/test/java/org/eolang/maven/rust/NamesTest.java`, `eo-maven-plugin/src/main/java/org/eolang/maven/VerifyMojo.java`, `eo-maven-plugin/src/test/java/org/eolang/maven/objectionary/OyHomeTest.java`, `eo-maven-plugin/src/test/java/org/eolang/maven/CopyMojoTest.java`, `eo-maven-plugin/src/test/java/org/eolang/maven/RegisterMojoTest.java`, `eo-maven-plugin/src/test/java/org/eolang/maven/objectionary/OyFilesystemTest.java`, `eo-maven-plugin/src/test/java/org/eolang/maven/dependencies/DcsEachWithoutTransitiveTest.java`, `eo-maven-plugin/src/main/java/org/eolang/maven/ShakeMojo.java`, `eo-maven-plugin/src/main/java/org/eolang/maven/OptimizationTask.java`, `eo-maven-plugin/src/main/java/org/eolang/maven/OptimizeMojo.java`, `eo-parser/src/main/java/org/eolang/parser/XePhiListener.java`, `eo-maven-plugin/src/main/java/org/eolang/maven/tojos/TranspiledTojos.java`, `eo-maven-plugin/src/test/java/org/eolang/maven/objectionary/ObjectsIndexTest.java`, `eo-maven-plugin/src/test/java/org/eolang/maven/ParseMojoTest.java`, `eo-maven-plugin/src/test/java/org/eolang/maven/footprint/FtDefaultTest.java`, `eo-maven-plugin/src/main/java/org/eolang/maven/tojos/PlacedTojos.java`, `eo-maven-plugin/src/main/java/org/eolang/maven/UnplaceMojo.java`, `eo-maven-plugin/src/test/java/org/eolang/maven/objectionary/OyIndexedTest.java`, `eo-parser/src/test/java/org/eolang/parser/ParsingTrainTest.java`, `eo-parser/src/test/java/org/eolang/parser/EoIndentLexerTest.java`, `eo-maven-plugin/src/test/java/org/eolang/maven/PullMojoTest.java`, `eo-maven-plugin/src/test/java/org/eolang/maven/BinarizeMojoTest.java`, `eo-maven-plugin/src/test/java/org/eolang/maven/objectionary/OyFallbackSwapTest.java`, `eo-maven-plugin/src/test/java/org/eolang/maven/tojos/TranspiledTojosTest.java`, `eo-maven-plugin/src/test/java/org/eolang/maven/footprint/FtCachedTest.java`, `eo-parser/src/test/java/org/eolang/parser/StUnhexTest.java`, `eo-maven-plugin/src/test/java/org/eolang/maven/objectionary/OyFallbackTest.java`, `eo-maven-plugin/src/main/java/org/eolang/maven/tojos/PlacedTojo.java`, `eo-maven-plugin/src/main/java/org/eolang/maven/SafeMojo.java`, `eo-maven-plugin/src/test/java/org/eolang/maven/SodgMojoTest.java`, `eo-maven-plugin/src/test/java/org/eolang/maven/util/HmBaseTest.java`, `eo-maven-plugin/src/test/java/org/eolang/maven/UnplaceMojoTest.java`, `eo-maven-plugin/src/test/java/org/eolang/maven/BinarizeParseTest.java`, `eo-maven-plugin/src/test/java/org/eolang/maven/OptimizeMojoTest.java`, `eo-parser/src/test/java/org/eolang/parser/EoSyntaxTest.java`, `eo-parser/src/main/java/org/eolang/parser/XeEoListener.java`, `eo-maven-plugin/src/test/java/org/eolang/maven/ResolveMojoTest.java`, `eo-maven-plugin/src/main/java/org/eolang/maven/tojos/ForeignTojos.java`, `eo-maven-plugin/src/test/java/org/eolang/maven/TranspileMojoTest.java`, `eo-maven-plugin/src/test/java/org/eolang/maven/PlaceMojoTest.java`, `eo-maven-plugin/src/main/java/org/eolang/maven/tojos/ForeignTojo.java`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by yegor256** [comment]
@maxonfjvipon let's merge this one until it expires?

**Comment by maxonfjvipon** [comment]
@yegor256 @c71n93 let's merge master to it first and restart CI again

**Comment by maxonfjvipon** [comment]
@yegor256 or, since there's no conflicts, let's merge

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
