### PR TITLE
feat(#2340): Remove shouldPass method from OptimizeMojo

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
Remove `OptimizeMojo.shouldPass` method.

Closes: #2340

---

### Detailed summary

- The focus of this PR is to refactor the `OptimizeMojo` class in the `eo-maven-plugin` module.
- The notable changes in this PR include:
  - Refactoring the code to improve readability and maintainability.
  - Reorganizing the code to optimize the XML document in a more efficient way.
  - Removing the `shouldPass` method and its related logic.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Review by maxonfjvipon — APPROVED** [review]
@volodya-lombrozo LGTM! Thanks

**Comment by volodya-lombrozo** [comment]
@yegor256 Reminder

**Comment by volodya-lombrozo** [comment]
@yegor256 Reminder

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
