### PR TITLE
2974 enable try tests

### LINKED ISSUE #2974: try-tests.eo:30-32: Enable try tests. The tests were...
The puzzle `2931-a76712ab` from #2931 has to be resolved: 

https://github.com/objectionary/eo/blob/446d62f268ac3224a2927fccfba20a7f444576ce/eo-runtime/src/test/eo/org/eolang/try-tests.eo#L30-L32

The puzzle was created by rultor on 18-Mar-24. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

### PR DESCRIPTION
**Pull request by levBagryansky**
closes #2974 
I do not know why `3` was there

---

## PR-Codex overview
This PR focuses on enabling `try` tests in the `eo-runtime` module by updating the test cases affected by changes in the `rho` attribute immutability.

### Detailed summary
- Enabled `try` tests in `try-tests.eo`.
- Updated test cases `simple-division-by-zero` and `try-memory-update`.
- Modified test case `try-memory-update-catch`.
- Adjusted values and assertions in the tests.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by levBagryansky** [comment]
@maxonfjvipon please check

**Review by maxonfjvipon — APPROVED** [review]
@levBagryansky that's really strange, because this 3 was there since the test was introduced

**Comment by levBagryansky** [comment]
@yegor256 please take a look

**Comment by yegor256** [comment]
@rultor merge

**Comment by maxonfjvipon** [comment]
@rultor status

**Pull request merged**
