### PR TITLE
Refactoring: Foreign Tojos

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
Refactoring of foreign tojos usage.
It is only the first step of refactoring foreign tojos: #1969. See puzzles to check next steps.

Similar to: https://github.com/objectionary/eo/pull/1929
Blocked by: https://github.com/objectionary/eo/pull/1942

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
@Graur Could you have a look, please?

**Review by Graur — APPROVED** [review]
@volodya-lombrozo Looks good to me
@yegor256 Please, have a look

**Comment by volodya-lombrozo** [comment]
@yegor256 Reminder

**Comment by yegor256** [comment]
@rultor merge

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you merge it again, please?

**Comment by yegor256** [comment]
@rultor merge

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you merge that changes, please?

**Comment by yegor256** [comment]
@rultor merge

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you merge that again, please?

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
