### PR TITLE
#3058: Fixed access modifier in EOorg/EOeolang/

### LINKED ISSUE #3058: We can speed up `switch` object
Current implementation of `switch` object uses `tuple.at` object which is convenient for retrieval object by index but quite heavy.
Instead we can implement some recursive algorithm that can just do `cases.head` and `cases.tail` instead. Something similar to #3048 but in EO

### PR DESCRIPTION
**Pull request by levBagryansky**
Closes #3058

---

## PR-Codex overview
This PR adds a test to ensure all EO.. classes are public in the EOorg.EOeolang package.

### Detailed summary
- Added a test class `EoClassesArePublicTest` to check public access for EO.. classes
- Included license information in the test file
- Imported necessary classes for the test
- Implemented logic to filter and check public access for EO.. classes

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by levBagryansky** [comment]
@maxonfjvipon Please review

**Review by maxonfjvipon — APPROVED** [review]

**Comment by levBagryansky** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
@levBagryansky isn't it easier to use Reflection for this, in runtime? When unit tests in the eo-runtime package are executed, all Java classes are parsed and available in classpath. Just search for all classes in the package and check their access modifiers.

**Comment by levBagryansky** [comment]
@yegor256 I tried to use `Dataized` in this script and get the error 
```
[ERROR] /home/tardis3/eo/eo-runtime/src/test/groovy/check-eo-classes-are-public.groovy: 29: unable to resolve class org.eolang.Dataized
[ERROR]  @ line 29, column 1.
[ERROR]    import org.eolang.Dataized
[ERROR]   
```
Looks like the main issue is how to use foreign dependencies in `groovy-maven-plugin`

**Comment by yegor256** [comment]
@levBagryansky that's what I'm saying. You don't need Groovy for this task. Just create a normal unit test in the eo-runtime: it should scan the classpath, find all classes in the `EOorg.EOeolang` package, and check their access modifiers (through reflection). Should be easy. Most probably you should use this lib: https://github.com/ronmamo/reflections

**Comment by levBagryansky** [comment]
@yegor256 please check. For some reason reflections did not counted all classes, so I used guava here. Here we check 827 classes

**Comment by levBagryansky** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
