### PR TITLE
refactor(#2281): simplify VersionsMojo

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
Refactor VersionsMojo in order to make it more readable.

History:
- refactor(#2281): Split the long method on several small methods
- refactor(#2281): Simplify methods in VersionsMojo

Related to #2281

---

## PR-Codex overview
This PR focuses on replacing versions with corresponding hashes in an XML document. 

### Detailed summary
- Added imports for `FileNotFoundException`, `IOException`, and `Path`
- Removed unused imports
- Refactored code to replace versions with hashes in XML documents
- Added new methods `replace()` and `versions()` to handle version replacement and retrieval
- Added new method `isSemver()` to check if a version is a semver version

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
@maxonfjvipon What do you think?

**Comment by maxonfjvipon** [comment]
@volodya-lombrozo this code is ok, but I like the previous code more because it's more object oriented (less procedure code, less static methods, more ladders :)). It's not difficult for me to read/write/understand such code, but if it is for you - this refactoring make sense. If you think that this refactoring is really needed and brings a lot of benefits - let it be and let's merge it

**Review by maxonfjvipon — COMMENTED** [review]
@volodya-lombrozo this code is ok, but I like the previous code more because it's more object oriented (less procedure code, less static methods, more ladders :)). It's not difficult for me to read/write/understand such code, but if it is for you - this refactoring make sense. If you think that this refactoring is really needed and brings a lot of benefits - let it be and let's merge it

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you merge that changes, please?

**Comment by volodya-lombrozo** [comment]
@yegor256 Reminder

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
