### PR TITLE
fix(#2736): prohibit vertical method in scope

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Closes: #2736 

What's done:
- Prohibit using vertical methods in scopes
- Make `SnippetTestCase` use object from `eo-runtime`
- Fixed packs and tests

---

## PR-Codex overview
This PR focuses on code formatting and minor syntax changes. 

### Detailed summary
- Removed unnecessary parentheses in method calls
- Updated method calls to use dot notation instead of parentheses
- Added missing imports in a test file
- Removed unnecessary comments and TODOs
- Fixed indentation and formatting issues

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@yegor256 please have a look

**Comment by maxonfjvipon** [comment]
@yegor256 please have a look

**Comment by maxonfjvipon** [comment]
@yegor256 please have a look

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
