### PR TITLE
#1757 Removed transformation 0.0 to -0.0 and upgraded `float.eq` and `int.eq`

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Closes: #1757

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@Graur please take a look. Btw this PR solves [this](https://github.com/objectionary/eo-math/issues/104) ticket too

**Comment by maxonfjvipon** [comment]
@Graur please take a look. Btw this PR closes [this](https://github.com/objectionary/eo-math/issues/104) ticket too. it will no longer be relevant

**Review by Graur — APPROVED** [review]
@maxonfjvipon I like it, thanks!
@yegor256 Please, have a look at this updated implementation of `float.eq` and `int.eq`. All tests are stay green and we got rid of float's bad solution with `-0.0`

**Comment by Graur** [comment]
> @Graur please take a look. Btw this PR closes [this](https://github.com/objectionary/eo-math/issues/104) ticket too. it will no longer be relevant


@maxonfjvipon So, when this pull request will be merged I close this ticket too

**Comment by maxonfjvipon** [comment]
@yegor256 please take a look

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
