### PR TITLE
#1188 Expand QQ transformation

### PR DESCRIPTION
**Pull request by mximp**
implement #1188

### CODE REVIEW

**Comment by mximp** [comment]
@yegor256 please check.

**Comment by mximp** [comment]
> @mximp you have to add it to the `ParsingTrain`, otherwise it's not used

:) nice spot! I was totally excited by testing XSL.. thank you

**Comment by mximp** [comment]
@yegor256 fixed. Please check.

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
