### PR TITLE
fix(#2931): `\rho` refers to nearest object

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Ref: #2931 

---

## PR-Codex overview
This PR improves data handling in EO runtime. It adds `asString()` method to `Bytes` and updates `Dataized` to use `BytesOf`. Various classes now support `attach(byte[])` method for data manipulation.

### Detailed summary
- Added `asString()` method to `Bytes` for string conversion.
- Updated `Dataized` to use `BytesOf` for data conversion.
- Implemented `attach(byte[])` method in multiple classes for data manipulation.

> The following files were skipped due to too many changes: `eo-runtime/src/test/eo/org/eolang/cage-tests.eo`, `eo-runtime/src/main/java/org/eolang/Data.java`, `eo-runtime/src/main/java/org/eolang/PhData.java`, `eo-runtime/src/test/eo/org/eolang/seq-tests.eo`, `eo-runtime/src/main/java/org/eolang/PhDefault.java`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
