### PR TITLE
feat(#2131): Redundant Objects Clarification

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
I've added several tests that show the problem with redundant objects that actually might create some problems in the future transformations.

Closes: #2131 

---

## PR-Codex overview
This PR adds XSL files and test cases to optimize the EO code by removing redundant levels and objects.

### Detailed summary
- Added `abstracts-float-up.xsl` to optimize EO code by removing redundant level of abstract objects
- Added `remove-levels.xsl` to optimize EO code by removing redundant level of concrete objects
- Added test cases to optimize EO code by removing redundant levels and objects
- Removed redundant objects from the result code snippet in `redundant-levels.yaml` test case

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
@Graur Could you have a look, please?

**Review by Graur — APPROVED** [review]
@volodya-lombrozo Looks good
@yegor256 Please, have a look

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you merge that changes, please?

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
