### PR TITLE
test(#1366): Fix tests names and add `test-naming-conventions` plugin

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
I've added `test-naming-conventions` [plugin](https://github.com/volodya-lombrozo/test-naming-conventions/blob/main/src/main/java/com/github/lombrozo/testnames/ValidateMojo.java) and fixed all tests names in the project.

Closes: #1366

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
@mximp Can you take a look please? And if you like the [plugin](https://github.com/volodya-lombrozo/test-naming-conventions), please put the star, I'll be appreciated :)

**Comment by mximp** [comment]
@volodya-lombrozo So what is the general naming convention forced by the plugin?

**Review by mximp — APPROVED** [review]

**Comment by volodya-lombrozo** [comment]
@yegor256 Can you merge that changes, please?

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@volodya-lombrozo very good contribution, thanks!

**Pull request merged**
