### PR TITLE
feat(#2101): fix all flaky tests related to logging

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
I've added thread-safe implementation of logs capturing in tests. 

Closes: #2101

---

## PR-Codex overview
This PR adds a log capturing package to the Maven plugin. It includes a JUnit extension and a logger appender. The extension captures log messages during tests and the appender saves them to a log collector. 

### Detailed summary
- Added `CaptureLogs` annotation for tests.
- Added `Logs` class to collect logs.
- Added `CaptureLogsAppender` class to save logs to `Logs`.
- Added `CaptureLogsExtension` class to capture log messages during tests.

> The following files were skipped due to too many changes: `eo-maven-plugin/src/test/java/org/eolang/maven/LogFormatTest.java`, `eo-maven-plugin/src/test/java/org/eolang/maven/log/Logs.java`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
Blocked by #2097

**Comment by volodya-lombrozo** [comment]
@mximp Could you have a look, please?

**Review by mximp — APPROVED** [review]

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you merge that changes, please?

**Comment by volodya-lombrozo** [comment]
@yegor256 Reminder

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
