### PR TITLE
feat(#3092): snippet `phi` -> `unphi` test

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Closes: #3092 
Closes: #2955 
Closes: #2956 
Closes: #2957 
Closes: #2958 
Closes: #2959 
Closes: #2960

---

## PR-Codex overview
This PR updates dependencies, removes unused classes, refactors code for clarity, and enhances test coverage in the `org.eolang` package.

### Detailed summary
- Updated `farea` version to `0.0.17` in `pom.xml`
- Removed unused classes `EObytes`, `EOint`, `EOstring`
- Refactored `Data` class for clarity
- Enhanced `SnippetTestCase` test coverage with new tests and improved existing tests

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
@rultor merge

**Comment by maxonfjvipon** [comment]
@yegor256 please start merge one more time

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
