### PR TITLE
Updated requirements

### PR DESCRIPTION
**Pull request by levBagryansky**
Closes: #2003 

---

## PR-Codex overview
This PR adds Rust installation instructions to the README and updates the getting started guide.

### Detailed summary
- Added Rust with Cargo installation instructions to the README
- Updated the getting started guide to include Rust installation
- No other notable changes were made

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by levBagryansky** [comment]
@Graur please take a look

**Review by Graur — APPROVED** [review]
@levBagryansky Indeed we won't be able to run it without `Rust`
@yegor256 What do you think?

**Comment by levBagryansky** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
thanks

**Pull request merged**
