### PR TITLE
Add testing profiles(solves invoker-maven-plugin invocation when -DskipITs is set)

### PR DESCRIPTION
**Pull request by ArtemGet**
To achieve [this](https://github.com/objectionary/eo/issues/3696#issuecomment-2554040718) logic I added profiles as I mentioned in [comment](https://github.com/objectionary/eo/issues/3711#issuecomment-2558749735). 
Profile activates if corresponding property is set, so there are no need to rewrite any action scripts.
 I.E:
-DskipTests -> -PskipTests
-DskipITs -> -PskipITs
-DskipUTs -> -PskipUTs

(-PskipITs and PskipUTs is kind of useless, but i added them to uniformity with -PskipTests)

### CODE REVIEW

**Comment by yegor256** [comment]
@maxonfjvipon please, check this one

**Comment by maxonfjvipon** [comment]
@ArtemGet could you please also integrate these profiles into our CI builds (in `.github/workflow` directories) so we may see that they actually work as expected. The necessary builds are: `daily`, `mvn`, `qulice`, `integration`

**Comment by ArtemGet** [comment]
> @ArtemGet could you please also integrate these profiles into our CI builds
Sure.

**Comment by yegor256** [comment]
@ArtemGet please, read this: https://www.yegor256.com/2024/04/01/ping-me-please.html

**Comment by ArtemGet** [comment]
> @ArtemGet please, read this: https://www.yegor256.com/2024/04/01/ping-me-please.html

@yegor256 thanks, just did not want to bother before i make shure all job's logs is fine.

**Pull request merged**
