### PR TITLE
feat(#1320): Check `unplaced` attribute during `PlaceMojo` execution

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
Check `unplaced` attribute during `PlaceMojo` execution.
1. If `unplaced == false` -> No need to copy
2. if `unplaced == true` -> Perform copy

Closes: #1320

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
@mximp I'm not sure that I've understood the issue correctly. Could you check, please?

**Review by mximp — APPROVED** [review]

**Review by mximp — APPROVED** [review]

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you merge that changes, please?

**Comment by volodya-lombrozo** [comment]
@yegor256 Please, merge that changes. They block [that](https://github.com/objectionary/eo/pull/1903) PR.

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
