### PR TITLE
`text` and `sscanf` objects

### PR DESCRIPTION
**Pull request by Graur**
#777

### CODE REVIEW

**Comment by yegor256** [comment]
@Graur let's do `sscanf` instead.

**Comment by Graur** [comment]
@yegor256 Should `sscanf` apply all conversion specifiers as `sprintf` did?
e.g.
```
QQ.txt.sscanf
  "%d and %f"
  "5"
  "20.0"
```
return 
```
* 
  5
  20.0
```

**Comment by yegor256** [comment]
@Graur well..

```
QQ.txt.sscanf
  "%d and %f"
  "5 and 20.0"
```

return

```
* 
  5
  20.0
```

**Comment by yegor256** [comment]
@Graur yes, sure

**Comment by Graur** [comment]
@yegor256 Please, have a look. It's the first implementation of `sscanf` object.

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
