### PR TITLE
fix(#2216): enable runtime test

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Closes: #2216 

---

## PR-Codex overview
This PR focuses on enabling the 'correctly-handles-same-name-attrs' test and improving its error messages. 

### Detailed summary
- Enabled the 'correctly-handles-same-name-attrs' test.
- Reorganized the test to make it more understandable.
- Improved error messages for better debugging.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@Graur please review this one

**Review by Graur — APPROVED** [review]
@maxonfjvipon Good one!
@yegor256 Could you please take a look?

**Comment by maxonfjvipon** [comment]
@yegor256 please have a look

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
