### PR TITLE
bug(#3619): added sugar for compact tuples

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Closes: #3619

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Review by yegor256 — APPROVED** [review]
ok

**Comment by yegor256** [comment]
@maxonfjvipon perfect, thanks!

**Comment by 0crat** [comment]
@maxonfjvipon Thanks for the contribution! You've earned +4 points for this: +4 as a basis; -8 for too many hits-of-code (529 >= 200); -4 for very few (2) comments; +12 to give you at least something. Please, [keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) them coming. Your running balance is [+20](https://www.eolang.org/zerocracy/objectionary-vitals.html).

**Pull request merged**
