### PR TITLE
#769 force Locale.US for printf

### PR DESCRIPTION
**Pull request by mximp**
Fix for #769

### CODE REVIEW

**Comment by yegor256** [comment]
@mximp no tests? It's usually better to add a test to reproduce the problem, and then make the changes to fix it. A pull request without a test is a bad idea in general.

**Comment by mximp** [comment]
> @mximp no tests? It's usually better to add a test to reproduce the problem, and then make the changes to fix it. A pull request without a test is a bad idea in general.

@yegor256 the issue is by itself to fix broken test: `org.eolang.txt.sprintf-tests.eo:prints-complex-string`. 
The change is already covered by several existing tests.

In order to fully validate the specific case the tests must be run under specific environment (with default JVM locale equals to 'RU'). It seems quite excessive. Unless you see any simple way to do this.

**Comment by yegor256** [comment]
@mximp we need to make sure the test fails in our CI and inside Rultor, not only on your laptop. How to do this, I'm not yet sure. I tried this, but didn't work:

```
$ LC_ALL=ru_RU.utf8 mvn clean test
```

**Comment by mximp** [comment]
@yegor256 the following probably would work for linux/macos:
```
@\> locale
LANG="ru_RU.UTF-8"
LC_COLLATE="ru_RU.UTF-8"
LC_CTYPE="ru_RU.UTF-8"
LC_MESSAGES="ru_RU.UTF-8"
LC_MONETARY="ru_RU.UTF-8"
LC_NUMERIC="ru_RU.UTF-8"
LC_TIME="ru_RU.UTF-8"
LC_ALL=
@\> export LANG="en_US.UTF-8"
@\> locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```

The only issue is that we need to run separate test run to configure such env.
Do we want to set up a separate workflow for this?

**Comment by mximp** [comment]
@yegor256 changes for testing the case are ready.
Pls review and merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@mximp thanks!

**Pull request merged**
