### PR TITLE
684 malloc

### PR DESCRIPTION
**Pull request by levBagryansky**
#Closes 684
@Graur please review.
Implemented heap.malloc and heap.free on eo.
I chosed [linear allocation](https://github.com/mtrebi/memory-allocators#linear-allocator)  because of its simplicity and the highest speed. However, this allocation requires more memory when creating a `heap`.

### CODE REVIEW

**Comment by yegor256** [comment]
@Graur pls, take a look

**Review by Graur — APPROVED** [review]
@levBagryansky Looks good to me
@yegor256 Please, have a look

**Comment by levBagryansky** [comment]
@yegor256 please check

**Comment by levBagryansky** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
@rultor merge

**Comment by Graur** [comment]
@levBagryansky Looks like it's a broken container. These tests are disabled. 
@yegor256 Can we try one more time?

**Comment by levBagryansky** [comment]
@yegor256 could you try again please?

**Comment by yegor256** [comment]
@rultor mege

**Pull request merged**
