### PR TITLE
1112 xsl id check

### PR DESCRIPTION
**Pull request by mximp**
#1112 implement XSL id checks

### CODE REVIEW

**Comment by mximp** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
@mximp all looks cool, but why do you need to repeat the plugin in each module? It will be executed one in the parent module and that's it. Isn't it?

**Comment by mximp** [comment]
> ... It will be executed one in the parent module and that's it. Isn't it?
@yegor256 see my comment: https://github.com/objectionary/eo/issues/1112#issuecomment-1249030623

This _stub_ plugins are required to suppress plugin execution in every module.

**Comment by yegor256** [comment]
@mximp got it now. To avoid confusion, it's better to say `<phase>never</phase>` in each of them. It will be clearer for the reader.

**Comment by mximp** [comment]
@yegor256, please check

**Comment by yegor256** [comment]
@mximp still not perfect. Let's add `id` to the execution both in parent module and in all child modules. This will guarantee that in the future a mistake won't happen, when someone will add `id` to the parent. Also, I suggest to put `<configuration>` inside `<execution>`. Now, the configuration applies to all executions, which is again a potential cause of confusion.

**Comment by mximp** [comment]
@yegor256 please check.
If I got the idea correctly - `id`s has to be the same in parent and children, right?

**Comment by yegor256** [comment]
@mximp yes, now it's correct, but you don't need to specify `<goals>` in child modules. You disable the entire `<execution>` by `<phase>none`.

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
