### PR TITLE
feat(#2640): added snippet test for horizontal abstract syntax

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Closes: #2640

---

## PR-Codex overview
This PR focuses on adding test resources and snippets for simple-horizontal and complex-horizontal in the eo-maven-plugin. 

### Detailed summary
- Added test resource for simple-horizontal.yaml
- Added expected output for simple-horizontal.yaml
- Added file path for simple-horizontal.eo
- Added arguments for simple-horizontal.eo
- Added eo code for simple-horizontal.eo
- Added test resource for complex-horizontal.yaml
- Added expected output for complex-horizontal.yaml
- Added file path for complex-horizontal.eo
- Added arguments for complex-horizontal.eo
- Added eo code for complex-horizontal.eo

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@yegor256 please have a look

**Comment by yegor256** [comment]
@maxonfjvipon it's too simple. Let's make it more complex, to see a number of named attributes on the same line:


```
+package simple
+alias org.eolang.io.stdout
+alias org.eolang.io.sprintf

[args...] (stdout msg > @) (sprintf "Hello, %s!" name > msg) ("Jeff" > name) > main
```

**Comment by maxonfjvipon** [comment]
@yegor256 please have a look one more time

**Comment by yegor256** [comment]
@maxonfjvipon will merge after this one is fixed: https://github.com/objectionary/eo/issues/2660

**Comment by yegor256** [comment]
@maxonfjvipon I'm ready to merge this one, but I'm sure it won't work because of varargs inside. Please, fix it.

**Comment by maxonfjvipon** [comment]
@yegor256 please have a look

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
