### PR TITLE
Ctor_changed

### PR DESCRIPTION
**Pull request by MCJOHN974**
#625

### CODE REVIEW

**Comment by MCJOHN974** [comment]
@yegor256 does it mean that I should create ```OyRemoteTest.java``` ?

**Comment by Graur** [comment]
@MCJOHN974 You should start from reading [this part](https://github.com/objectionary/eo#how-to-contribute). After running full Maven build, you will see what is wrong.

**Comment by yegor256** [comment]
@MCJOHN974 the build is not clean in your branch

**Comment by MCJOHN974** [comment]
@yegor256 i runned ```mvn clean install -Pqulice``` in master and my branch and both times have the same error. Error was in ```OyFallback.java``` but I edited just ```OyRemote.java```. I don't think that adding a constructor can brake ```OyFallback.java```. Does it mean that I should fix ```OyFallback.java``` too ?

**Comment by yegor256** [comment]
@MCJOHN974 read this: https://www.yegor256.com/2018/07/24/bugs-or-pull-requests.html If you see a bug in master, report a ticket. If you don't see it, make a pull request.

**Comment by yegor256** [comment]
@MCJOHN974 what's up with this? will you continue or we close this?

**Pull request closed without merging**
