### PR TITLE
bug(#3757): Conservative to-phi conversion

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Closes: #3757

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Review by yegor256 — APPROVED** [review]
OK

**Comment by 0crat** [comment]
@maxonfjvipon Thanks for the contribution! You've earned +4 points for this: +4 as a basis; -8 for too many hits-of-code (282 >= 200); -4 for very few (1) comments; +12 to give you at least something. Please, [keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) them coming.

**Comment by 0crat** [comment]
@yegor256 Thanks for the review! You've earned +4 points for this: +4 as a basis; -10 for very few (1) comments; +10 to give you at least something.  Your running balance is [-8](https://www.eolang.org/zerocracy/objectionary-vitals.html).

**Pull request merged**
