### PR TITLE
feat(#1678): Check reserved chars in `add-probes.xsl`

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
1. Added check for "reserved" characters in `add-probes.xsl`
2. Also only some characters were left ('$', '^', '@', '<'), since other can't be declared in `base` attribute (I can be mistaken here, please correct me if I'm wrong)
3. Added some checks to `add-probes.yaml` pack test.

Closes: #1700

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
@mximp @MikhailLipanin guys, could you take a look, please?

**Review by mximp — APPROVED** [review]

**Comment by mximp** [comment]
@volodya-lombrozo this PR says it closes #1678 but it's already closed. Why is that?

**Comment by volodya-lombrozo** [comment]
@mximp Merge conflict (puzzle was modified in another PR)

**Comment by volodya-lombrozo** [comment]
@mximp Fixed
@yegor256 Could you merge that changes, please?

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
