### PR TITLE
#3008: Enabled and edited tests

### PR DESCRIPTION
**Pull request by levBagryansky**
## PR-Codex overview
This PR updates the `PhLocated` class to include a new `location` parameter and adds unit tests for the `PhLocated` class.

### Detailed summary
- Added a new `location` parameter to the `PhLocated` class constructor
- Added a test case for saving location after copying in `PhLocatedTest`
- Updated test cases for Rust functions in `rust-tests.eo`

> The following files were skipped due to too many changes: `eo-runtime/src/test/eo/org/eolang/rust-tests.eo`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by levBagryansky** [comment]
@maxonfjvipon please check

**Review by maxonfjvipon — APPROVED** [review]

**Comment by levBagryansky** [comment]
@yegor256 please check

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Comment by levBagryansky** [comment]
@yegor256 please check

**Comment by levBagryansky** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
