### PR TITLE
bug(#3698): Remove object versioning

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Closes: #3698

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Comment by maxonfjvipon** [comment]
@yegor256 
1. they are already disabled for a long time (almost a year) and everything works fine 
image
2. some of them are not relevant anymore, for example `rewritten_sources` or `hash_package_layer`
3. some of them are already implemented as unit tests
4. we have `Jaxec` now, so if something goes wrong in the future - we can use it instead

**Comment by yegor256** [comment]
@maxonfjvipon well, it's a good practice (and a very very common practice) to use invoker for Maven plugin testing. It's just something people always do in Maven world. I suggest keeping one of them in place (fibonacci, for example) and getting rid of all others. WDYT?

**Comment by maxonfjvipon** [comment]
@yegor256 please check one more time, I fixed `fibonacci` integration test and enabled it

**Comment by yegor256** [comment]
@maxonfjvipon perfect, thanks!

**Pull request merged**
