### PR TITLE
#1206 latex directory created and has empty files

### PR DESCRIPTION
**Pull request by potatmen**
@Graur here `latex` directory created and has all `.xmir` files stored in `03-optimize` + `universe.txt`. For now, they are empty, without any content (I was recommended to split this issue to some small), later I will add parsing from `.xmir` to phi-calc. For now this version is not passing `qulice`, if all is ok I will refactor code to pass `qulice` checks

### CODE REVIEW

**Comment by Graur** [comment]
@potatmen If you want to split this issue to small ones, you need to use [PDD](https://www.yegor256.com/2017/04/05/pdd-in-action.html). And take care of the checkstyle violations in your code

**Comment by potatmen** [comment]
@Graur Please take a look

**Comment by potatmen** [comment]
@Graur oh sorry, I mistakenly deleted file, will fix it now

**Comment by potatmen** [comment]
@Graur Sorry for mess, It's done now

**Comment by potatmen** [comment]
@Graur Strangely that all commits aren't shown like I made them, there is only name `potatmen` but no profile picture

**Pull request closed without merging**
