### PR TITLE
feat(#1821) Move integration tests into a separate module

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
Since it's impossible to run integration tests on `parent` level, I have created one more module with integration tests and placed it after all other modules.
[Discussion](https://stackoverflow.com/questions/39612692/how-can-i-run-integration-tests-after-building-all-modules-in-a-multi-module-mav).

We steel need to deploy tuple to objectionary to make integration tests work.

Closes: #1821

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
@mximp Could you have a look, please?

**Comment by yegor256** [comment]
@volodya-lombrozo I understand the intent, but this is not how maven projects are tested, according to Maven philosophy (as I understand it). `it` tests are not "integration tests", but "invoker tests", which are supposed to be located in the same module where the Maven Plugin is located. we test the plugin, not the entire reactor. Also, having a special module just for tests (even if they are integration), is a bad idea, I believe. Mostly because, such a detachment of tests from the "system under test" is risky -- it will be harder to catch errors right when they happen.

**Comment by volodya-lombrozo** [comment]
@yegor256 

**ChatGTP**:
> In a Maven project, the `src/it` directory typically stands for "integration tests" and is a standard directory for placing integration test source code and resources.
Integration tests are used to test how different components of a system work together, as opposed to unit tests that test individual units of code in isolation. The `src/it` directory is used to store integration test code and resources, such as configuration files, test data, and scripts.
When you run mvn verify on a Maven project, the integration tests in the `src/it` directory are executed along with the unit tests in the `src/test` directory. The results of the integration tests are reported separately from the unit test results.
It's worth noting that the directory structure of a Maven project is configurable, so it's possible for a project to have a different directory structure than the standard one. However, the `src/it` directory is a commonly used convention for integration tests in Maven projects.

**Comment by volodya-lombrozo** [comment]
@yegor256 We have the significant problem that decrease speed of development. Actually we have cyclic dependency.

1. `eo-maven-plugin` requires `eo-runtime` to run integration tests
2. `eo-runtime` requires `eo-maven-plugin` to build itself.
3.  Integration tests require both `eo-maven-plugin` and `eo-runtime`

**Comment by mximp** [comment]
@volodya-lombrozo @yegor256 
Actually the issue with our set up is that `eo-maven-plugin` uses fixed (downgraded) version of `eo-runtime` and raw version of `eo-parser`. Changes in core parsing/syntax normally require modification in both `eo-runtime` and `eo-parser`. When it happens `eo-maven-plugin` integration tests become invalid. 
I believe we could solve the issue by fixing `eo-parser` within integration `pom` to whatever is compatible with fixed `eo-runtime`. With such set up IT tests will be decoupled from the changes we make and `eo-maven-plugin` won't fail.

**Comment by volodya-lombrozo** [comment]
> @volodya-lombrozo @yegor256
> Actually the issue with our set up is that `eo-maven-plugin` uses fixed (downgraded) version of `eo-runtime` and raw version of `eo-parser`. Changes in core parsing/syntax normally require modification in both `eo-runtime` and `eo-parser`. When it happens `eo-maven-plugin` integration tests become inconsistent.
> I believe we could solve the issue by fixing `eo-parser` within integration `pom` to whatever is compatible with fixed `eo-runtime`. With such set up IT tests will be decoupled from the changes we make and `eo-maven-plugin` won't fail.

@mximp  Do I understand correctly, that you are going to separate `eo-maven-plugin` from current versions of `eo-parser` and `eo-runtime` and use only stable already deployed versions?

**Comment by volodya-lombrozo** [comment]
@yegor256 @mximp To he honest, I believe that it's good to have integration tests for the entire set of `eo-parser`, `eo-runtime` and `eo-maven-plugin` modules all together. It's quite useful to test everything works correctly with current versions.

**Comment by yegor256** [comment]
@mximp @volodya-lombrozo I think it's a good idea: to use the same version of eo-parser and eo-runtime in _invoker_ tests.

@volodya-lombrozo check this out: https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html (notice that `src/it` is primarily for plugins)

**Comment by volodya-lombrozo** [comment]
@mximp @yegor256 If we want to divide `eo-parser`, `eo-runtime`, `eo-maven-plugin`, then why do we keep them in a single repository? It's a quite confusing.

@yegor256 primaly != always.

**Comment by yegor256** [comment]
@volodya-lombrozo we don't want to divide them! I believe that should stay together because they depend on each other. If, for example, we move our parser away, it will be very hard to synchronize the changes made to the syntax with the changes in the runtime. We will be able to modify the parser and the runtime will fail, but later, when the parser is already released. Keeping them in sync will be a tougher task than now.

**Comment by volodya-lombrozo** [comment]
> @volodya-lombrozo we don't want to divide them! I believe that should stay together because they depend on each other. If, for example, we move our parser away, it will be very hard to synchronize the changes made to the syntax with the changes in the runtime. We will be able to modify the parser and the runtime will fail, but later, when the parser is already released. Keeping them in sync will be a tougher task than now.

@yegor256 Now I understand. We want to keep/change them together, it's fine. Do you agree that it would be nice to check if everything altogether works correctly (especially if we want to synchronise the changes)? If you will set some hardcoded (fixed) versions of `eo-runtime` or `eo-parser` in integration tests then you will check how a new `eo-maven-plugin` works with old  `eo-runtime` and `eo-parser` libraries, it's strange and creates some problems with updating `eo-maven-plugin` (at least I have to disable integration tests in my case).

**Comment by volodya-lombrozo** [comment]
If we don't need common integration tests, I close that PR. In the future when we will face with the problem again, we can revive that PR.

**Pull request closed without merging**
