### PR TITLE
feat(#2146): Refactor tests in `eo-runtime` module

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
Refactor tests in `eo-runtime` module.

Closes: #2146

---

## PR-Codex overview
This PR removes and modifies several test classes in the `eo-runtime` module. Notable changes include:

### Detailed summary
- Deleted `DataizedLogLevelTest.java` and `EOfailed.java`
- Modified `EOerrorTest.java`, `EOas_phiTest.java`, `EOstringEOsliceTest.java`, `EOboolEOandTest.java`, `EOstringEOas_bytesTest.java`, `EObytesEOconcatTest.java`, `EOintEOplusTest.java`, `EOintEOnegTest.java`, `EOramEOramSliceTest.java`, `EOintEOminusTest.java`, `EOintEOeqTest.java`, `EOintEOltTest.java`, `EOheapEOpointerEOblockTest.java`, `EOtupleEOatTest.java`, `EOstringTest.java`, `EOboolEOnotTest.java`, and `EOcageTest.java`
- Removed configuration block in `pom.xml`

> The following files were skipped due to too many changes: `eo-runtime/src/test/java/EOorg/EOeolang/EOcageTest.java`, `eo-runtime/src/test/java/EOorg/EOeolang/EOboolEOwhileTest.java`, `eo-runtime/src/test/java/org/eolang/DataizedTest.java`, `eo-runtime/src/test/java/EOorg/EOeolang/EOio/EOstdinTest.java`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by Graur** [comment]
@volodya-lombrozo There are still some issues from Codacy

**Review by Graur — APPROVED** [review]
@volodya-lombrozo Good one!
@yegor256 Please have a look

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you merge that changes, please?

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
