### PR TITLE
test(#2120): Add test for synthetic-references.xsl with add-refs.xsl

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
This PR reveals the problem with `synthetic-attributes.xsl` and `add-refs.xsl` - missing `@line` attribute.
Related to #2120

---

## PR-Codex overview
This PR adds a test for synthetic attributes optimization chain, ensuring its correctness. It also adds several XSL transformations and fixes a missing `@line` attribute issue.

### Detailed summary
- Adds test for synthetic attributes optimization chain
- Adds several XSL transformations
- Fixes missing `@line` attribute issue

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
Blocked by #2111

**Comment by volodya-lombrozo** [comment]
@Graur Could you have a look, please?

**Review by Graur — APPROVED** [review]
@volodya-lombrozo Good one
@yegor256 Please, have a look

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you merge that changes, please?

**Pull request merged**
