### PR TITLE
map.keys and multimap.keys added

### PR DESCRIPTION
**Pull request by EugeneDar**

### CODE REVIEW

**Comment by EugeneDar** [comment]
@yegor256 tests that have nothing to do with my changes are crashing.

**Comment by yegor256** [comment]
@rultor merge

**Comment by EugeneDar** [comment]
@yegor256 rultor crushes because of `[ERROR]   DataizedTest.logsCorrectly:71 » IndexOutOfBounds Index: 0, Size: 0`

**Comment by yegor256** [comment]
@EugeneDar if you know how to fix, please submit a PR

**Comment by EugeneDar** [comment]
@yegor256 please merge again.

**Comment by EugeneDar** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@EugeneDar thanks!

**Pull request merged**
