### PR TITLE
feat(#1443): move optimization logic to separate classes

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
I've created new classes `OptTrain` and `OptSpy` that incapsulate optimization logic. Optimization function was removed from `OptimizationMojo`. 

Closes: #1443

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
@mximp Take a look, pls.

**Comment by volodya-lombrozo** [comment]
@yegor256 merge, please

**Comment by volodya-lombrozo** [comment]
@yegor256 reminder

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
