### PR TITLE
fix(#2291): remove synthetic objects + prohibit scopes in the head of application

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Closes: #2291 
Closes: #415 

See more details [here](https://github.com/objectionary/eo/issues/2291#issuecomment-1731432729)

---

## PR-Codex overview
This PR focuses on removing the `scopes.xsl` file and making various changes to the codebase. 

### Detailed summary
- Deleted `scopes.xsl` file and related test files.
- Updated `scopes.yaml` test file.
- Updated `full-syntax.yaml` test file.
- Updated `runtime-tests.eo` file.
- Updated `OptimizeMojoTest.java` file.
- Updated `Program.g4` file.
- Updated `ParsingTrain.java` file.
- Updated `Objects.java` file.
- Updated test files related to scopes and methods.
- Updated `ObjXembly` class.

> The following files were skipped due to too many changes: `eo-parser/src/test/resources/org/eolang/parser/packs/optimize/redundant-levels-with-arrays.yaml`, `eo-parser/src/main/java/org/eolang/parser/XeListener.java`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@Graur please review this one

**Review by Graur — APPROVED** [review]
@maxonfjvipon These changes are very important and can significantly affect to the language. I am ok with them, but I prefer to get one more opinion about these changes. It is up to you of course.

**Comment by maxonfjvipon** [comment]
@yegor256 please have a look

**Comment by yegor256** [comment]
@rultor merge

**Comment by maxonfjvipon** [comment]
@yegor256 please try to merge one more time

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
