### PR TITLE
2716 too long unit tests

### LINKED ISSUE #2716: Extremely long unit tests in eo-runtime
Unit tests in `eo-runtime` project run extremely long time: 
```
eo-runtime ......................................... SUCCESS [04:37 min]
```

I believe `4min` for unit test is extremely long. A close look on tests itself shows that only a few tests run so long:
```
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.382 s - in EOorg.EOeolang.EOtuple_fluent_withTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.607 s - in EOorg.EOeolang.EOrefers_to_inner_vars_correctlyTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.396 s - in EOorg.EOeolang.EOcalculates_only_once_BROKENTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.196 s - in EOorg.EOeolang.EOrecursion_without_argumentsTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 10.831 s - in EOorg.EOeolang.EOcage_nested_objectsTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 10.789 s - in EOorg.EOeolang.EOdataizes_encaged_object_lazily_firstTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 25.733 s - in EOorg.EOeolang.EOswitch_simple_caseTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 83.445 s - in EOorg.EOeolang.EOswitch_with_several_true_casesTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 84.961 s - in EOorg.EOeolang.EOswitch_strings_caseTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 102.758 s - in EOorg.EOeolang.EOswitch_complex_caseTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 122.704 s - in EOorg.EOeolang.EOtuple_with_negative_index_gets_firstTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 217.928 s - in EOorg.EOeolang.EOdataizes_encaged_object_lazily_thirdTest
```

Maybe it makes sense to move this tests to integration tests section, or just optimize the current tests somehow?

### PR DESCRIPTION
**Pull request by levBagryansky**
Closes #2716 
Now `SnippetCase` is the bottleneck in fast passing of tests in `eo-runtime`:
```
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.362 s -- in EOorg.EOeolang.EOcalculates_only_once_BROKENTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 7.775 s -- in EOorg.EOeolang.EOswitch_strings_caseTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.096 s -- in EOorg.EOeolang.EOswitch_with_all_false_casesTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.113 s -- in EOorg.EOeolang.EOswitch_with_several_true_casesTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 17.07 s -- in EOorg.EOeolang.EOswitch_complex_caseTest
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 120.2 s -- in org.eolang.SnippetTestCase
```
We already tag such tests "slow" in `eo-maven-plugin`, see https://github.com/objectionary/eo/blob/master/eo-maven-plugin/src/test/java/org/eolang/maven/BinarizeMojoTest.java#L60. So I think we can do the same here. Then `SnippetTestCase` tests will be passed with `qulice` profile only. 
BTW these tests cases are performed sequentially and cannot parallelized.

### CODE REVIEW

**Comment by levBagryansky** [comment]
@maxonfjvipon WDYT

**Comment by maxonfjvipon** [comment]
@levBagryansky if I got it right, tests with `slow` tag are not executed on regular `mvn `

**Comment by levBagryansky** [comment]
@maxonfjvipon yes

**Comment by levBagryansky** [comment]
@maxonfjvipon please approve

**Review by maxonfjvipon — APPROVED** [review]

**Comment by levBagryansky** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
