### PR TITLE
feat(#3251): introduced `listen`, `accept`, `bind`, `send`, `recv` posix socket objects

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Ref: #3251

---

## PR-Codex overview
This PR focuses on enhancing the handling of socket operations in both Windows and POSIX systems, including the introduction of new syscalls and improvements to existing tests for socket functionality.

### Detailed summary
- Updated `addr.eq` values in `win32-tests.eo` and `posix-tests.eo`.
- Removed `Integer.reverseBytes` in `InetAddrSyscall.java`.
- Added `SetLastError` method in `Kernel32.java`.
- Simplified test conditions in `EOwin32Test.java`.
- Introduced new `ListenSyscall`, `SendSyscall`, `RecvSyscall`, and `BindSyscall` classes.
- Enhanced `EOsocketTest` to include tests for socket operations with improved error handling.
- Created `RandomServer` class for random port server setup.
- Added detailed comments and documentation throughout the new and modified code.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Review by yegor256 — APPROVED** [review]
@maxonfjvipon LGTM, thanks!

**Comment by 0crat** [comment]
@maxonfjvipon Great contribution! 🌟 You've earned +4 points for your effort. While we noticed a high hit-of-code count (1643) and few comments, we appreciate your hard work. Your running balance is now [+40](https://www.eolang.org/zerocracy/objectionary-vitals.html). Keep the contributions coming and remember to [focus on quality](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) in your next submission. Every improvement counts!

**Comment by 0crat** [comment]
@yegor256 Hey there! 👋 Great job on the review! You've snagged +10 points for your effort. Here's the breakdown: +4 as the base reward, +16 for tackling a whopping 1643 hits-of-code (impressive!), but we had to deduct 10 points due to the low comment count (just 1). Remember, more comments can boost your score next time! Your current balance sits at [-35](https://www.eolang.org/zerocracy/objectionary-vitals.html). Keep up the good work and aim for those extra points by leaving more detailed feedback! 💪

**Pull request merged**
