### PR TITLE
feat(#3415): `malloc.resize` introduced

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Closes: #3415

---

## PR-Codex overview
This PR focuses on enhancing the memory allocation functionality in the `EOmalloc` module, specifically addressing resizing of memory blocks, adding size retrieval, and improving error handling in the `Heaps` class.

### Detailed summary
- Added `EOmalloc$EOof$EOallocated$EOsize` for retrieving the size of allocated blocks.
- Introduced `EOmalloc$EOof$EOallocated$EOresize` for resizing allocated blocks.
- Enhanced error messages in the `Heaps` class for clarity.
- Updated tests to cover new resizing and size retrieval functionalities.
- Improved handling of negative size resizing attempts.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
@rultor merge

**Comment by maxonfjvipon** [comment]
@yegor256 it seems rultor feels bad again(

**Comment by 0crat** [comment]
@maxonfjvipon Thanks for your contribution! Your effort is appreciated, but there's room for improvement. You've earned +4 points: +4 base, -8 for 358 hits-of-code (≥200), -16 for no code review, -4 for only 5 comments, +28 adjustment. Remember, our [policy](https://www.yegor256.com/2014/11/14/hits-of-code.html) rewards efficient code and thorough reviews. [Keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) refining your approach! Your balance is now [+20](https://www.eolang.org/zerocracy/objectionary-vitals.html).

**Pull request merged**
