### PR TITLE
feat(#3251): introduced `path` object

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Ref: #3251 

---

## PR-Codex overview
The PR focuses on refactoring file handling in the EO language runtime. 

### Detailed summary
- Refactored file handling methods in `PhPackage.java`
- Updated file and directory operations in `dir-tests.eo`
- Added new functionalities for text manipulation in `text.eo` and `text-tests.eo`
- Improved file path handling in `file.eo` and `path-tests.eo`

> The following files were skipped due to too many changes: `eo-runtime/src/test/eo/org/eolang/fs/path-tests.eo`, `eo-runtime/src/main/eo/org/eolang/fs/path.eo`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Review by yegor256 — APPROVED** [review]
@maxonfjvipon LGTM

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
@yegor256 Thanks for the review! You've earned +55 points for this: +25 as a basis; +40 for the 1134 hits-of-code that you reviewed; -10 for very few (3) comments.  Your running balance is [+240](https://www.eolang.org/zerocracy/objectionary-vitals.html).

**Comment by 0crat** [comment]
@maxonfjvipon Hey there, coding champ! 👨‍💻 Thanks for your hard work on this contribution! You've earned +5 points, which might seem low, but here's the breakdown: You started with a solid 25 points, but we had to deduct some for the high number of [hits-of-code](https://www.yegor256.com/2014/11/14/hits-of-code.html) (1134 is quite a lot!) and the low comment count. We added 7 points to keep you motivated. Remember, [quality over quantity](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) is key! Keep the contributions coming, and aim for more concise code with thorough reviews next time. Your current balance is [+170](https://www.eolang.org/zerocracy/objectionary-vitals.html). You've got this! 💪

**Pull request merged**
