### PR TITLE
added documentation about testing `eo-parser`

### PR DESCRIPTION
**Pull request by Graur**
Closes: #1545

---

## PR-Codex overview
This PR adds documentation on how to test EO code in the `eo-parser` package. It includes a step-by-step guide on creating YAML files for testing, and details on the different sections of the YAML file.

### Detailed summary
- Added a step-by-step guide to test `EO` code in `eo-parser` package.
- Documented how to create YAML files for testing.
- Explained the different sections of the YAML file.
- Provided an example of a YAML file for testing.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by Graur** [comment]
@levBagryansky @yegor256 How do you think is this documentation clear? Or I need to add more details about how these tests are working?

**Comment by yegor256** [comment]
@levBagryansky it's your call

**Comment by levBagryansky** [comment]
@Graur This addition, as for me, explains the process of writing tests very well, thank you!

**Comment by Graur** [comment]
@yegor256 Please, merge these changes

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
