### PR TITLE
ddr mojo

### PR DESCRIPTION
**Pull request by OlesiaSub**
#1197

### CODE REVIEW

**Comment by yegor256** [comment]
@Graur check this out pls

**Comment by OlesiaSub** [comment]
@Graur it's not ready yet. I'll ping you when it'll be ready for checking

**Comment by Graur** [comment]
@OlesiaSub You can make it a [draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request#converting-a-pull-request-to-a-draft)

**Comment by OlesiaSub** [comment]
@Graur fyi, Yegor asked me to add the project I'm currently working on ([ddr](https://github.com/objectionary/ddr)) to the build process. He also wanted to add it to objectionary/home build files. It would allow me to run a huge number of tests on my project without manually adding them to my repo.
DDR it still raw, so it won't be run by default.

**Comment by OlesiaSub** [comment]
@Graur reminder

**Comment by Graur** [comment]
@OlesiaSub I don't see any tests for this `DdrMojo`. How can I be sure it works?

**Comment by OlesiaSub** [comment]
@Graur I'm in two minds about it. Yegor wanted me to add this mojo for me to be able to test my DDR tool better. Right now DDR has many tests in its repository, but I'm lacking real integration tests, that's why Yegor wanted to integrate my tool into the build process and run the build script with all the tests with my tool inside. It would give me a huge amount of tests. But I needed to add this mojo first for him to be able to do so.

This mojo is already included into AssembleMojo and therefore participates in many other tests. I can add a test just to ensure that this mojo is indeed doing something though.

**Comment by Graur** [comment]
@OlesiaSub It's clearer now, thanks. But still, if I set `executeDdr` to `true` will I get a new folder?

**Review by Graur — APPROVED** [review]
@yegor256 Please, take a look

**Comment by Graur** [comment]
@yegor256 @OlesiaSub  I believe we can close this pull request

**Comment by yegor256** [comment]
@OlesiaSub we will do this in the objectionary/eoc tool

**Pull request closed without merging**
