### PR TITLE
feat(#3251): windows `socket.connect` syscall

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Ref: #3251

---

## PR-Codex overview
This PR focuses on enhancing the handling of network socket connections in the `Win32` environment, specifically improving the `inet_addr` function and adding tests for both POSIX and Win32 socket connections.

### Detailed summary
- Added tests for valid POSIX and Win32 `inet_addr` handling.
- Modified `inet_addr` in `InetAddrSyscall.java` to reverse bytes.
- Implemented `connect` and `WSAGetLastError` functions in `Winsock.java`.
- Updated `EOwin32$EOφ` to include new socket functions.
- Created `InetAddrFuncCall` and `ConnectFuncCall` for Win32.
- Enhanced error handling in socket connection tests.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Review by yegor256 — APPROVED** [review]
@maxonfjvipon LGTM

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
@yegor256 Hey there! 👋 Thanks for your review work! You've earned +4 points this time. Here's the breakdown: +4 base points, -10 for having just 4 comments (we love feedback!), and +10 to keep you motivated. Remember, more code and comments can boost your score next time! Your current balance is [-67](https://www.eolang.org/zerocracy/objectionary-vitals.html). Keep up the good work and let's see that number climb! 💪

**Comment by 0crat** [comment]
@maxonfjvipon Hey there, coding champ! 👋 Thanks for your contribution! You've snagged +4 points this time around. Here's the breakdown: +4 base points, -8 for your 465 [hits-of-code](https://www.yegor256.com/2014/11/14/hits-of-code.html) (over 200), -4 for only 3 comments (we love feedback!), and +12 to keep you motivated. Remember, [quality and speed](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) are key! Keep the code coming, but aim for smaller, more focused contributions next time. Your current balance is [+40](https://www.eolang.org/zerocracy/objectionary-vitals.html). Keep up the great work! 💻🚀

**Pull request merged**
