### PR TITLE
#3015: compare hashcodes of parents

### LINKED ISSUE #3015: UniverseDefaultTest.java:39-41: Enable the tests. The...
The puzzle `2931-86a23c6e` from #2931 has to be resolved: 

https://github.com/objectionary/eo/blob/e7e56f0cf06ea2e08f24289bea4fcfd9762d01b7/eo-runtime/src/test/java/org/eolang/UniverseDefaultTest.java#L39-L41

The puzzle was created by maxonfjvipon on 27-Mar-24. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

### PR DESCRIPTION
**Pull request by levBagryansky**
Closes #3015 
The only solution I find is to compare parents of these objects.

---

## PR-Codex overview
This PR updates the `UniverseDefault` class by replacing character constants with enum constants and refactoring attribute names in the test class.

### Detailed summary
- Replaced character constants with enum constants in `UniverseDefault.java`
- Refactored attribute names in `UniverseDefaultTest.java`
- Updated test methods to use new attribute names

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@levBagryansky 
> The only solution I find is to compare parents of these objects.
This actually makes sense because `\rho` is not copied when it's dispatched

**Review by maxonfjvipon — APPROVED** [review]

**Comment by levBagryansky** [comment]
@yegor256 please check

**Comment by levBagryansky** [comment]
@yegor256 please check

**Comment by maxonfjvipon** [comment]
@yegor256 please check

**Comment by levBagryansky** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
@rultor merge

**Comment by levBagryansky** [comment]
@yegor256 please check

**Comment by levBagryansky** [comment]
@yegor256 please check

**Comment by levBagryansky** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
