### PR TITLE
feat(#1347): `OptimizeMojo` flexible parallelism 

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
I've implemented the issue slightly different comparing with the original puzzle description. I believe that we don't have to "choose" number of thread by hands, `java` can understand how many cores the System has. By that reason it's much easier to use `.parallelStream()` function that creates executor service with number of threads ~= number of cores. Using that method we don't need to use `ExecutorService` directly and set number of threads manually .

Closes: #1347 
___
You can read more about `parallelStream()` [here](https://docs.oracle.com/javase/tutorial/collections/streams/parallelism.html)

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
@mximp have a look, please

**Comment by volodya-lombrozo** [comment]
@mximp Please, check

**Review by mximp — APPROVED** [review]

**Comment by volodya-lombrozo** [comment]
@yegor256 merge

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
