### PR TITLE
#1305 Prohibit weak object typing outside of `org.eolang`

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Closes: #1305

---

### Focus of the PR:
This PR focuses on adding error handling for external weak-typed atoms and making changes related to package meta.

### Detailed summary:
- Modified `bool.eo` to change the `if` operator to use `?` instead of `t` and `f`.
- Added a `not` operator in `bool.eo`.
- Updated `catches-external-weak-typed-atoms.yaml` to include new XSL files for error handling.
- Added a new XSL file `external-weak-typed-atoms.xsl` in the `eo-parser` module for handling external weak-typed atoms errors.
- Modified `ParsingTrain.java` to include the new XSL file for error handling.
- Updated the content of `external-weak-typed-atoms.xsl` to handle errors related to weak typing of `/?` atoms outside the `org.eolang` package.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@Graur please review this one

**Comment by maxonfjvipon** [comment]
@yegor256 please have a look, since integration tests are disabled now - this PR can be merged

**Review by Graur — APPROVED** [review]
@maxonfjvipon Good one! BTW why integration tests are disabled?

**Comment by maxonfjvipon** [comment]
@Graur tuple implementation was changed (`to-java.xsl` also was changed because of that), but integration tests download `tuple` from objectionary where `tuple` is outdated

**Comment by maxonfjvipon** [comment]
@yegor256 please have a look

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
