### PR TITLE
feat(#3706): Found the Bug Related to Token Names

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
In this PR I:

1. Added human-readable messages to all the tests inside `EoIndentLexerTest`.
2. Added two more disabled tests that show the problem with icorrect naming of `TAB/UNTAB` tokens.

Related to #3706.

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you take a look, please?

**Comment by yegor256** [comment]
@maxonfjvipon make sense?

**Comment by volodya-lombrozo** [comment]
> @yegor256 yes, actually it's a common and annoying problem. Maybe I even know how to solve it @volodya-lombrozo LGTM

@maxonfjvipon Thank you for the review. I've already solved it. The solution just waits for this PR to be merged.

**Comment by yegor256** [comment]
@volodya-lombrozo thanks!

**Pull request merged**
